"""Advanced chain-of-thought — statistics, harder debugging, ML concepts, systems design."""
_STATS=[
    ('What is the difference between mean, median, and mode?','Mean = sum/count. Pulled by outliers (one billionaire skews average income). Median = middle value when sorted. Robust to outliers — better summary for skewed data. Mode = most frequent value. Useful for categorical or to spot the typical case. For symmetric distributions all three coincide; for skewed (income, house prices), median is honest, mean is misleading.'),
    ('What is standard deviation?','Measure of spread around the mean. Roughly: average distance of points from the mean (formally, sqrt of mean squared deviation). Small std = tightly clustered. Large = wide spread. Used in z-scores (how many std-devs above/below mean a point is), confidence intervals, hypothesis tests. For normal distribution: ~68% of data within 1 std, 95% within 2, 99.7% within 3 (the "empirical rule").'),
    ('What is correlation and what does correlation coefficient mean?','Measure of linear relationship between two variables. Pearson r ranges -1 to +1. +1 = perfect positive (as x rises, y rises proportionally). -1 = perfect negative. 0 = no linear relationship. |r| ≈ 0.3 weak, 0.5 moderate, 0.7+ strong. Correlation does NOT imply causation. Captures linear relationships only — two variables can be perfectly related (e.g., y = x²) with r near 0.'),
    ('What is statistical significance and a p-value?','p-value = probability of observing data this extreme (or more) if the null hypothesis is true. p < 0.05 traditionally called "statistically significant" — but this is convention, not magic. Misuses: (1) p-hacking (running tests until one is significant). (2) confusing significance with EFFECT SIZE (a tiny effect can be significant with huge sample). (3) treating p ≥ 0.05 as "no effect" instead of "no evidence in this study." Look at effect size + confidence interval, not just p.'),
    ('What is sample size and why does it matter?','Number of observations. Larger samples → more precise estimates, more statistical power. Required sample size depends on: expected effect size (smaller effects need bigger n), variability in data, desired confidence. Rule: doubling precision requires 4x sample size. Common error: drawing conclusions from a sample too small to detect realistic effect sizes — you reported "no difference" but never had power to find one.'),
    ('What is Bayes\' theorem in plain English?','Updates beliefs based on evidence. P(hypothesis | data) ∝ P(data | hypothesis) × P(hypothesis). Or: posterior ∝ likelihood × prior. Practical: rare disease (1 in 1000) with 99% accurate test — if you test positive, your odds of actually having it are ~10%, not 99%, because false positives among the 999 healthy people outnumber true positives. Always update FROM prior probability, not from zero.'),
    ('What is the difference between supervised and unsupervised learning?','Supervised: training data has LABELS (input → known correct output). Goal: predict output for new inputs. Examples: classification (spam/not-spam), regression (predict price). Unsupervised: no labels, find structure in data. Examples: clustering (group similar customers), dimensionality reduction (PCA), anomaly detection. Semi-supervised: small labeled + large unlabeled. Self-supervised: labels derived from data structure (next-token prediction in LLMs).'),
]
_ML=[
    ('What is overfitting and how to detect it?','Model memorizes training data instead of learning general patterns. Symptom: training accuracy ≫ validation accuracy. Causes: model too complex for amount of data, training too long, leakage of test info into training. Fixes: more data, regularization (L1/L2, dropout, weight decay), simpler model, early stopping (monitor val loss), data augmentation. Always hold out a clean test set you never train on.'),
    ('What is the bias-variance tradeoff?','Total error = bias² + variance + irreducible noise. Bias: error from wrong assumptions (model too simple). Variance: error from sensitivity to small fluctuations in training data (model too complex). Increasing capacity reduces bias but increases variance. Decreasing capacity opposite. Optimal model balances both. Ensemble methods (random forests, gradient boosting) cleverly reduce variance without paying full bias cost.'),
    ('What is a neural network in one paragraph?','Stacks of layers, each computing linear combinations of inputs followed by nonlinear activation. Earlier layers learn low-level features (edges in images), deeper layers learn higher-level concepts (faces). Trained via gradient descent on a loss function (MSE for regression, cross-entropy for classification). Architecture choices (convolutions, attention, recurrence) inject useful inductive biases. Modern LLMs are transformers — stacks of attention + feedforward blocks.'),
    ('What is gradient descent?','Iterative optimization to minimize a loss function. Compute gradient (slope) at current parameters, step in opposite direction (downhill), repeat. Step size = learning rate (too small: slow; too large: overshoots/diverges). Stochastic gradient descent (SGD) uses random subsets (mini-batches) — faster, escapes shallow minima. Adam, AdaGrad, RMSprop are common adaptive variants that adjust per-parameter learning rates.'),
    ('What is a transformer architecture?','Neural network built around the attention mechanism. Each token computes weighted combinations of all other tokens, weights determined by content similarity (query·key dot product). Parallelizable across sequence length, unlike RNNs. Stacks: multi-head attention → feedforward → repeat. Layer normalization + residual connections enable training deep nets. Introduced in "Attention is All You Need" (2017); the foundation of GPT, BERT, T5, and most modern LLMs.'),
    ('What is fine-tuning vs in-context learning?','Fine-tuning: update the model\'s weights on new task-specific data. Permanent specialization. Requires labeled data + compute. In-context learning: include examples in the prompt; model adapts behavior without weight changes. No training cost. LLMs do this surprisingly well. Use in-context for: prototyping, few-shot tasks, when you don\'t want weight drift. Use fine-tuning when: in-context can\'t reach quality, or you need specialized behavior reliably without huge prompts.'),
    ('What is prompt engineering?','Crafting input to LLMs to get better outputs. Techniques: (1) clear instructions + explicit format. (2) few-shot examples. (3) chain-of-thought ("think step by step"). (4) role assignment ("you are a senior engineer"). (5) decomposition (break into sub-questions). (6) self-consistency (sample multiple, vote). Limits: prompts get long, brittle to phrasing, model-specific. Better long-term: fine-tuning or RAG when stable behavior is needed.'),
]
_SYSTEMS=[
    ('How would you design a URL shortener?','Core: map long URL → short code → redirect. Components: (1) shortener service generates short codes (random base62, ~7 chars = 3.5 trillion). (2) KV store (Redis) maps code → URL. (3) Postgres for analytics (clicks, owner, expiry). (4) HTTP service for redirect (return 301 or 302). Scale concerns: cache hot URLs, handle collisions on random code, prevent abuse (rate limiting, malicious URL scanning), TTL for old codes. Bit.ly-class system fits comfortably on a few servers.'),
    ('How would you design a real-time chat system?','WebSocket connection per user. Server tracks user → connection mapping. Messages: sender → server → recipient(s). Persistence: store in DB for history + offline delivery. Scale: shard by conversation/room; use pub-sub (Redis, Kafka) so any server can broadcast to any user. Read receipts: ack from recipient → store + propagate. Push notifications when user offline (APNs, FCM). E2EE adds key exchange + per-message encryption.'),
    ('How would you design a rate limiter?','Token bucket: each user has N tokens, refills at rate R/sec. Each request consumes 1; reject if empty. Store buckets in Redis (atomic INCR + EXPIRE works). Sliding window: count requests in last N seconds. More accurate but heavier. Distributed: rate limit at API gateway (closer to client), not per service. Per-user AND per-IP for abuse prevention. Return 429 with Retry-After header.'),
    ('How would you design a notification service?','Producers (other services) send events. Service determines delivery channels (push, email, SMS, in-app) per user preferences. Queue (Kafka, SQS) decouples producer from delivery. Worker fans out to channel-specific dispatchers (FCM/APNs/SendGrid/Twilio). Idempotency: dedupe by event ID. Retry with backoff for transient failures. Dead-letter queue for permanent failures. Aggregate similar notifications (digest mode) to avoid spam.'),
    ('What is sharding and when do I need it?','Splitting data across multiple servers, each holding a subset. Typically by hash(key) % N or by range. Use when: single DB can\'t handle the data size OR the write load. Pain: cross-shard queries are slow/complex, rebalancing when adding shards, transactional consistency across shards is hard. Often easier than re-sharding: vertical scaling, read replicas, caching, or moving to a sharding-native DB (Cassandra, Cockroach, Vitess).'),
    ('What is eventual consistency in practical terms?','After a write, reads may briefly return stale data before all replicas converge. Examples: S3 (now strongly consistent for reads-after-writes since 2020), DNS (TTL-bounded staleness), social media feeds (you post, friend sees it seconds later). Design client to tolerate: don\'t assume "I just wrote it, I can read it." Use the write response as confirmation; query on demand only. Conflict resolution strategies: last-write-wins, vector clocks, CRDTs.'),
    ('What is a circuit breaker pattern?','Prevents cascading failures. Three states: closed (normal, requests pass through), open (after threshold of failures, requests fast-fail without calling), half-open (after timeout, allow trickle to test recovery). Stops a slow dependency from consuming all your threads/connections. Libraries: Hystrix, resilience4j, Polly. Pair with: bulkheads (isolate resources per dep), timeouts, retries with backoff + jitter, fallback responses (cached or degraded).'),
]
_DEEPER_DEBUG=[
    ('How do I debug an intermittent bug?','Make it reproducible FIRST — without reliable repro, you\'re guessing. Strategies: (1) increase logging around the suspected area, especially state at decision points. (2) add invariant assertions that catch bad state earlier. (3) record everything (request/response, all DB queries) then replay. (4) reduce environment chaos: same machine, same load, same data. (5) if rare under load: stress test until it triggers. (6) if timing-related: add random delays or run on slower CPU.'),
    ('My production system is slow but tests pass — diagnose?','Possible causes: (1) test data tiny vs prod (DB queries are O(n) but tests use n=10, prod has n=1M). (2) test runs sequentially; prod has concurrency / contention. (3) network latency (cross-region, slow DNS) absent in test. (4) memory pressure, GC pauses, swap. (5) DB stats/plan changed under load. Approach: profile in prod (sampling profiler), add tracing, compare slow vs fast requests, focus on differences in input data + concurrency.'),
    ('How do I find a memory leak?','Watch process RSS over time — if growing without bound, leak. Tools: tracemalloc (Python), heapdump (Node), pprof (Go), valgrind (C/C++). Common Python leaks: (1) unbounded global caches. (2) circular references involving __del__. (3) threads holding references to large objects. (4) C extension bugs. Bisect: when did it start growing? What changed? Reduce to minimal repro then attach profiler.'),
    ('How do I debug a race condition?','By definition non-deterministic — make it deterministic to study. Tools: thread sanitizer (TSan), Go\'s -race flag, Java JIT race detectors. Manual: add print/log of which thread acquired which lock in what order; look for inverted orders (deadlock) or unprotected shared writes. Reproduce by adding random delays before suspected critical sections — exposes races that timing usually hides. Fix: mutex, atomic ops, immutable data, message passing instead of shared state.'),
    ('How do I debug a performance regression after a deploy?','Compare flame graphs before/after the change. Look for: (1) new hot paths in the diff. (2) higher call counts (loops, recursion accidentally re-introduced). (3) different query plans (DB stats changed, new index missing). (4) larger payloads (someone added a field that\'s now serialized everywhere). git bisect the deploy commits if needed; revert + reapply piecemeal. Don\'t guess — measure.'),
]
LESSONS=_STATS+_ML+_SYSTEMS+_DEEPER_DEBUG
