"""Advanced algorithms — graph, DP, string, interview-pattern questions with worked solutions."""
_GRAPH=[
    ('What is topological sort?','Linear ordering of nodes in a DAG such that for every edge u→v, u appears before v. Use cases: task scheduling with dependencies, build systems (make), course prerequisites. Algorithm 1: Kahn\'s — repeatedly remove a node with in-degree 0. Algorithm 2: DFS — post-order traversal in reverse. O(V+E). Cycle in graph → no topological order possible (detected when Kahn\'s leaves nodes or DFS finds back-edge).'),
    ('How does Prim\'s algorithm work?','Minimum spanning tree of weighted undirected graph. Greedy: start with one node, repeatedly add the lowest-weight edge connecting tree to a non-tree node. Priority queue keyed on edge weight. O((V+E) log V) with heap. Use Prim when graph is dense (many edges per node). Use Kruskal (sort edges, union-find) when sparse.'),
    ('How does Kruskal\'s algorithm work?','Also MST. Sort all edges by weight ascending. Greedily add each edge that connects two previously-disconnected components (check via union-find). Stop when V-1 edges added. O(E log E) with sort. Use when sparse (few edges).'),
    ('What is Floyd-Warshall?','All-pairs shortest path. Triple nested loop over intermediate node k: `dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])`. O(V³). Handles negative edges (but NOT negative cycles — detected if dist[i][i] becomes negative). Use when you need all-pairs distances on small (V<500) graphs.'),
    ('What is Bellman-Ford?','Single-source shortest path with negative edges allowed. Relax all edges V-1 times. O(VE). Detects negative cycles (one more relaxation in iteration V → cycle exists). Use when Dijkstra can\'t (negative edges). Slower than Dijkstra so prefer Dijkstra when applicable.'),
    ('What is a Union-Find (Disjoint Set Union) data structure?','Maintains a partition of elements into disjoint sets. Two ops: find(x) returns set representative; union(x,y) merges sets containing x and y. With union-by-rank + path compression, both ops are O(α(n)) — practically O(1). Use cases: Kruskal\'s MST, connected components, dynamic connectivity, Hoshen-Kopelman.'),
    ('How do I find connected components?','Two ways. BFS/DFS: pick unvisited node, traverse all reachable, mark them; repeat. Each traversal = one component. O(V+E). Union-Find: union(u,v) for each edge; component = find(v) value. Use BFS/DFS for one-shot computation; Union-Find for dynamic edges (online algorithm).'),
    ('What is the difference between DFS and BFS?','DFS: stack-based (or recursion), goes deep before wide, uses O(depth) memory, finds cycles, computes topological order. BFS: queue-based, level-by-level, uses O(width) memory, finds shortest unweighted path, computes distances from source. BFS is the right choice for "minimum number of steps" problems. DFS for structural questions (is connected, is acyclic, components).'),
]
_DP=[
    ('What is the longest common subsequence problem?','Given two sequences, find the longest sequence that appears in both (preserving order, not necessarily contiguous). DP: dp[i][j] = LCS of first i of A, first j of B. If A[i]==B[j], dp[i][j] = dp[i-1][j-1] + 1, else max(dp[i-1][j], dp[i][j-1]). O(mn) time + space. Reconstruct by tracing back through dp table. Foundation of diff algorithms.'),
    ('What is the edit distance (Levenshtein) algorithm?','Min insertions/deletions/substitutions to transform string A into B. DP: dp[i][j] = edits to convert first i of A to first j of B. If A[i]==B[j], dp[i][j] = dp[i-1][j-1]. Else 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) (delete/insert/substitute). O(mn). Used in spell checkers, fuzzy search, DNA alignment.'),
    ('How does the 0/1 knapsack DP work?','N items each with weight w[i] and value v[i]; pick subset to maximize value with total weight ≤ W. dp[i][w] = max value using first i items with weight cap w. Transition: dp[i][w] = max(dp[i-1][w], dp[i-1][w-w[i]] + v[i]). O(NW). Space-optimize to 1D array, iterate weight backward to avoid reusing items.'),
    ('How does the longest increasing subsequence work?','Longest strictly-increasing subsequence in array. Naive DP: dp[i] = LIS ending at i = max(dp[j] + 1 for j<i if a[j]<a[i]). O(n²). Better: maintain a sorted "tails" array; for each element binary-search and replace (or extend). O(n log n). The tails array isn\'t the LIS itself; reconstruct by tracking predecessors.'),
    ('What is the coin change problem?','Min number of coins to make amount N from given denominations (unlimited supply each). DP: dp[i] = min coins for amount i. Transition: dp[i] = min(dp[i-c] + 1 for c in coins if c ≤ i), dp[0] = 0. O(N * len(coins)). Variant: count number of ways (similar DP, sum instead of min). Classic interview problem with many follow-ups.'),
    ('What is matrix chain multiplication?','Find optimal parenthesization to minimize scalar multiplications when multiplying chain of matrices. DP: dp[i][j] = min cost to multiply matrices i..j. Try every split point k: dp[i][j] = min(dp[i][k] + dp[k+1][j] + dims[i-1]*dims[k]*dims[j]). O(n³). Classic interval DP — pattern applies to many problems (e.g., burst balloons, palindrome partitioning).'),
]
_STRINGS=[
    ('What is KMP and what problem does it solve?','Knuth-Morris-Pratt: finds all occurrences of a pattern in a text in O(n + m). Preprocesses pattern into a "failure function" that tells you, when a mismatch occurs at position j, what\'s the longest prefix of pattern[0..j] that\'s also a suffix — so you can shift the pattern without rescanning text characters. Beats naive O(nm) for repetitive patterns.'),
    ('What is a trie and when use it?','Tree where each path from root to a node spells a prefix. Each node has up to alphabet-size children. Use for: autocomplete (find all words with prefix X), spell checking, longest common prefix, IP routing tables. Space-time tradeoff vs hash set: trie supports prefix queries but uses more memory. Variants: compressed trie (Radix), Patricia tree, Aho-Corasick (multi-pattern matching).'),
    ('How do I check if a string is a palindrome?','Two-pointer technique: i=0, j=len-1; while i<j: if s[i]!=s[j] return false; i++; j--; return true. O(n) time O(1) space. For "longest palindromic substring": Manacher\'s algorithm O(n), or expand-around-center O(n²) (simpler, often acceptable). Even-length vs odd-length palindromes need separate cases or use Manacher\'s trick of inserting separators.'),
    ('How do I detect an anagram pair?','Sort both strings, compare: O(n log n). Or count characters in a fixed-size array (26 letters), compare counts: O(n). For Unicode, use a dict/hash map: O(n) average. To find all anagram groups in a list: hash by the sorted/canonical-counted form. Classic interview problem with many phrasings.'),
    ('What is Rabin-Karp?','String matching via rolling hash. Hash the pattern, hash each window of text, compare hashes (cheap), confirm by char compare on hash match. O(n+m) average. Slides window by removing old char from hash and adding new char (the rolling part). Great for multi-pattern matching: hash all patterns, check each window\'s hash against the set.'),
]
_INTERVIEW=[
    ('Two sum problem — find two numbers in array that add to target','Naive: O(n²) nested loop. Better: hash map. For each x, check if target-x already seen; if yes return both indices, else add x to map. O(n) time O(n) space. Variant: sorted array → two-pointer i=0, j=len-1, move based on sum vs target. O(n) time O(1) space.'),
    ('How do I find the kth largest element in an array?','Quickselect: like quicksort but only recurse into the side containing position k. O(n) average, O(n²) worst. Heap-based: maintain min-heap of size k; for each item, push and pop if size > k. End: heap top = kth largest. O(n log k) — better for streaming or when k << n. Stdlib heap-based usually fine: heapq.nlargest(k, arr) in Python.'),
    ('How do I merge two sorted lists efficiently?','Two pointers. While both nonempty: take smaller head, advance that pointer, append to result. When one empties, append the rest of the other. O(n+m) time O(n+m) space. In-place for arrays needs auxiliary buffer or backward merge. Underlies merge sort.'),
    ('How do I find the longest substring without repeating characters?','Sliding window with a hash set/map. Two pointers L, R both at 0. Move R right, adding to set. If duplicate, move L right (removing from set) until duplicate gone. Track max(R-L+1) as you go. O(n) time O(min(n, alphabet)) space. Pattern: any "longest/shortest window with property" tends to be sliding window.'),
    ('How do I detect a cycle in a directed graph?','DFS with three colors: white (unvisited), gray (in current DFS path), black (fully done). If you reach a gray node, cycle. O(V+E). For undirected graphs, just don\'t count edge to immediate parent (or use Union-Find: edge between same-component nodes = cycle).'),
    ('How do I find the median of two sorted arrays?','Binary search for the partition point that splits both arrays into "left half" and "right half" of equal total length. Verify left max ≤ right min. O(log min(m,n)). Classic hard problem — full solution is tricky to get right, requires careful boundary handling. Memorize the partition idea.'),
    ('How do I clone a graph?','BFS or DFS from any node. Maintain dict mapping original_node → clone. For each visited node: create clone if not in map, recurse/queue neighbors, link clone to clone of each neighbor. Standard pattern, applies to clone-linked-list-with-random-pointer too.'),
    ('How do I rotate a matrix 90 degrees clockwise?','Two steps in-place: (1) transpose (swap m[i][j] with m[j][i] for i<j). (2) reverse each row. Or layer-by-layer rotation (more cache-friendly). O(n²) — must touch every cell.'),
    ('How do I find duplicates in O(n) time O(1) space if values are 1..n?','Mark seen by negating: for each value v, if a[abs(v)-1] is negative we\'ve seen it; else negate it. Or use cyclic sort: put each value in its "home" slot, then misplaced slots reveal duplicates/missing. Trick is exploiting that values are bounded to indices.'),
    ('How do I find all permutations of a string?','Backtracking. At each position, try each unused character, recurse, undo. Time O(n! * n) (n! permutations, each O(n) to copy). For unique perms with duplicates: sort + skip duplicates at each level. itertools.permutations in Python.'),
    ('How do I solve N-Queens?','Backtracking. Place queens row by row. For each row, try each column; check if safe (no same column, no diagonal conflicts with placed queens — track sets for col, row+col, row-col). Recurse; backtrack on dead ends. O(N!) worst but pruning is aggressive.'),
    ('How does Dijkstra handle a re-update of a node already popped?','Standard Dijkstra with non-negative weights: once popped, distance is final — don\'t re-push. But with the LAZY approach using priority queue, you may push the same node multiple times when distance improves; when you pop, check if popped distance > current best (skip if so). Both correct; lazy is simpler to implement.'),
]
LESSONS=_GRAPH+_DP+_STRINGS+_INTERVIEW
