"""Software architecture patterns — MVC, hexagonal, event-driven, CQRS, domain modeling."""
_PATTERNS=[
    ('What is MVC and what are common misuses?','Model-View-Controller. Model = data + business rules. View = presentation. Controller = handles input, updates model, picks view. Common misuse: putting business logic in controllers ("fat controllers"). Better: thin controllers, fat models, dumb views. Modern frameworks (Rails, Django) follow MVC. React + Vue blur it (component owns both view + local state).'),
    ('What is hexagonal architecture (Ports + Adapters)?','Application core is independent of external systems (DB, UI, API, queue). Core defines PORTS (interfaces); ADAPTERS implement them for specific tech. Swap MySQL → Postgres = swap adapter, core untouched. Tests don\'t need real DB — use in-memory adapter. Concrete result: layered code (domain → application → adapters) with dependencies pointing INWARD.'),
    ('What is Clean Architecture?','Robert Martin\'s name for hexagonal-style layering. Four concentric circles: Entities (business objects) → Use Cases (business rules) → Interface Adapters (controllers, presenters) → Frameworks (DB, web). Dependencies point inward only. Outer layers can change without inner-layer code edits. Critique: heavy ceremony for small apps; valuable for long-lived large systems.'),
    ('What is event-driven architecture?','Components communicate by emitting/consuming EVENTS via a broker (Kafka, NATS, RabbitMQ). Producer doesn\'t know who consumes. New consumers added without changing producers. Excellent for: decoupling services, audit/replay, fan-out, integrating heterogeneous systems. Trade-offs: eventual consistency, harder to trace, ordering challenges, contract evolution.'),
    ('What is CQRS?','Command-Query Responsibility Segregation. Writes (commands) and reads (queries) use different models/stores. Write model optimized for consistency (normalized schema, ACID). Read model denormalized for query speed (materialized views, cache, search index). Synced via events (often event sourcing). Useful when read + write patterns differ wildly. Overkill for simple CRUD.'),
    ('What is event sourcing?','Store domain changes as a sequence of immutable events (UserCreated, EmailChanged, PasswordReset). Current state = replay of events. Pros: full audit trail, time-travel debugging, derive new read models from history. Cons: complexity, schema evolution of events, replay performance for long-lived aggregates. Pairs well with CQRS. Snapshot periodically to avoid replaying entire history.'),
    ('What is Domain-Driven Design (DDD)?','Software structure mirrors the business domain — ubiquitous language shared by devs + domain experts. Key concepts: bounded context (a model is consistent within), aggregate root (consistency boundary for writes), value object (immutable identity-less), domain service (logic not belonging to one entity). Most useful for: complex business domains. Overhead for simple CRUD.'),
    ('What is a microservice vs a monolith vs a modular monolith?','Monolith: one deployable, easy to refactor, hard to scale teams. Microservices: many deployables, each small + independent — scales teams, hardens fault isolation, costs distributed-systems complexity. Modular monolith: one deployable but disciplined module boundaries (no cross-module DB access). Best of both for many apps. Don\'t start with microservices — extract them when monolith pain forces it.'),
    ('When should I extract a microservice?','When (1) a piece of the monolith has different scaling needs OR (2) a team needs to deploy independently OR (3) it has a clear bounded context with stable interface OR (4) fault isolation justifies the cost. NOT when: just to follow trends, when team is small (<20 devs), when boundaries unclear. Wrong extraction = distributed monolith — worst of both worlds.'),
    ('What is the strangler fig pattern?','Replace a legacy system incrementally. Wrap legacy with a facade (router). Route new features to a new service. Migrate existing features one at a time. Eventually the legacy is empty and removed. Pattern named after strangler fig trees that grow around host trees, eventually replacing them. Lower risk than big-bang rewrites (which usually fail).'),
    ('What is the saga pattern for distributed transactions?','Long-running business transaction across services, no global lock. Each step is a local transaction; if any fails, run COMPENSATING transactions to undo earlier steps. Two coordination styles: orchestration (central conductor calls services in order, handles failures) or choreography (services emit events, react). Saga ≠ ACID — partial visibility possible mid-saga. Design for it.'),
]
_DOMAIN_MODELING=[
    ('What is an aggregate in DDD?','Cluster of related entities treated as a single unit for data changes. Has one ROOT entity (aggregate root) — external code only references the root. Internal entities accessed through the root. Invariants (business rules) enforced inside the aggregate. Example: Order + OrderLines = aggregate, Order is root. Saving the order saves all lines atomically.'),
    ('What is the difference between an entity and a value object?','Entity: has identity that persists over time even as attributes change (User #5 is still User #5 after rename). Value object: identified by its attributes, immutable, interchangeable if equal (Money(100, USD) == Money(100, USD)). Make value objects immutable to avoid bugs. Common value objects: Money, Address, DateRange, GeoCoordinate.'),
    ('What is a bounded context?','A boundary within which a domain model is consistent. Outside it, the same concept may mean something different. Example: "Customer" in Sales context (lead, deal stage) is different from "Customer" in Support context (tickets, SLA). Each context owns its model. Inter-context: explicit translation (context map). Critical for microservices boundaries.'),
    ('What is anemic domain model anti-pattern?','Classes that hold data but no behavior — just getters/setters. All logic lives in "service" classes outside the domain. Result: business rules scattered, logic duplicated, no encapsulation. Symptom of accidental data-class style in OO. Fix: move behavior INTO the entity ("Order.place()", "User.changeEmail(newEmail)"). Encapsulate invariants there too.'),
    ('When should I use inheritance vs composition?','Inheritance for true subtype relationships (Dog IS-A Mammal) where Liskov substitution holds — anywhere parent is used, child can be substituted without surprises. Composition for everything else, especially behavior reuse (Logger HAS-A Formatter). "Favor composition over inheritance" because deep hierarchies become rigid; composed objects can be swapped at runtime. Most modern code: 90% composition, occasional inheritance for tight relationships.'),
]
_API_DESIGN=[
    ('What are characteristics of a good API?','(1) Consistent: same patterns throughout (naming, errors, paging). (2) Minimal: smallest surface that does the job — easier to evolve. (3) Predictable: behavior matches name + signature. (4) Backward-compatible: don\'t break existing consumers; version when needed. (5) Discoverable: docs + examples make 80% of cases obvious. (6) Failure modes clear: errors say what went wrong + how to fix.'),
    ('What is API versioning and best practices?','Make breaking changes additively. Strategies: URL path (/v1/users), header (Accept: application/vnd.myapi.v2+json), query param (?version=2). URL path most common — simple. Maintain old versions until usage drops below threshold. For internal APIs: prefer evolving than versioning (add field, never remove; deprecate slowly). Semver for libraries; calver (date-based) often for SaaS.'),
    ('What is HATEOAS?','Hypermedia As The Engine Of Application State — REST principle that responses include links to related resources/actions. Client doesn\'t hardcode URLs; follows links. Decouples client from URL structure. Reality: most "REST" APIs don\'t do HATEOAS — too much overhead for typical client/server pairs that ship together. Most useful for evolving public APIs.'),
    ('What is GraphQL vs REST?','REST: resources at URLs, multiple endpoints, you get what each returns (over/under-fetching common). GraphQL: single endpoint, client specifies exactly which fields it wants. Pros: efficient for mobile (precise data), strongly typed schema. Cons: caching harder (no URL hierarchy), complexity in resolver perf (N+1 risk), server complexity higher. Use GraphQL for: rich UIs with varied data needs. REST for: simple CRUD, caching matters, public APIs.'),
    ('What is the Richardson Maturity Model?','REST adoption levels. Level 0: HTTP as RPC tunnel. Level 1: resources (one URL per "thing"). Level 2: HTTP verbs + status codes (GET/POST/PUT/DELETE + 200/404/etc). Level 3: HATEOAS (links in responses). Most "RESTful" APIs are Level 2 in practice. Level 3 is rare; Level 2 captures most benefit.'),
]
LESSONS=_PATTERNS+_DOMAIN_MODELING+_API_DESIGN
