"""Cloud computing corpus — AWS/GCP/Azure services, serverless, IaC, FinOps."""
_AWS=[
    ('What is EC2?','AWS Elastic Compute Cloud. Virtual machines on demand. Many instance types (compute, memory, storage, GPU optimized). On-demand, reserved (1-3 year discount), spot (deep discount + interruptible). Auto-scaling groups for horizontal scale. Replaced by ECS/EKS/Lambda for many workloads, but still foundational.'),
    ('What is S3?','AWS Simple Storage Service. Object storage. Practically unlimited. Strong read-after-write consistency (since 2020). Use for: backups, static sites, data lake, ML datasets, anything not requiring filesystem semantics. Pricing: storage + requests + egress (egress is the gotcha). Versions, lifecycle (transition to Glacier), bucket policies.'),
    ('What is RDS?','AWS Relational Database Service. Managed Postgres, MySQL, MariaDB, Oracle, SQL Server. Handles backups, patching, replication, failover. Aurora variant: AWS-proprietary, performance + scale beyond stock. Use RDS to avoid running DB ops yourself. Cost trade-off: more expensive than self-hosted.'),
    ('What is IAM?','AWS Identity and Access Management. Who can do what on AWS resources. Users + groups + roles + policies (JSON). Principle: least privilege — grant minimum permissions needed. Service-to-service auth via roles (no long-lived keys). Hardest part of AWS to get right; spend time here.'),
    ('What is VPC?','AWS Virtual Private Cloud. Isolated network in AWS. Subnets (per AZ), route tables, NAT gateways, security groups (instance firewall), NACLs (subnet firewall). Default VPC is fine for many apps; custom for compliance / hybrid networking. Painful to redesign once running.'),
    ('What is CloudFront?','AWS CDN. Caches content at edge POPs near users. Pair with S3 for static sites (origin: bucket). Lambda@Edge for compute at edge. Compete with: Cloudflare, Fastly, BunnyCDN. AWS-friendly choice when already on AWS.'),
    ('What is CloudWatch?','AWS monitoring + logging. Metrics from AWS services + custom. Alarms. Log groups + streams. Dashboards. Cheap-ish for the first GB; can explode if you log everything. Modern: many teams use Datadog / Grafana / New Relic + ship to CloudWatch for AWS service metrics.'),
    ('What is EKS?','AWS Elastic Kubernetes Service. Managed control plane. You manage data plane (worker nodes — EC2 or Fargate). Easier than self-managing Kubernetes, harder than ECS. Use when: need k8s ecosystem + portability + AWS hosting.'),
    ('What is ECS?','AWS Elastic Container Service. Managed container orchestration. AWS-proprietary (not k8s). Simpler than EKS. Fargate launch type: serverless containers (no node management). Use for: AWS-native container apps without k8s complexity.'),
    ('What is Fargate?','AWS serverless compute for containers. Run containers without managing EC2 instances. Pay per second + per vCPU/memory. Use with ECS or EKS. Compare: Cloud Run (GCP), Container Apps (Azure). Modern preference over EC2-based clusters for many apps.'),
]
_GCP=[
    ('What is Cloud Run?','GCP\'s serverless container platform. Push a container, GCP runs it on demand, scales 0 to N, charges per request + CPU/memory. Easier than k8s. Best for: HTTP services, webhooks, simple APIs. Compare: AWS Fargate, Azure Container Apps.'),
    ('What is BigQuery?','GCP\'s serverless data warehouse. SQL queries on petabyte data. Columnar storage, separation of compute + storage. Charges per query bytes scanned + storage. Best for: analytics, ad-hoc analysis, dbt projects. Compare: Snowflake, Redshift, ClickHouse.'),
    ('What is Cloud Functions?','GCP serverless functions. Pay per invocation. HTTP triggers + event triggers (Pub/Sub, Storage). Compare: AWS Lambda, Azure Functions. Use for: event-driven glue code, webhooks, simple APIs.'),
    ('What is GKE?','Google Kubernetes Engine. Managed k8s on GCP. Most mature managed k8s (Google invented k8s). Autopilot mode: GCP manages nodes too. Use for: any k8s workload on GCP.'),
    ('What is Spanner?','GCP\'s globally-distributed SQL database. Strong consistency across regions via TrueTime. ACID transactions globally. Use for: massive scale + strong consistency. Expensive. Powers Gmail, AdWords.'),
]
_SERVERLESS=[
    ('What is serverless?','Computing model where infrastructure scaling + provisioning is fully managed. You write functions/containers; cloud runs them. Pay per actual execution, not idle time. Pros: zero ops, auto-scale, cheap for sporadic. Cons: cold starts, vendor lock-in, harder to test locally, slower for sustained loads. Sweet spot: event-driven workloads, low-traffic APIs, webhooks.'),
    ('What is a cold start?','When a serverless function spins up a new container/runtime to handle a request. Cost: 100ms-several seconds depending on runtime. Mitigations: keep functions warm (scheduled pings), smaller deployment packages, faster runtimes (Cloudflare Workers ~5ms, lighter languages), provisioned concurrency (always-warm but costs more).'),
    ('What is the difference between serverless and containers?','Serverless: function-or-container as a unit; scale per request; cold start cost; usually short-lived. Containers (ECS/EKS/Cloud Run): longer-lived processes; no cold starts (warm) but you pay for idle. Modern blur: Cloud Run scales from 0 (serverless-like), Fargate hides EC2 management. Pick by traffic shape + ops appetite.'),
]
_IAC=[
    ('What is Terraform?','Infrastructure as Code tool. Declare desired infrastructure in HCL files; Terraform creates/updates resources via cloud APIs. State file tracks managed resources. Supports all major clouds + 1000s of providers. Use for: reproducible infra, code review of infra changes, multi-environment. Modern: OpenTofu (fork after license change).'),
    ('What is Pulumi?','Infrastructure as Code with real programming languages (TypeScript, Python, Go, C#) instead of HCL. Same model as Terraform (declarative, state). Pros: loops, conditionals, abstractions you already know. Cons: less tooling than Terraform. Pick if you prefer code over HCL.'),
    ('What is CloudFormation?','AWS-native IaC. JSON/YAML templates. Native AWS integration. Limited to AWS. CDK (Cloud Development Kit) wraps CloudFormation with TypeScript/Python — like Pulumi for AWS only. Pick over Terraform if AWS-only + want native AWS support.'),
    ('What is Ansible?','Configuration management + IaC. Agentless (SSH). YAML playbooks. Use for: configuring existing VMs, app deployment, ad-hoc remote commands. Compare to: Chef, Puppet (older, with agents), Salt. Modern containerized workflows reduce need (immutable deploys via Docker).'),
    ('What is GitOps?','Git is the source of truth for infrastructure + app config. CI/CD watches git; reconciles deployed state to match. Tools: ArgoCD, Flux (Kubernetes-specific). Benefits: audit trail = git log, code review of changes, easy rollback (revert commit). Standard pattern for Kubernetes deployments.'),
]
_FINOPS=[
    ('What is FinOps?','Cloud cost management as discipline. Visibility (who spends what), optimization (right-size, savings plans, spot), governance (tagging, budgets, alerts). Tools: AWS Cost Explorer, GCP Billing, Azure Cost Management, third-party (CloudHealth, Vantage). Common wins: idle resources, oversized instances, unattached EBS volumes, untagged spend, untransitioned S3.'),
    ('Why is cloud egress so expensive?','Data leaving the cloud (to internet, to another region, to another cloud) typically costs $0.05-0.12 per GB — vs storage at fractions of a cent. Locks you in (moving data out = expensive). Avoid: stay in same region as compute, cache aggressively (CDN), use providers without egress fees (Cloudflare R2). Architecture decision: data gravity is real.'),
    ('What is reserved instance vs spot vs on-demand?','On-demand: pay-as-you-go, full price, anytime. Reserved (RI) / Savings Plans: commit 1-3 years, 30-72% discount. Spot: unused capacity, up to 90% off, but can be reclaimed with seconds notice. Strategy: baseline load on reserved, burst on on-demand, fault-tolerant batch on spot.'),
]
LESSONS=_AWS+_GCP+_SERVERLESS+_IAC+_FINOPS
