"""Coding corpus — algorithms, data structures, design patterns, debugging, language idioms.
Each lesson teaches Adam to think like a senior engineer: WHEN, WHY, and pitfalls — not just WHAT."""
_ALGORITHMS=[
    ('How does binary search work?','Requires SORTED input. Maintain low/high pointers. Loop: compute mid = (low+high)//2. If arr[mid] == target, found. If arr[mid] < target, search right half (low = mid+1). Else search left half (high = mid-1). Stop when low > high (not found). O(log n) time, O(1) space. Classic bug: use (low + high) // 2 risks overflow in some languages — write low + (high - low) // 2 in C/Java.'),
    ('When should I use binary search?','When (1) data is sorted (or can be sorted once and queried many times), AND (2) you need to find elements, insertion points, or boundaries by comparison. Also for "guess the answer" problems where you can verify whether a guess is too high/low — e.g., find smallest x such that f(x) >= target. The trick: any problem with monotonic predicate is binary-searchable.'),
    ('How does quicksort work?','Pick a pivot. Partition: elements < pivot go left, > pivot go right. Recurse on each partition. Best/average O(n log n), worst O(n²) on already-sorted input with naive pivot. Mitigation: random pivot or median-of-three. In-place possible. Not stable (equal elements may reorder). Used by most language stdlibs underneath the hood (often as a hybrid with insertion sort for small partitions).'),
    ('What is the difference between merge sort and quick sort?','Merge: stable, guaranteed O(n log n), needs O(n) extra space, good for linked lists. Quick: in-place (O(log n) stack), faster constants, but O(n²) worst case, not stable. Use merge sort when stability matters or worst-case guarantee is critical. Use quick sort for in-memory arrays where average performance dominates. Both are O(n log n) average.'),
    ('How does a hash table work?','Array of buckets. To insert (key, value): compute hash(key) % size to pick bucket; store there. Collisions handled by chaining (linked list per bucket) or open addressing (probe to next slot). Lookup is O(1) average if hash is good and load factor low. Resize when load factor exceeds threshold (~0.7) — doubles size, rehashes all keys. Worst case O(n) if all keys collide.'),
    ('When use a hash table vs array vs tree?','Array: ordered, fast index access O(1), slow contains O(n). Hash table: no order, fast contains/insert O(1) average, no range queries. Balanced BST (like Python\'s sortedcontainers): ordered, O(log n) for everything, supports range queries. Pick based on access pattern: random by key → hash; sequential or by-position → array; sorted iteration or range → tree.'),
    ('What is dynamic programming?','Solve a problem by combining solutions to overlapping subproblems, storing each subproblem result once (memoization). Recognize DP when: (1) optimal substructure (problem decomposes into smaller of same type), (2) overlapping subproblems (same subproblem appears multiple times in naive recursion). Two styles: top-down with memo (recursive + cache), bottom-up tabulation (iterative, fill table). Classic problems: Fibonacci, knapsack, edit distance, longest common subsequence.'),
    ('How does Dijkstra\'s algorithm work?','Shortest path in graph with non-negative edge weights. Maintain priority queue keyed on tentative distance from source. Repeatedly: pop closest unvisited node, relax all its outgoing edges (update neighbor distances if shorter via this node). Marks node visited. Continue until target popped (or queue empty). O((V+E) log V) with heap. Fails with negative weights (use Bellman-Ford instead).'),
    ('What is BFS vs DFS — when to use which?','BFS = breadth-first search, expands neighbors level-by-level via queue. Finds shortest path in unweighted graphs. Uses O(width) memory. DFS = depth-first search, goes deep before backtracking via stack/recursion. Detects cycles, computes topological order, finds connected components. Uses O(depth) memory. BFS for shortest, DFS for exploration/structure.'),
    ('What is amortized complexity?','Average cost per operation across a sequence, even if individual ops are expensive. Classic: dynamic array push. Most pushes O(1), but every 2^n pushes trigger O(n) resize. Averaged: O(1) per push. Use when one bad op pays for many cheap ones. Formal techniques: aggregate, accounting, potential method. Not the same as average-case complexity (which is over random inputs).'),
    ('How does merge sort merge two sorted arrays?','Two pointers i, j at start of each array. Loop: compare arr1[i] vs arr2[j], take smaller, advance its pointer. When one runs out, copy rest of the other. Linear time O(n+m), needs O(n+m) output space. The "merge" idea underlies external sorting (sort more data than fits in RAM by merging sorted chunks).'),
    ('How to detect a cycle in a linked list?','Floyd\'s tortoise and hare. Two pointers, slow advances one step per iteration, fast advances two. If there\'s a cycle, fast will eventually catch slow (they meet inside the loop). If no cycle, fast hits null. O(n) time, O(1) space. The math: relative velocity is 1 step per iter, so they close any gap within the loop.'),
    ('What is the time complexity of common Python operations?','list[i]: O(1). list.append: O(1) amortized. list.insert(0, x): O(n). list.pop(): O(1). list.pop(0): O(n). x in list: O(n). x in set/dict: O(1) average. dict[k]: O(1). sorted(list): O(n log n). copy.deepcopy: O(n) or worse. Key takeaway: middle/front operations on list are slow; use collections.deque for queue-like access.'),
    ('What is recursion and when should I use it?','Function calls itself with a smaller subproblem until a base case. Use when problem has self-similar structure (trees, graphs, divide-and-conquer). Watch for: (1) base case clearly defined? (2) progress toward base case? (3) stack depth (Python default ~1000) — convert to iteration if too deep. Tail recursion is NOT optimized in Python; use loops for that pattern.'),
]
_PYTHON_IDIOMS=[
    ('How do I reverse a list in Python?','Three ways: (1) lst[::-1] returns a new reversed list (slicing, most Pythonic for new copy). (2) list(reversed(lst)) returns same via iterator (memory-efficient for one-pass iteration). (3) lst.reverse() reverses in place, returns None. Use slicing for new list, .reverse() when you want to mutate.'),
    ('What is a list comprehension and when should I use it?','Concise syntax for building lists: [f(x) for x in iterable if cond]. Use when transforming/filtering a collection in one step. Don\'t use when: logic is too complex (write a loop instead — readability wins), you want side effects (use a regular loop), or the result is huge (use a generator expression with () instead of [] to avoid materializing). Example: squares = [x*x for x in range(10)].'),
    ('How do I read a file in Python safely?','Use a context manager: `with open(path, encoding="utf-8") as f: data = f.read()`. The `with` guarantees file closes even on exception. Always specify encoding explicitly — relying on default is a source of cross-platform bugs. For large files use `for line in f:` to stream rather than reading all into memory.'),
    ('What is the difference between is and == in Python?','== checks VALUE equality (calls __eq__). is checks IDENTITY (same object in memory). Use == for almost everything. Use is only for: comparison with None (x is None), True, False, or to check if two variables point to the exact same object. Common bug: `x == None` works but `x is None` is preferred and faster.'),
    ('What is a Python generator and why use one?','A function with `yield` instead of `return`. Each call produces the next value lazily. Use when: (1) iterating over something too large to fit in memory, (2) values are expensive to compute and may not all be needed, (3) representing infinite sequences. Example: `def evens(): n=0; while True: yield n; n+=2`. Combine with itertools for powerful pipelines.'),
    ('What does *args and **kwargs mean?','*args captures positional arguments as a tuple. **kwargs captures keyword arguments as a dict. Use to accept variable arguments or to forward all arguments to another function: `def wrap(*a, **k): return inner(*a, **k)`. Inside, args is a regular tuple and kwargs is a regular dict. The names "args" and "kwargs" are convention only — the * and ** are what matter.'),
    ('How do I sort a list of dicts by a key?','Use the `key` argument with a lambda: `sorted(lst, key=lambda d: d["score"])`. Sort descending with `reverse=True`. For complex sort (sort by category then by score): `key=lambda d: (d["category"], -d["score"])`. The negative trick reverses one field while leaving others ascending. For attribute access on objects, use operator.attrgetter for speed.'),
    ('What is a decorator and when to write one?','Decorator wraps a function with extra behavior without modifying its body. Syntax: `@decorator` above the def. Common uses: logging, timing, caching (functools.lru_cache), input validation, retries, permission checks. Write your own when the same wrapping logic applies to many functions. Avoid writing decorators that hide important behavior — they make stack traces harder to read.'),
    ('How do I merge two dicts in Python?','Python 3.9+: `d3 = d1 | d2` (d2 wins on conflicts). Python 3.5+: `d3 = {**d1, **d2}`. Mutate in place: `d1.update(d2)`. For nested merge use a recursive function — none of the above merge nested dicts deeply. The "later wins" rule is critical to remember when reasoning about config merging.'),
    ('What is the GIL and when does it matter?','Global Interpreter Lock — only one Python thread executes bytecode at a time in CPython. Matters for CPU-bound work: threads do NOT give parallelism (use multiprocessing or async + native code). Doesn\'t matter for I/O-bound: GIL releases during I/O so threads CAN overlap network/disk waits. Free-threaded CPython (3.13+, experimental) removes the GIL but most libs aren\'t ready yet.'),
    ('What is the difference between deepcopy and copy?','copy.copy(x) makes a shallow copy: new outer container, but inner mutable objects shared with original. copy.deepcopy(x) recursively copies everything. Performance: deepcopy is much slower. Pitfall: shallow copy of a list of lists shares the inner lists — modifying one mutates the "copy." Use deepcopy when you need true independence; use json.loads(json.dumps(x)) for simple data structures (faster).'),
    ('How do I run a Python script as a module vs as a script?','As script: `python myfile.py` — __name__ == "__main__", relative imports break. As module: `python -m mypkg.myfile` — relative imports work, package-relative paths resolved properly. Always use the `-m` form for code that\'s part of a package. The `if __name__ == "__main__":` guard lets a file work both as importable module AND directly runnable.'),
    ('What is a context manager and how to write one?','Object with __enter__ and __exit__ methods, used with `with` statement. Guarantees cleanup (file close, lock release, transaction commit) even on exception. Easiest way to write one: `from contextlib import contextmanager` + decorator + `try/yield/finally`. Example: `@contextmanager\\ndef timer(): t0=time.time(); yield; print(time.time()-t0)`. Use for any setup/cleanup pair.'),
    ('How do I make a class iterable?','Implement __iter__ returning an iterator (often self) AND __next__ raising StopIteration when done. Or simpler: implement __iter__ as a generator function with `yield`. Or even simpler: subclass an existing iterable. Once iterable, the class works with for loops, list(), unpacking, etc., for free.'),
    ('What is duck typing?','"If it walks like a duck and quacks like a duck, it\'s a duck." Python checks at runtime whether an object has the method/attribute you use, not whether it\'s a specific type. Lets functions accept any object with the right interface. Trade-off: more flexible than static types, but errors only show at runtime. Modern Python increasingly uses type hints + Protocol classes to get the best of both.'),
]
_DEBUGGING=[
    ('Python TypeError: NoneType object has no attribute X — what does it mean?','You called .X on a value that is None. Trace back to where the None came from: (1) a function that should return a value but returned None (missing return statement, conditional path skipped). (2) dict.get(key) returned None because key not present (use default). (3) a regex search/match returned None on no-match. (4) list.append/sort returns None (in-place mutation). Fix at the source, not by adding `if x is not None:` everywhere.'),
    ('IndentationError: unexpected indent — common causes?','Python is whitespace-sensitive. Causes: (1) mixing tabs and spaces — pick one (PEP 8 says spaces, 4-wide) and configure editor to convert. (2) extra/missing indentation on a continuation. (3) pasted code with mismatched indent. Quick fix: select all → re-indent (most editors have this). Long-term fix: editor shows whitespace + configures auto-format on save.'),
    ('My code runs in Jupyter but fails as a script — why?','Three common reasons: (1) cells run in a single shared namespace — names defined earlier persist. Scripts start fresh. (2) Jupyter\'s default `display` shows last expression; scripts don\'t print unless explicit. (3) Jupyter automatically does `await` at top level for async; in script you need `asyncio.run()`. Solution: run notebook with "restart kernel and run all" — if it fails there, the same will fail as script.'),
    ('Function returns wrong result silently — how to debug?','Add a print/log at the function entry showing inputs, at exit showing output. Run with a known case where you know the right answer. If output is wrong, you have the inputs that trigger it — bisect the function body next: print intermediate values until you find the step that produces wrong data. Most "complex" bugs become obvious once you see the actual values vs expected.'),
    ('My test passes locally but fails in CI — diagnose?','Likely causes: (1) test depends on environment (env vars, file paths, locale, timezone). (2) test depends on order (uses state from prior test). (3) test depends on network or filesystem state. (4) timing/race condition that manifests under different CPU load. Fix priority: make test deterministic (mock external deps, set seeds, freeze time), then it will pass everywhere.'),
    ('How do I diagnose a memory leak in Python?','Use tracemalloc: tracemalloc.start(); ...run code...; snapshot = tracemalloc.take_snapshot(); for s in snapshot.statistics("lineno")[:10]: print(s). Shows top allocation sites. Also useful: objgraph.show_growth() to see object counts growing between checkpoints. Common leaks: circular references with __del__, global caches without bounds, threads holding references.'),
    ('Code is too slow — how to find the bottleneck?','Always profile first; do not guess. cProfile: python -m cProfile -o prof.out myscript.py; then snakeviz prof.out for visualization. For line-level detail: line_profiler. For memory: memory_profiler. The 80/20 rule almost always applies — one or two functions dominate. Optimize those, leave the rest. "Make it work, make it right, make it fast" — in that order.'),
    ('UnicodeDecodeError: how to handle?','You\'re reading bytes as text with wrong encoding. Fix: specify the correct encoding when opening: `open(path, encoding="utf-8")` (or whatever the file actually is — check with chardet or file command). If you don\'t care about exact reproduction, use `errors="replace"` to substitute bad bytes with replacement char. For binary data, open with mode="rb" and don\'t decode at all.'),
    ('Recursion limit exceeded — solutions?','Three options: (1) increase the limit (sys.setrecursionlimit(10000)) — works if you know the actual max depth is bounded. (2) convert to iteration with an explicit stack — preserves the algorithm, removes the limit. (3) use memoization to short-circuit repeated calls — if the recursion has overlapping subproblems, this collapses the depth. Generally option 2 is the cleanest long-term solution.'),
    ('JSON encoding error: Object of type X is not JSON serializable — fix?','json.dumps only knows native types (dict, list, str, int, float, bool, None). For others, pass `default=` argument: `json.dumps(obj, default=str)` converts everything else via str(). Better: write a custom serializer per type. For datetime: `default=lambda o: o.isoformat() if isinstance(o, datetime) else None`. For numpy arrays: `default=lambda o: o.tolist() if hasattr(o, "tolist") else None`.'),
]
_DESIGN_PATTERNS=[
    ('What is the singleton pattern and when use it?','Class that has only one instance globally. Implement by overriding __new__ to return the same instance, or via a module (modules ARE singletons). Use for: shared configuration, connection pools, loggers. Avoid because: hard to test (global state), violates dependency injection, makes parallel use harder. If you must, prefer dependency injection of the single instance over global access.'),
    ('What is the factory pattern?','Function or method that creates objects without exposing instantiation logic to the caller. Use when: (1) object construction is complex (multi-step, conditional). (2) you want to abstract over which concrete class is returned (depending on input or environment). Python often uses module-level factory functions instead of factory classes — simpler and equally effective.'),
    ('What is dependency injection?','Pass dependencies into a class/function rather than constructing them inside. Instead of `def f(): db = Database(); ...`, do `def f(db): ...` and have the caller create the db. Benefits: testable (inject mocks), composable (swap implementations), explicit (clear what a function needs). Done well, makes code dramatically more flexible. Done excessively, becomes "framework hell."'),
    ('What is the observer pattern?','Subject maintains a list of observers and notifies them on state changes. Observers register/unregister. Use for: event systems, model-view separation, reactive UIs. Modern alternatives: pub-sub, signals/slots (Qt), event streams (RxJS). Pitfall: observer ordering matters when one observer\'s action affects others; document the contract.'),
    ('What is the strategy pattern?','Encapsulate algorithms as interchangeable objects. Instead of `if mode == "fast": ...; elif mode == "accurate": ...`, define a Strategy class with execute() method, subclass for each variant, pass instance into the consumer. In Python often replaced by passing a function — Python has first-class functions so a class wrapping a single method is usually overkill.'),
    ('What is composition over inheritance?','Prefer "has-a" relationships over "is-a" when reusing behavior. Reasons: inheritance couples subclass to superclass internals; multiple inheritance has diamond problems; composition lets you swap implementations at runtime. Modern OO wisdom: use inheritance for genuine subtype relationships (Dog IS a Mammal), composition for behavior reuse (Logger HAS a Formatter).'),
    ('When should I use OOP vs functional style?','OOP fits when: state is core to the domain (entities with identity that change over time), behaviors cluster naturally around data (a User has methods that operate on user data), polymorphism via subtyping is genuinely useful. Functional fits when: transforming data through pipelines, parallelism (immutability eliminates races), testing (pure functions trivial to test). Most real code is a mix; the labels are religions, the techniques are tools.'),
    ('What is YAGNI?','"You Aren\'t Gonna Need It." Don\'t build features speculatively — wait until you actually need them. Speculation usually misses the real requirement; you build the wrong abstraction and now need to maintain it. Counterexample: building for a need you can\'t cheaply add later (security, scalability foundations). Default to YAGNI; deviate consciously.'),
    ('What is the DRY principle and its failure mode?','Don\'t Repeat Yourself: every piece of knowledge has a single, authoritative representation. The failure mode is over-applying it to coincidental similarity — two pieces of code that LOOK alike but represent different concepts. When the concepts diverge, the shared abstraction becomes a tangle. Better rule: WET (Write Everything Twice) — only DRY out when you see the SAME knowledge in three places.'),
    ('What is "principle of least surprise"?','API should behave the way a reasonable user would expect from the name and signature. Don\'t hide side effects. Don\'t make len(x) be O(n). Don\'t name a function get_X if it modifies state. Surprise is what causes bugs — users build mental models that disagree with reality. When in doubt, err on the side of explicit and predictable over clever.'),
]
_TOOLING_AND_LIBS=[
    ('What does git rebase do vs merge?','Merge: creates a commit joining two histories, preserving the divergence. Rebase: replays your commits on top of the target branch, making history linear. Rebase BEFORE pushing (clean history). Never rebase commits already pushed to shared branches (rewrites history others depend on). Modern workflow: `git pull --rebase` keeps feature-branch history clean.'),
    ('How do I undo the last git commit but keep the changes?','git reset HEAD~1 — uncommits but keeps changes in working dir (mixed reset, default). git reset --soft HEAD~1 also keeps changes AND keeps them staged. git reset --hard HEAD~1 DELETES the changes — dangerous, prefer the others. None of these affect already-pushed commits on shared branches; for those use `git revert` (creates a new commit that undoes).'),
    ('What is the difference between fetch, pull, and push?','fetch: download remote refs (branches, tags) but don\'t merge — safe to run any time. pull: fetch + merge (or rebase if configured) of upstream into current branch. push: send your local commits to remote. Common mistake: pull immediately after starting work on a branch already changed remotely → unnecessary merge commits. Fetch first, look at what changed, then decide whether to merge/rebase.'),
    ('How does pytest fixture work?','A function decorated with @pytest.fixture that creates/provides a value to tests that ask for it by name in their function signature. Scope: function (default, fresh per test), class, module, session. Teardown: use yield instead of return, code after yield runs after the test. Powerful for: db connections, temp dirs, mocked services. Avoid scope=session for mutable state — bleeds between tests.'),
    ('What is virtualenv and why use it?','Isolated Python environment with its own site-packages and pip. Each project gets its own venv, preventing dependency conflicts between projects. Create: `python -m venv .venv`. Activate: `.venv/Scripts/activate` (Windows) or `source .venv/bin/activate` (Unix). Install in venv, not globally. Use one venv per project; commit lockfile (requirements.txt or pyproject.toml + uv.lock) but NOT the venv dir.'),
    ('What is pip vs conda vs poetry vs uv?','pip: stdlib package installer, lowest common denominator. conda: handles non-Python deps (CUDA, R, system libs) — heavier. poetry: pip + dep resolver + project metadata + lockfile, popular for libraries. uv: very fast modern replacement for pip + poetry, by Astral (ruff team) — recommend for new projects. For most app code: uv or poetry. For data science / non-Python deps: conda.'),
    ('What does HTTPS actually protect against?','Three things: (1) eavesdropping — content is encrypted, attacker on wire sees ciphertext only. (2) tampering — content has integrity (HMAC), modification detected. (3) impersonation — server identity verified via certificate signed by trusted CA. HTTPS does NOT protect: server-side data (only in-transit), metadata (which sites you visit at the DNS/SNI level pre-ECH), or against a compromised endpoint.'),
    ('What is async/await and when use it?','Async = cooperative concurrency, NOT parallelism. async functions return coroutines; await suspends until the awaited thing completes, letting other coroutines run. Use for: I/O-bound work (network, disk) — overlap waits. Don\'t use for: CPU-bound work (use multiprocessing). Critical rule: don\'t mix sync and async carelessly — calling a blocking function from an async coroutine freezes the event loop. asyncio.to_thread() bridges them.'),
    ('What is the difference between TCP and UDP?','TCP: connection-oriented, reliable (lost packets resent), ordered (packets arrive in order), congestion control. Use for: HTTP, SSH, anything where every byte must arrive. Higher latency due to handshake + retransmits. UDP: connectionless, unreliable, unordered. Use for: real-time (voice/video), DNS, gaming — where retransmit is worse than loss. QUIC (HTTP/3) is UDP-based but adds TCP-like reliability + multiplexing.'),
    ('How does HTTPS handshake work?','Client sends ClientHello with supported ciphers + random nonce. Server replies with chosen cipher + cert + random nonce. Client verifies cert chain against trusted CAs. Both compute shared secret via key exchange (RSA, DH, ECDHE). Switch to symmetric encryption using derived key. From here on, all data is encrypted. Modern TLS 1.3 collapses this to 1 round trip (vs 2 for older versions).'),
]
_CODE_REVIEW=[
    ('How do I review a pull request well?','Read in this order: (1) PR description — what is the intent? (2) tests — what behavior is locked in? (3) code — does it match intent? Look for: clarity (would a new dev understand?), edge cases (null/empty/max/min), error handling (silent failures are worse than crashes), concurrency (shared state safe?), security (input validation, secrets), perf (obvious O(n²) over big data). Comment with WHY not just WHAT. Approve, request changes, or comment — be explicit.'),
    ('What are red flags in code review?','(1) "TODO" or "HACK" comments without ticket reference. (2) try/except that catches Exception and passes silently. (3) commented-out code (delete it, version control remembers). (4) hardcoded constants that smell configurable (URLs, timeouts, magic numbers). (5) new dep added for trivial use. (6) function longer than ~50 lines. (7) deep nesting (>3 levels). (8) repeated copy-paste blocks. (9) no tests for new behavior.'),
    ('How do I write a good commit message?','First line: imperative mood, ≤50 chars, summarizes WHAT changed. Example: "Fix race condition in cache eviction." Blank line. Body (wrap at ~72 chars): WHY the change is needed, not WHAT it does (the diff shows what). Reference issues: "Fixes #123". The first line shows in `git log --oneline` so make it count. Future-you reading `git log` should understand the intent without reading the diff.'),
    ('What is a code smell?','A surface pattern that suggests deeper design problems. Examples: long methods, large classes (god objects), too many parameters (>5), feature envy (method uses another class\'s data more than its own), shotgun surgery (a single change requires edits in many places), divergent change (one class changes for many different reasons). Smells don\'t prove a bug, they prompt a closer look.'),
    ('What does "premature optimization is the root of all evil" actually mean?','Knuth\'s full quote: "premature optimization is the root of all evil ... yet we should not pass up our opportunities in that critical 3%." Meaning: don\'t make code less clear for speed you haven\'t measured AND don\'t actually need. The "evil" is hand-tuning code to be cryptic before you know it\'s the bottleneck. NOT an excuse to write O(n³) when O(n log n) is obvious — algorithmic choice is design, not premature opt.'),
    ('When should I refactor?','Three rules: (1) follow the boy-scout rule — leave code cleaner than you found it. Small improvements compound. (2) refactor BEFORE adding a new feature when the existing structure makes the addition hard — "make the change easy, then make the easy change." (3) refactor when you read the code three times in a row and have to re-derive what it does — it\'s costing you and others time. Never refactor without tests covering the behavior; you\'ll break things.'),
]
_SECURITY=[
    ('What is [REDACTED] and how to prevent?','Attack: user-supplied input embedded in SQL string allows the user to inject arbitrary SQL. Example: `query = f"SELECT * FROM users WHERE name=\'{name}\'"` — if name = `\'; DROP TABLE users; --` the attacker drops the table. Prevention: NEVER concatenate user input into SQL. Use parameterized queries (placeholders): `cursor.execute("SELECT * FROM users WHERE name=?", (name,))`. The DB driver escapes safely.'),
    ('What is XSS and how to prevent?','Cross-site scripting: attacker injects JavaScript into a page viewed by other users, stealing cookies/sessions. Prevention: (1) escape user content when rendering as HTML — replace <, >, &, ", \' with their HTML entities. Modern frameworks (React, Vue) do this by default unless you use dangerouslySetInnerHTML. (2) set HttpOnly cookies so JS can\'t read them. (3) Content-Security-Policy header restricts which scripts can run.'),
    ('What is CSRF and how to prevent?','Cross-site request forgery: malicious site causes user\'s browser to make a request to your site, using the user\'s session cookie. Prevention: (1) CSRF tokens — server includes random token on each form/page, expects it back on submit; attacker\'s site can\'t guess it. (2) SameSite cookies — browser doesn\'t send cookies on cross-site requests by default (Lax or Strict). (3) check the Origin / Referer header.'),
    ('Why is hashing passwords with bcrypt better than SHA256?','SHA256 is fast — attacker with stolen hashes can try billions of passwords per second on GPU. Bcrypt is intentionally SLOW (configurable cost factor, target ~100ms per hash). Also includes per-password salt automatically. Modern alternatives: argon2 (winner of password hashing competition) or scrypt. NEVER use MD5, SHA1, or plain SHA256 for passwords. Even adding salt to SHA256 is much weaker than bcrypt.'),
    ('What is principle of least privilege?','Every component (user, process, service) should have only the permissions it needs to do its job, nothing more. Apply: (1) DB user for read-only API has SELECT only, no DELETE. (2) container runs as non-root by default. (3) API tokens scoped to specific repos. (4) production deploys can\'t reach dev. When something IS compromised, blast radius is limited.'),
    ('What is defense in depth?','Multiple layers of security so failure of one layer doesn\'t mean total compromise. Example: HTTPS in transit + encrypted at rest + access control on DB + audit log + anomaly detection. Each layer alone is fallible; combined they raise the bar. Anti-pattern: a single "magic" defense ("we have a firewall"). Plan for "what if X is bypassed?" at every layer.'),
    ('What are common API authentication methods?','(1) API key — simple shared secret in header. Low security; revoke per-key. (2) Bearer token (JWT or opaque) — short-lived, often via OAuth flow. (3) HMAC signing — request includes signature derived from body + secret; prevents tampering AND replay if timestamped + nonced. (4) mTLS — client AND server have certs. Highest security, hardest setup. Pick based on threat model and ops cost.'),
]
_ARCHITECTURE=[
    ('What is REST and what are common mistakes?','REST = stateless HTTP API using nouns (resources) + standard verbs (GET/POST/PUT/DELETE). Common mistakes: (1) verbs in URLs (`/getUser/5` vs `GET /users/5`). (2) inconsistent pluralization. (3) ignoring HTTP status codes (returning 200 with `{error: "..."}` in body). (4) breaking changes without versioning (no /v1/ prefix). (5) chatty endpoints (forcing N requests where 1 would do). REST is convention as much as protocol.'),
    ('What is idempotency and why does it matter?','Operation is idempotent if doing it multiple times has the same effect as doing it once. GET, PUT, DELETE are idempotent. POST is not (creates new resource each time). Matters because: networks fail, retries happen. If your operation is idempotent, the client can retry safely. Design for it: use client-supplied IDs so duplicate POSTs become updates, use unique constraints, use idempotency keys (Stripe pattern).'),
    ('What is the CAP theorem in plain English?','In a distributed system you can pick at most 2 of: Consistency (all nodes see same data), Availability (every request gets a response), Partition tolerance (system continues working despite network splits). In practice, networks DO partition, so you really pick between consistency and availability when a partition happens. Most systems pick eventual consistency (AP) for read paths, consistency (CP) for critical writes.'),
    ('What is eventual consistency?','Updates propagate to all replicas eventually, but at any given moment different replicas may show different values. Users may see stale or "ghost" data briefly. Trade-off: gives you high availability + partition tolerance. Examples: DNS, S3 (after 2020 it\'s strong consistency for object operations), social media feeds. Design clients to tolerate slightly-old data — don\'t assume "I just wrote it, so I can read it now."'),
    ('What is a microservice and when use it?','A small, independently deployable service that owns a specific bounded context. Communicates with others via APIs (REST, gRPC) or messaging. Use when: org is large enough that teams need to deploy independently, scaling needs differ per service, fault isolation matters. DON\'T use for small teams — monoliths are simpler and faster. Service boundaries should follow team boundaries (Conway\'s law).'),
    ('What is the difference between a queue and a topic?','Queue: each message consumed by ONE consumer (work distribution). Topic / pub-sub: each message delivered to ALL subscribers (event broadcasting). Same channel concept, different delivery semantic. Queue for tasks. Topic for events. Modern brokers (Kafka, NATS) let you have it both ways via consumer groups — multiple consumers in same group share the load, different groups each see all messages.'),
    ('What is a database transaction?','Group of operations that either ALL succeed or ALL fail — no partial state. ACID: Atomicity (all-or-nothing), Consistency (DB constraints preserved), Isolation (concurrent transactions don\'t interfere), Durability (committed data survives crash). Use when: a logical operation spans multiple writes (transfer money: debit + credit, both or neither). Cost: locks, potential deadlocks, performance overhead.'),
    ('What is an index in a database?','Auxiliary data structure (usually B-tree or hash) that maps column values to row locations. Speeds up SELECT WHERE / ORDER BY / JOIN on indexed columns from O(n) scan to O(log n) lookup. Costs: storage space, slower writes (must update index on insert/update/delete). Rule: index columns used in WHERE/JOIN, especially with high cardinality. Don\'t index every column blindly — perf gets worse.'),
]
LESSONS=_ALGORITHMS+_PYTHON_IDIOMS+_DEBUGGING+_DESIGN_PATTERNS+_TOOLING_AND_LIBS+_CODE_REVIEW+_SECURITY+_ARCHITECTURE
