"""Concurrency patterns across languages — threads, async, locks, channels, common bugs."""
_BASICS=[
    ('What is the difference between concurrency and parallelism?','Concurrency: multiple tasks interleaved (one CPU rapidly switching). Parallelism: multiple tasks literally simultaneously (multi-core). Concurrent code MAY run in parallel if hardware allows. Async = concurrency, threading = potential parallelism (modulo GIL in Python). Rob Pike: "concurrency is about dealing with many things at once, parallelism is about doing many things at once."'),
    ('What is a thread vs a process?','Process: isolated memory space, expensive to create, communicate via IPC (pipes, sockets, shared memory). Thread: shares process memory, cheap to create, communicate via shared variables (with locks). Threads are lighter but share = potential for races. Modern alternative for I/O: coroutines (async) — even lighter than threads, no preemption, cooperatively scheduled.'),
    ('What is a race condition?','Two or more threads access shared data, at least one writes, and the final state depends on timing. Result: nondeterministic bugs, data corruption, crashes. Classic: i++ from two threads — not atomic (load, add, store), can lose updates. Fixes: mutex around critical section, atomic ops, message passing instead of shared state, immutable data.'),
    ('What is a deadlock?','Two+ threads each waiting for a resource the other holds → all stuck forever. Classic: thread A holds lock 1 wants lock 2; thread B holds lock 2 wants lock 1. Detection: thread dump shows cycles. Prevention: (1) always acquire locks in same global order. (2) use try-lock with timeout + backoff. (3) use higher-level constructs (channels) that avoid lock-pairs entirely.'),
    ('What is a livelock?','Threads aren\'t blocked — they\'re actively responding to each other but making no progress. Like two people stepping side-to-side in a hallway. Different from deadlock (which is stuck). Fix: add randomized backoff so the dance breaks, or use priorities, or use a coordinator.'),
    ('What is a starvation?','A thread keeps failing to acquire resources because others always get there first. Common in unfair locks or priority inversion. Fix: fair queueing (FIFO lock), priority inheritance, or time-bound retries with backoff.'),
    ('What is the difference between a mutex and a semaphore?','Mutex: lock owned by ONE thread at a time, must be released by same thread. For mutual exclusion of a resource. Semaphore: counter — N threads can acquire simultaneously (binary semaphore = N=1 ≈ mutex but releasable by any thread). Use semaphore to limit concurrency (e.g., max 10 outbound HTTP requests at once).'),
    ('What is a condition variable?','Lets a thread sleep until some condition becomes true. Used WITH a mutex: lock, check condition, if false → wait (releases mutex, sleeps, reacquires on wakeup), if true → proceed. Signaller calls notify after changing state. Classic producer-consumer. Modern alternatives: blocking queues, channels (cleaner abstraction).'),
    ('What is a read-write lock?','Allows many readers OR one writer (mutual exclusion only between read+write or write+write). Faster than mutex for read-heavy workloads. Pitfalls: writer starvation if readers keep arriving (fix: writer-preference); upgrade-deadlock if two threads try to upgrade read→write. Modern: prefer immutable data structures or copy-on-write.'),
    ('What is atomic in concurrency?','Operation that completes indivisibly — no thread can see a partial result. Hardware-supported for word-sized reads/writes + CAS (compare-and-swap). Atomic counter avoids needing a mutex around i++. Languages expose: std::atomic (C++), AtomicInteger (Java), atomic crate / std::sync::atomic (Rust), atomics (JS SharedArrayBuffer). Faster than locks for simple data; locks for complex critical sections.'),
    ('What is a memory model?','Defines what writes one thread can observe from another and in what order. Hardware reorders memory operations for performance; compilers do too. Sequential consistency = simplest mental model (everything happens in some global order) but expensive. Relaxed memory models allow reordering. Use atomic operations + memory ordering (acquire/release/seq_cst) to constrain. Most app devs use mutexes/channels and let the runtime handle this.'),
]
_PATTERNS=[
    ('What is a channel for inter-thread communication?','Typed queue between threads/coroutines. Sender puts, receiver gets (blocks until item available). Unbuffered: rendezvous (send blocks until recv). Buffered: holds N items. Closed channels signal "no more data." Languages: Go (built-in), Rust (mpsc + crossbeam), Python (queue.Queue), Java (BlockingQueue). Beats locks for many problems because data flow is explicit.'),
    ('What is the actor model?','Each "actor" has private state + processes messages from its inbox sequentially. Actors communicate ONLY via messages (no shared mutable state). Failure isolation: an actor crashing doesn\'t corrupt others. Examples: Erlang/Elixir, Akka (JVM), Actix (Rust). Scales to massive concurrency because each actor is lightweight + isolated. Trade-off: harder for problems that need shared state.'),
    ('What is the producer-consumer pattern?','Producers create items, consumers process them, decoupled via a queue. Smooths bursts, allows different speeds, enables backpressure. Implementations: bounded queue (slow consumer slows producer = backpressure, prevents OOM), unbounded queue (can grow without bound). Patterns: thread pool consuming from queue, async tasks awaiting queue items.'),
    ('What is the future/promise pattern?','A placeholder for a value that will be available later. Threads can register callbacks or block waiting. Sync: thread blocks until value ready. Async: continuation runs when value ready, thread does other work meanwhile. Most modern languages use this (async/await is sugar). Composable: map, then, all, race over futures.'),
    ('What is the fork-join pattern?','Split work into N parallel tasks (fork), wait for all to complete (join), combine results. Maps to thread pools (Java ForkJoinPool, Rust rayon). Best for divide-and-conquer algorithms (parallel sort, parallel sum). Trade-off: task granularity — too fine = overhead, too coarse = poor load balance. Modern: work-stealing schedulers handle this automatically.'),
    ('What is backpressure?','Slow consumer pushes back on fast producer to prevent unbounded queueing. Without it: queue grows → memory OOM. Implementations: bounded buffer (producer blocks when full), reactive streams (consumer requests N items at a time), drop-oldest (lossy but bounded), drop-newest. Network protocols (TCP) have it built-in (window). Application code must implement it explicitly.'),
    ('What is the difference between cooperative and preemptive scheduling?','Cooperative: tasks voluntarily yield (async/await). Predictable, lower overhead, but one bad task can starve all others. Preemptive: scheduler forcibly interrupts. Fairer, robust to bad tasks, but more overhead + race-condition surface. Threads = preemptive. Coroutines = cooperative. JavaScript single thread = cooperative within its event loop.'),
    ('What is async I/O vs blocking I/O?','Blocking: thread waits for I/O to complete, doing nothing else (wasted on I/O wait). Async: kernel notifies when I/O done, thread does other work meanwhile. Async = many concurrent I/O ops per thread = scales much better for network servers (10k+ connections). Cost: code is more complex (callbacks, futures, async/await), debugging stack traces fragmented.'),
    ('What is the C10K problem?','Handling 10,000 concurrent network connections per server. Solution: async I/O (epoll/kqueue/IOCP) + small thread pool, not thread-per-connection. Modern frameworks (Node.js, Tornado, Tokio, Netty) solve this by default. Now we care about C10M (10 million) which needs specialized userspace TCP stacks or kernel bypass (DPDK).'),
    ('What is thread-local storage?','Per-thread variables — each thread sees its own copy. Avoids locks for thread-private state (per-request context, logger, RNG). Python: threading.local(). Rust: thread_local! macro. Java: ThreadLocal. Async equivalent: TaskLocal / contextvars (Python). Don\'t use thread-local in code that might switch threads (most async).'),
]
_BUGS=[
    ('What is the double-checked locking anti-pattern?','Trying to avoid lock cost by checking condition twice: `if (x == null) { lock { if (x == null) x = new X(); } }`. Broken in many languages because of memory reordering — partially constructed X might be visible. Fix: use volatile/atomic, or use a lazy initialization primitive (Java\'s `Class<>` init guarantees, std::sync::OnceLock in Rust, functools.cache in Python). Don\'t roll your own.'),
    ('What is a TOCTOU bug?','Time-of-check vs time-of-use: program checks a condition then acts assuming it still holds. Between check and act, another thread/process changes state. Classic: `if (file.exists()) file.delete()` — file may be deleted by another process in between, second call fails. Fix: use atomic operations (open with O_EXCL, FileChannel.lock), or check by attempting the action and handling failure.'),
    ('Why is shared mutable state hard to get right?','Every read/write must be coordinated with every other to avoid races. As state spreads, coordination cost explodes (N² interactions). Locks introduce deadlocks. Reasoning becomes non-local: a bug in one place can manifest in another seemingly-unrelated function. Solutions: minimize shared state, prefer immutability, use message passing, isolate mutable state behind narrow APIs.'),
]
LESSONS=_BASICS+_PATTERNS+_BUGS
