"""C++ and Java deep dives — modern features, common patterns, gotchas."""
_CPP=[
    ('What is RAII in C++?','Resource Acquisition Is Initialization. Resources (memory, file handles, locks) tied to object lifetime. Acquired in constructor, released in destructor. Stack unwinding on exception calls destructors automatically. Foundation of C++ memory safety. Examples: std::unique_ptr, std::lock_guard, std::ifstream.'),
    ('What is std::unique_ptr?','Smart pointer for sole ownership. Cannot be copied (only moved). Automatically deletes on destruction or reassignment. Replaces raw new/delete in 95% of cases. Use std::make_unique<T>(args) for construction. Pass by reference for borrow, by value (move) for transfer of ownership.'),
    ('What is std::shared_ptr?','Smart pointer with reference counting. Multiple shared_ptrs can own same object; deleted when last one destroyed. Cost: atomic refcount on each copy. Use when ownership is genuinely shared. Avoid cycles (use weak_ptr to break). Less common than unique_ptr in modern code.'),
    ('What is the difference between unique_ptr and shared_ptr?','unique_ptr: single owner, move-only, zero overhead vs raw pointer. Default choice. shared_ptr: multiple owners via reference counting, copy OK, small overhead. Use only when ownership is truly shared (rare). Both auto-delete on destruction.'),
    ('What is move semantics in C++?','C++11 feature: transfer ownership without copying. Source becomes "valid but unspecified." Triggered by: rvalue references (T&&), std::move, return-by-value. Massive perf win for objects with heap data (string, vector). Implement: move constructor + move assignment that steal resources from source.'),
    ('What is std::move?','Casts an lvalue to rvalue reference. Signals: "you may move from this." Doesn\'t actually move — enables moving. After std::move(x), x is in valid-but-unspecified state — don\'t use except to assign new value or destroy. Use to enable move from named variables.'),
    ('What is constexpr?','Compile-time computation. Functions + variables marked constexpr evaluated at compile time when possible. Use for: compile-time constants, template metaprogramming, performance (move work from runtime). C++20 expanded greatly (consteval, constinit). Modern C++ uses constexpr extensively.'),
    ('What is a lambda in C++?','Anonymous inline function. Syntax: `[capture](params) -> ret { body }`. Captures: [] (none), [=] (copy), [&] (ref), [x] (just x by copy), [&x] (just x by ref). Generates a struct with operator(). Use for: STL callbacks, async tasks, short logic local to one place.'),
    ('What is a template in C++?','Generic programming. Parameterize types or values: `template <typename T> void f(T x)`. Compiler generates a specialized version per concrete type used. Powerful but complex (compile errors verbose). Modern: concepts (C++20) constrain templates clearly.'),
    ('What is STL?','Standard Template Library. Containers (vector, map, set, unordered_map, etc.), algorithms (sort, find, transform), iterators connecting them. Designed for performance via generics. Modern: std::ranges (C++20) provides cleaner pipeline syntax.'),
    ('What is the difference between stack and heap allocation in C++?','Stack: automatic variables (function locals), fast (just adjust SP), released on scope exit, limited size. Heap: new/malloc, explicit allocate + delete/free, slower, can be much larger. Modern C++: prefer stack + RAII (unique_ptr) over raw heap allocation.'),
    ('What is undefined behavior in C++?','Behavior the standard doesn\'t specify — compiler may do anything. Examples: out-of-bounds access, use-after-free, signed integer overflow, race conditions. Compiler may optimize ASSUMING you never trigger UB → mysterious bugs. Tools: ASan, UBSan, MSan detect at runtime.'),
    ('What is the difference between struct and class in C++?','Identical EXCEPT default access: struct = public, class = private. Convention: struct for plain data (no invariants), class for things with behavior + encapsulation. Both can have methods, inheritance, constructors. Pick by intent.'),
]
_JAVA=[
    ('What is the JVM?','Java Virtual Machine. Runs Java bytecode (.class files) on any platform with a JVM. Provides: garbage collection, JIT compilation (hot code → native), security manager, threading. Languages targeting JVM: Java, Kotlin, Scala, Clojure, Groovy, Jython. Modern: GraalVM compiles JVM apps to native binaries.'),
    ('What is the difference between == and .equals() in Java?','== compares REFERENCES (same object in memory). .equals() compares VALUES (override per class to define equality). Strings: always use .equals() — string pooling sometimes makes == seem to work but breaks unexpectedly. Override .equals AND .hashCode together (contract).'),
    ('What is a Java collection?','Standard library data structures. List (ArrayList, LinkedList), Set (HashSet, TreeSet, LinkedHashSet), Map (HashMap, TreeMap, LinkedHashMap, ConcurrentHashMap), Queue/Deque (ArrayDeque, PriorityQueue). Pick based on access pattern + ordering needs + concurrency.'),
    ('What is ArrayList vs LinkedList in Java?','ArrayList: dynamic array, fast random access O(1), slow mid-insert O(n). LinkedList: doubly-linked, O(1) insert/delete at known node, O(n) random access. Default to ArrayList — better cache locality wins for almost all real workloads.'),
    ('What is HashMap vs ConcurrentHashMap?','HashMap: not thread-safe (concurrent modification → undefined behavior, potential infinite loop in older versions). ConcurrentHashMap: thread-safe via lock striping. Modern Java: ConcurrentHashMap for concurrent code; Collections.synchronizedMap is older + slower alternative.'),
    ('What is Java garbage collection?','JVM automatically reclaims unused heap memory. Generational: young gen (most objects die young, fast minor GC) + old gen (long-lived, slow full GC). Algorithms: G1 (default modern), ZGC (low-pause, large heap), Shenandoah, Parallel. Tuning rarely needed for app code; let GC do its job.'),
    ('What is a Java Stream?','Pipeline of operations on a collection. Lazy, functional-style: `list.stream().filter(p).map(f).reduce(...)`. Pros: declarative, parallelizable (.parallelStream()). Cons: slower than plain loops for small data, harder to debug. Use for clarity in complex transformations.'),
    ('What is Optional in Java?','Wraps possibly-null value. Forces handling absence at the type level. Methods: .isPresent(), .ifPresent(fn), .map(fn), .orElse(default). Modern Java return type for "may be absent" results. Don\'t use as parameter type (just pass null or overload). Java 8+.'),
    ('What is the difference between checked and unchecked exceptions?','Checked: extends Exception (not RuntimeException). Compiler forces handling via try/catch or throws declaration. Examples: IOException. Unchecked: extends RuntimeException. No compiler enforcement. Examples: NullPointerException, IllegalArgumentException. Modern style: prefer unchecked for most cases — checked exceptions don\'t scale to deep code.'),
    ('What is Java generics?','Parameterized types. `List<String>` is type-safe — can\'t add an Integer. Type erasure at runtime: List<String> and List<Integer> are same class at runtime. Wildcards: <? extends T> (covariant), <? super T> (contravariant), <?> (any). PECS: Producer Extends, Consumer Super.'),
    ('What is Spring framework?','Most popular Java application framework. Dependency injection (Spring Core), web (Spring MVC, Spring WebFlux), data (Spring Data JPA), security (Spring Security), boot (Spring Boot — opinionated quickstart). Powerful but heavyweight. Dominant in enterprise Java. Alternatives: Micronaut, Quarkus (lighter, faster startup).'),
    ('What is Spring Boot?','Opinionated Spring distribution. Auto-configuration based on classpath, embedded server (Tomcat/Netty), starter dependencies, production-ready features (Actuator endpoints). Run with `java -jar`. Standard for new Java services. Curve: very fast start, deep complexity if you fight defaults.'),
    ('What is Kotlin?','Modern JVM language by JetBrains. 100% Java interop. Pros over Java: null safety in type system (Type? for nullable), data classes (auto equals/hashCode/toString), extension functions, coroutines for async, concise. Now Android\'s preferred language. Increasingly used for server.'),
    ('What is the difference between Java and Kotlin?','Same JVM, full interop. Kotlin: null safety enforced by types, less boilerplate (data class, smart casts, extension functions), coroutines built-in for async, optional semicolons. Java catching up (records, sealed classes, pattern matching) but still more verbose. New Android: Kotlin default. New backend: either, depending on team.'),
]
_KOTLIN=[
    ('What is null safety in Kotlin?','Types distinguish nullable (`String?`) from non-nullable (`String`). Compiler enforces null checks before access. Operators: `?.` (safe call, returns null if receiver null), `?:` (Elvis, default if null), `!!` (assert non-null, throws if wrong — avoid). Eliminates ~99% of NullPointerExceptions.'),
    ('What is a data class in Kotlin?','Auto-generates equals(), hashCode(), toString(), copy() based on primary constructor properties. `data class User(val name: String, val age: Int)`. Use for: value objects, DTOs, immutable records. Replaces ~50 lines of Java boilerplate. Component functions enable destructuring.'),
    ('What is a coroutine in Kotlin?','Lightweight concurrency primitive. `suspend fun` declares a function that can pause. launch{} fires-and-forgets, async{} returns Deferred for await. Structured concurrency via CoroutineScope — children cancel with parent. viewModelScope (Android) auto-cancels when ViewModel cleared. Replaces RxJava/callbacks for most async.'),
    ('What is an extension function in Kotlin?','Add methods to existing classes without modifying them. `fun String.toSlug() = this.lowercase().replace(" ", "-")`. Statically dispatched (no override at runtime). Use for: adding utility methods to library types, DSL building. Don\'t abuse — discoverability suffers if extensions scattered.'),
]
LESSONS=_CPP+_JAVA+_KOTLIN
