"""Data engineering corpus — ETL, streaming, warehousing, data modeling."""
_ETL=[
    ('What is ETL vs ELT?','ETL: Extract, Transform, Load — transform data BEFORE loading into warehouse. Used when warehouse compute is expensive or limited (old Teradata era). ELT: Extract, Load, Transform — load raw into warehouse first, transform inside (modern dbt + Snowflake/BigQuery/Redshift). ELT wins now because cloud warehouse compute is cheap, schema can evolve, raw data preserved for reprocessing.'),
    ('What is dbt and what role does it play?','Data build tool. SQL-based transformations modeled as a DAG of dependent models. Runs inside your warehouse (BigQuery, Snowflake, etc). Version controlled, tested (built-in assertions), documented (auto-generated). The modern standard for analytics engineering. Replaces hand-coded transformation scripts + ad-hoc SQL.'),
    ('What is data warehouse vs data lake vs lakehouse?','Warehouse: structured, schema-on-write, optimized for BI queries (Snowflake, BigQuery, Redshift). Lake: any data, schema-on-read, raw files in object storage (S3, ADLS, GCS) — cheap, flexible, harder to query. Lakehouse: combines — open table formats (Iceberg, Delta, Hudi) give warehouse-like queries on lake storage. Modern stack tilting toward lakehouse.'),
    ('What is partitioning in data warehouses?','Splitting a table by a column (date, region, customer_id) so queries that filter on that column scan only relevant partitions, not the whole table. Massive speedup + cost reduction. Choose partition key based on query patterns + cardinality (date is the classic). Too many partitions (high cardinality keys) hurts metadata performance — find balance.'),
    ('What is a slowly changing dimension (SCD)?','Pattern for tracking how dimension data changes over time. Type 1: overwrite (no history). Type 2: add new row with effective date ranges (most common — "as of X, this customer was at this address"). Type 3: add columns for current + previous. Type 6: combo. Use Type 2 unless you have a specific reason; analytics needs historical context.'),
    ('What is a star schema vs snowflake schema?','Star: central fact table + denormalized dimension tables (each dim is one table). Simpler queries, denormalized = some duplication but faster joins. Snowflake: dimensions further normalized into sub-dimensions (countries → cities → users). Less duplication, more joins, slower. Most warehouses use star — storage is cheap, query speed wins.'),
    ('What is a fact table vs dimension table?','Fact: measurements/events (orders, page views, sensor readings) — many rows, narrow columns, NUMERIC measures + FK to dimensions. Dimension: context/who-what-where (customers, products, dates) — fewer rows, wider columns, descriptive attributes. Joins: fact LEFT JOIN dims on FK. Most queries: aggregate facts, GROUP BY dimension attributes.'),
]
_STREAMING=[
    ('What is Apache Kafka?','Distributed streaming platform. Producers publish messages to topics; consumers subscribe. Messages persisted on disk (configurable retention), replicated across brokers. Partitioned topics scale horizontally. Used for: event streaming, log aggregation, stream processing pipelines, decoupling services. Alternatives: Pulsar, Redpanda (Kafka-API-compatible, no ZooKeeper), AWS Kinesis.'),
    ('What is a Kafka consumer group?','Set of consumers cooperatively reading a topic — each partition assigned to ONE consumer in the group. Add consumers → automatic rebalancing → parallelism up to # partitions. Different groups: each receives all messages (fan-out). One group + N consumers: load-balance. Pick partitions = max(consumer count) you might want.'),
    ('What is at-most-once vs at-least-once vs exactly-once?','At-most-once: messages might be lost (ack before processing). At-least-once: messages might be duplicated (process before ack — if crash before ack, redelivered). Exactly-once: idempotent OR transactional. Kafka supports exactly-once for Kafka→Kafka via transactions. For external sinks, design for at-least-once + idempotent writes (dedup by message ID).'),
    ('What is the difference between batch and stream processing?','Batch: process a large chunk of data periodically (nightly, hourly). Higher latency, simpler, easier to reason about. Tools: Spark, Hadoop. Streaming: process events as they arrive, low latency (seconds to ms). Tools: Flink, Kafka Streams, Spark Streaming. Modern shift: stream-first ("Kappa" architecture) — batch is just a subset of stream.'),
    ('What is a watermark in stream processing?','Best estimate of "we\'ve seen all events up to time T" — accounts for out-of-order events. Triggers window closures + late-data handling. Watermark = event time of newest event minus an allowed lateness. Once watermark passes a window\'s end, fire the window\'s computation. Late events arriving after: drop or retroactive update (depends on framework).'),
    ('What is a windowed aggregation?','Group events by time intervals + aggregate. Tumbling: fixed non-overlapping (1-min windows). Sliding: fixed-size, slide every N (60s window, slide 10s = each event in 6 windows). Session: gap-based (close window after N idle seconds). Choose based on metric semantics: tumbling for "events per minute," sliding for "rolling average," session for "user session length."'),
]
_PIPELINE=[
    ('What is data lineage?','Track where data came from, what transformed it, where it goes. Critical for: debugging ("why is this number wrong?"), compliance (where did PII flow?), impact analysis ("what breaks if I change this source?"). Auto-extracted by tools (dbt, OpenLineage) from SQL/transformation code. Manual lineage docs always go stale; prefer automated.'),
    ('What is idempotency in data pipelines and why critical?','Pipeline can re-run on the same input and produce the same output (no duplicates, no missed). Pipelines fail and retry constantly — idempotent design is the only way to stay sane. Achieve via: UPSERT (insert-or-update on key), full-replace (delete + insert for partition), tombstone tracking. Anti-pattern: append without dedup.'),
    ('What is a slowly evolving schema and how to handle?','Source schemas change (new columns, renames, type widening). Strategies: (1) explicit migrations (rename columns in dbt) — clean but slow. (2) schema-on-read (Parquet + Iceberg evolution) — flexible. (3) JSON columns for unstable parts. Always: version your schemas, test transformations with both old + new data, deploy parsers before producers.'),
    ('What is data quality and how to enforce?','Properties: completeness (no nulls where expected), uniqueness (no dup IDs), validity (types, ranges, formats), consistency (sums match), timeliness (fresh enough). Tools: dbt tests, Great Expectations, Soda. Run as part of pipeline; FAIL pipeline (or quarantine) on critical violations. Don\'t silently let bad data flow downstream.'),
    ('What is backfilling and what makes it hard?','Re-run a pipeline for past dates after fix/add. Hard because: (1) pipeline must be idempotent. (2) source data may have changed since (snapshots help). (3) downstream consumers may have already used the old output. (4) compute/storage cost of reprocessing months of data. Design from the start: every step parameterized by date, dependencies tracked, partition-overwrite-safe.'),
]
LESSONS=_ETL+_STREAMING+_PIPELINE
