"""Advanced debugging strategies + war stories + production troubleshooting patterns."""
_STRATEGIES=[
    ('How do I debug code I did not write?','(1) Read the README + top-level docs. (2) Skim the entry point + main loop. (3) Run a basic test/example to verify it works. (4) Make ONE small change and trace its effect through the code. (5) Add print/log statements at key boundaries to map data flow. (6) Use a debugger to step through interesting paths. (7) Search for unfamiliar terms in commit history + issues. Don\'t try to understand it all at once.'),
    ('What is rubber duck debugging and why does it work?','Explain your problem in detail to an inanimate object (or a colleague). The act of forcing articulation reveals implicit assumptions and gaps in understanding. Most bugs are in your mental model, not the code — verbalizing exposes the mental model. Works alone with a notebook too. The tradition: explain to a literal rubber duck on your desk.'),
    ('What is the scientific method applied to debugging?','(1) OBSERVATION — what behavior is wrong? Be specific. (2) HYPOTHESIS — propose a CAUSE that explains it. (3) PREDICTION — if this cause is correct, what else should be true? (4) TEST — set up the experiment that would distinguish hypotheses. (5) CONCLUSION — confirm or revise hypothesis. Iterate. Avoid: jumping to "fix" without isolating cause; changing multiple things at once.'),
    ('How do I find the root cause vs treating symptoms?','Ask "why?" five times (Toyota 5 Whys). "The deploy failed because tests timed out. Why? Because DB queries were slow. Why? Because index was missing. Why? Because the migration was reverted. Why? Because the new schema broke production. Why? Because there was no staging mirror." Now you have the root cause, not just the symptom. Fix at the deepest level you can afford to.'),
    ('When should I stop debugging and ask for help?','Two hours of being truly stuck (no new info from each attempt) is a good rule. Before asking: write down what you\'ve tried + what didn\'t work + what evidence you have. Often the act of writing that summary solves it. If not, the summary makes the question easy for someone else to answer.'),
]
_PROD=[
    ('How do I investigate a production outage?','(1) Confirm scope — what is broken, for whom? (2) Stop the bleeding — rollback, failover, drain traffic. Restore service first, root-cause later. (3) Establish a timeline — what changed recently (deploys, config, traffic)? (4) Gather data — logs, metrics, traces from incident time. (5) Hypothesize + test against data. (6) Fix root cause. (7) Postmortem within a week — blameless, focus on systemic fixes.'),
    ('What is a blameless postmortem?','Document an incident focused on systemic causes + fixes, NOT individual blame. Premise: any engineer would have made the same mistake given the same context. Include: timeline, contributing factors, what worked well, action items (with owners + dates). Goal: lessons learned, NOT punishment. Published widely so others benefit. Cultural foundation of high-functioning SRE teams.'),
    ('What is the difference between a bug and an incident?','Bug: a defect in code/config/system that causes wrong behavior. Incident: an event that REQUIRES RESPONSE — service degradation, outage, data loss, security event. Bugs often cause incidents but not always (some bugs are minor, some incidents have no obvious bug — capacity exhaustion, dependency failure). Process: triage bugs via backlog; triage incidents via on-call response.'),
    ('What is observability vs monitoring?','Monitoring: predefined dashboards + alerts on known failure modes (you knew to ask). Observability: ability to investigate NEW questions about system behavior without adding new instrumentation (you ask questions after the fact). The three pillars (logs, metrics, traces) support both; modern stacks (OpenTelemetry) emphasize observability.'),
    ('What is a runbook and why does it matter?','Documented procedure for handling a recurring operational task: deploy, rollback, restart service, rotate credentials, respond to specific alert. During an incident at 3am with adrenaline + sleep deprivation, you do NOT want to invent procedure. Runbook lets anyone (including new hires) handle it safely. Test runbooks — review during postmortems if they failed to help.'),
]
_BUG_PATTERNS=[
    ('What is an off-by-one error?','Loop bound or array index off by one — too many or too few iterations. Classic: `for i in range(len(arr))` correct, but `for i in range(1, len(arr))` accidentally skips first item. Or `arr[len(arr)]` (out of bounds). Most languages use 0-based indexing — easier when you remember "size N means valid indices 0..N-1, slices end exclusive."'),
    ('What is a fencepost error?','You need N fence posts for N-1 fence sections (and vice versa). Software examples: separators between items (N items → N-1 separators), array slicing (end - start = length, even though end index is exclusive). When counting "items between two boundaries," draw a picture or test with N=1, N=2 to verify formula.'),
    ('What is a Heisenbug?','A bug that disappears or changes behavior when you try to observe it (named after Heisenberg\'s uncertainty principle). Often timing/race conditions where adding print/breakpoint slows code enough to mask the race. Mitigations: logging instead of breakpoint (less perturbation), thread sanitizers, randomized stress tests, capture/replay frameworks.'),
    ('What is a Schrödinbug?','Bug that an engineer notices in code (by reading or thinking), and only THEN does the bug start manifesting in production — even though the buggy code has been running forever. Variant of cognitive bias: once you know the bug exists, you see the symptoms. Real explanation: bug always existed; conditions just hadn\'t coincided.'),
    ('What is the bisect technique?','Divide and conquer for finding root cause. Bug appeared between A and B (commits, configs, time ranges). Pick midpoint M, test. If broken in M, bug is in A..M. Else B..M. Repeat. O(log N) tests. `git bisect` automates for commits. The most efficient technique for "this worked last week, broke today" debugging.'),
    ('How do I debug "it works on my machine"?','Differences between dev + prod environments: (1) OS / kernel version. (2) Library versions (lockfile mismatch). (3) Env vars / config. (4) Data (dev has small clean data, prod has weird real data). (5) Scale (dev: 1 request at a time, prod: concurrent). (6) Network (latency, partitions). Make dev mirror prod: use Docker / same versions, run with prod-like data, simulate load. Or run in prod with feature flag for the affected user only.'),
]
_TROUBLESHOOTING=[
    ('My API is suddenly slow — how to diagnose?','Compare slow vs fast requests. (1) Add tracing — which span got slower? (2) Check downstream deps (DB latency, third-party APIs, cache hit rate). (3) Check resource saturation (CPU, memory, GC pauses, file handles). (4) Check recent changes (deploys, config, traffic shape). (5) Network — packet loss, retries. (6) Geographic patterns — only one region affected? Profile in production if possible.'),
    ('My service is crashing — where to look?','(1) Logs — last few lines before crash often have the error. (2) Core dump / heap dump if available — actual memory state. (3) Process exit code + signal (OOM kill = 137, segfault = 139). (4) System logs (dmesg, journalctl, /var/log/messages). (5) Did anything recently change (deploy, traffic, dependency, OS update)? (6) Reproduce locally if possible. (7) Add more logging + redeploy if not reproducible. Crash logs lie sometimes — verify with reproducibility.'),
    ('My deploy broke production — what now?','ROLLBACK FIRST. Don\'t debug in prod. Restore the previous known-good version (atomic rollback if you have it). Once service restored, investigate the broken deploy in staging or a local replica. Then fix + re-test + redeploy. Postmortem: how did the broken code pass tests + canary? Improve those gates.'),
    ('Database queries got slow — diagnose?','EXPLAIN the slow query. (1) Sequential scan on big table? Add index. (2) Wrong plan? Stats stale? Run ANALYZE. (3) Index not used? Function on column (UPPER(col) = ...), implicit cast, OR conditions. (4) Big sort/group? Increase work_mem. (5) Lock contention? Check pg_stat_activity. (6) Concurrent load? Connection pool exhausted? Scale read replicas?'),
    ('Memory keeps growing — diagnose?','(1) Confirm leak vs cache vs normal growth — does it plateau? (2) Reproduce minimally. (3) Heap snapshot tools (tracemalloc, heaptrack, pprof). (4) Look for unbounded growth: caches without max size, queues that aren\'t drained, event handlers never unsubscribed, circular references. (5) Long-lived objects retaining references. (6) Periodic dumps; diff to see what\'s growing.'),
]
LESSONS=_STRATEGIES+_PROD+_BUG_PATTERNS+_TROUBLESHOOTING
