"""Linux/shell + Docker + Kubernetes + CI/CD + Git advanced + observability corpus."""
_SHELL=[
    ('What does grep do and useful flags?','Searches for patterns in text. `grep "pattern" file` — basic. -i (case-insensitive), -r (recursive into dirs), -v (invert: show non-matching), -n (show line numbers), -A 3 / -B 3 / -C 3 (lines of context), -l (only file names with match), -E (extended regex). For huge codebases use ripgrep (rg) — same syntax, 10-100x faster, respects .gitignore.'),
    ('How do I find files modified in the last N days?','`find . -mtime -7` — modified in last 7 days. -mtime +30 = older than 30 days. Combine with -type f (files only), -name "*.py" (pattern), -size +10M (size). Example: `find . -type f -name "*.log" -mtime +30 -delete` (delete logs older than 30 days). Always test with -print before -delete.'),
    ('What is the difference between sh, bash, zsh?','sh = POSIX shell, minimal, portable. bash = extended sh with arrays, [[ ]], $(...), readline. zsh = bash + better completion, themes (oh-my-zsh), globbing, named directories. Default on macOS since Catalina = zsh. Default on most Linux = bash. Scripts: write for sh if portability matters; bash if you need its features (and #!/usr/bin/env bash shebang).'),
    ('What does chmod 755 mean?','Permissions in octal. Three digits: owner, group, other. Each digit: read=4 + write=2 + execute=1. 755 = owner rwx, group rx, other rx. 644 = owner rw, group r, other r (common for files). 600 = owner rw, nobody else (private keys, .env). 700 for directories you want only yourself in. Use chmod +x file to just add execute without changing other bits.'),
    ('What is a pipe in shell and why useful?','`cmd1 | cmd2` runs cmd1, sends its stdout to cmd2\'s stdin. Lets you compose tools: `ps aux | grep python | grep -v grep | awk \'{print $2}\' | xargs kill`. Each tool stays simple, doing one thing. Pipes are why the Unix philosophy works. Anti-pattern: `cat file | grep x` — grep can read files directly: `grep x file`. (Useless use of cat.)'),
    ('What does xargs do?','Take input lines from stdin and use them as arguments to a command. Example: `find . -name "*.log" | xargs rm` (delete all log files). -I {} substitutes the placeholder: `cat urls.txt | xargs -I {} curl {}`. -P N runs N in parallel. Critical: -0 with `find -print0` to handle filenames with spaces/newlines safely. Without -0, filenames with spaces break.'),
    ('What is the difference between > and >>?','> overwrites the file (truncate). >> appends. Both redirect stdout. To redirect stderr: 2> or 2>>. To combine stderr into stdout: 2>&1 (must come AFTER the stdout redirect: `cmd > out 2>&1`, NOT `cmd 2>&1 > out`). To discard: > /dev/null. Common: `cmd > out.log 2>&1 &` (background, all output to file).'),
    ('How do I run a command in the background?','Append `&` to run in background: `long_task &`. Returns prompt immediately. Use `jobs` to list, `fg %1` to bring job 1 to foreground, `bg %1` to resume in background. For commands that should survive logout: nohup cmd & or use `disown` after backgrounding, or run inside tmux/screen. For production daemons use systemd or a process manager.'),
    ('What is sed and a useful one-liner?','Stream editor — reads stdin/files line by line, applies edits, outputs. Most common: substitute. `sed "s/old/new/g" file` (global per line). -i edits in place: `sed -i "s/old/new/g" *.py` (be careful — backup with -i.bak first). Delete lines matching pattern: `sed "/pattern/d"`. Print specific lines: `sed -n "5,10p"`. For complex text manipulation, reach for awk or a Python script.'),
    ('What does awk do?','Field-oriented text processor. Splits each line into fields ($1, $2, ..., $NF=last). Most useful for whitespace-separated data. Print column 2: `awk \'{print $2}\'`. Sum column 3: `awk \'{sum+=$3} END {print sum}\'`. Filter then print: `awk \'$3 > 100 {print $1, $3}\'`. -F sets delimiter: `awk -F: \'{print $1}\' /etc/passwd`. Powerful for log analysis without writing a real script.'),
]
_DOCKER=[
    ('What is a Docker image vs container?','Image = read-only template (your app + deps + OS bits). Container = running instance of an image. Like class vs object. Build images with Dockerfile + `docker build`. Run containers with `docker run`. Containers are ephemeral — data inside dies when container does, unless mounted via volumes.'),
    ('What is a Dockerfile and key best practices?','Recipe to build an image. Layered: each instruction creates a layer, cached if unchanged. Best practices: (1) put rarely-changing layers FIRST (FROM, system deps) so they cache. (2) copy requirements/lockfile + install BEFORE copying source — code changes don\'t re-install deps. (3) use small base images (alpine, distroless, slim) — fewer bytes + fewer CVEs. (4) one process per container — use docker-compose for multi-process. (5) USER non-root for security. (6) .dockerignore to skip node_modules, .git, etc.'),
    ('What is the difference between CMD and ENTRYPOINT?','Both define what runs when the container starts. ENTRYPOINT is the COMMAND itself, CMD is its DEFAULT ARGUMENTS. `docker run img foo` overrides CMD but ENTRYPOINT still runs. Pattern: ENTRYPOINT ["python"], CMD ["app.py"] → runs `python app.py` by default, `docker run img test.py` runs `python test.py`. Use ENTRYPOINT for binaries/scripts; CMD for default config.'),
    ('What is a Docker volume vs bind mount?','Volume: Docker-managed (in /var/lib/docker/volumes), survives container deletion, portable. Bind mount: mounts a host path INTO the container — useful for dev (live code reload), config files, but tied to specific host path. Use volumes for DB data (postgres). Use bind mounts for dev hot-reload. Anonymous volumes are auto-created — usually wrong; name them.'),
    ('What is docker-compose for?','Define multi-container apps in a YAML file (services, networks, volumes). One `docker compose up` brings the whole stack up. Perfect for: dev environment (app + DB + redis + nginx), small prod deployments, testing distributed scenarios. Not a Kubernetes replacement at scale. Common pattern: dev compose file + override file for prod-like testing.'),
    ('What is multi-stage Docker build?','Multiple FROM lines in one Dockerfile, each a stage. Build heavy stuff in builder stage (compile, install dev deps), then COPY just the artifacts to a minimal final stage. Result: small final image without build tools. Example: build Go binary in golang image (~1GB), COPY binary into alpine (~5MB) for final. Standard practice for compiled languages.'),
]
_K8S=[
    ('What is Kubernetes in one paragraph?','Container orchestrator. You declare desired state ("run 3 replicas of this image with this config"); Kubernetes makes it so. Schedules containers across a fleet of nodes, restarts failed ones, load-balances traffic, auto-scales based on metrics, rolls out new versions safely. Steep learning curve. Worth it when: many services, multi-team, need self-healing + zero-downtime deploys. Overkill for a single app on one server.'),
    ('What is a Pod, Deployment, Service?','Pod: smallest unit — one or more co-located containers sharing network + storage. Usually one container per pod. Deployment: declarative spec for N replicas of a Pod, handles rolling updates + rollback. Service: stable network endpoint that load-balances across Pod replicas (Pods come and go; their IPs change; Service stays). Ingress (separate) handles HTTP routing from outside cluster.'),
    ('What is the difference between StatefulSet and Deployment?','Deployment: stateless replicas, interchangeable, scale up/down freely, pods named randomly. StatefulSet: ordered pods (myapp-0, myapp-1...), stable network identity (DNS name), stable persistent storage per pod. Use for databases, queues, anything that needs identity. Slower to scale. Modern alternative for many cases: operator pattern + Deployment (e.g., Postgres operator).'),
    ('What is a Helm chart?','Templated Kubernetes manifests with values files for environment-specific config. helm install/upgrade/rollback manages a release. Pros: reusable packages (helm.sh hub), version control of deployments. Cons: templating in YAML strings gets ugly fast; consider Kustomize or jsonnet for some cases. For many teams: Helm + a values file per env is the standard.'),
]
_CI_CD=[
    ('What is CI vs CD?','CI = Continuous Integration: every push automatically builds + tests, fast feedback. CD = Continuous Delivery (deploys ready for manual release) or Continuous Deployment (every passing commit goes to prod). CD requires high test coverage + monitoring + easy rollback. Start with CI; add CD once you trust your tests. GitHub Actions, GitLab CI, CircleCI, Jenkins are common runners.'),
    ('What should a good CI pipeline look like?','Fast first: lint + type-check (seconds) before slow tests. Parallel where possible (e.g., test shards). Fail fast — don\'t wait through a 20-min build if lint fails. Cache deps between runs. Pin tool versions (not "latest") for reproducibility. Run identical commands as developers do locally — "works on my machine" should never differ from "works in CI."'),
    ('How do I handle secrets in CI?','NEVER in plain env vars in code or YAML. Use the platform\'s secret store (GitHub Secrets, GitLab Variables, Vault). Inject as env vars at runtime. Rotate periodically. Scope to specific repos/environments. For prod deploys, use OIDC federation (GitHub → AWS/GCP) to avoid long-lived keys entirely — short-lived tokens issued per job.'),
    ('What is blue-green vs canary deployment?','Blue-green: stand up the new version (green) alongside the old (blue), switch traffic atomically once green is healthy. Rollback = switch back. Needs 2x capacity briefly. Canary: send small % of traffic (5%, then 25%, then 100%) to new version, watch metrics, abort if errors spike. Slower but lower risk. Modern setup: feature flags decouple deploy from release — ship code disabled, enable per user/percent.'),
]
_GIT_ADV=[
    ('What is git stash and when to use it?','Saves uncommitted changes to a stash stack, gives you a clean working dir. Use when you need to switch branches but aren\'t ready to commit. `git stash` saves, `git stash pop` restores, `git stash list` shows, `git stash drop` discards. Annotate with `git stash push -m "msg"`. Don\'t stash for hours — easier to commit WIP to a branch.'),
    ('What does git cherry-pick do?','Apply a specific commit from another branch to the current one. Useful for: backporting a hotfix to a release branch, copying a single useful commit from someone\'s long branch. `git cherry-pick <sha>`. Multiple: list shas. -x adds source info to message. Conflicts handled like merge. Don\'t cherry-pick the same commit twice into the same branch — duplicate history.'),
    ('What is git bisect?','Binary search through commit history to find when a bug was introduced. `git bisect start`, mark current as bad: `git bisect bad`, mark a known-good commit: `git bisect good <sha>`. Git checks out a midpoint commit; you test and run `git bisect good` or `bad`. Repeats until it identifies the introducing commit. Best tool ever for "this worked last week, broke today." Automate the test: `git bisect run ./test.sh`.'),
    ('How do I clean up a messy local history before pushing?','`git rebase -i HEAD~N` opens interactive rebase. Pick commits to keep/squash/reword/drop. Combines fixup commits, fixes typos, splits commits. NEVER rebase commits already pushed to a shared branch — rewrites history others have. Safe rule: rebase WIP on your feature branch before opening PR.'),
    ('What is git reflog?','Local log of every HEAD movement — checkouts, commits, resets, rebases. Lets you recover "lost" commits after a bad rebase or reset. `git reflog` shows history; `git reset --hard HEAD@{2}` restores HEAD to where it was 2 moves ago. The safety net that makes `git reset --hard` survivable. Reflog entries expire (default 90 days).'),
]
_OBS=[
    ('What is logging vs metrics vs tracing (three pillars of observability)?','Logs: timestamped text events. Best for: debugging specific incidents. Verbose, hard to aggregate. Metrics: numeric measurements over time (request rate, error rate, latency). Best for: dashboards, alerts, capacity planning. Cheap to store. Tracing: tracks a single request through multiple services with timing. Best for: finding latency in distributed systems. All three together = observability.'),
    ('What is structured logging?','Logs as JSON or key-value pairs instead of plain text. Each event has named fields (user_id, request_id, latency_ms). Lets you grep/filter/aggregate efficiently: `jq \'select(.level=="error" and .latency_ms > 100)\'`. Modern aggregators (Loki, Datadog, Splunk) index structured fields. Always include: timestamp, level, service, request_id, error+stack on errors. Don\'t log secrets or PII.'),
    ('What is a SLO / SLI / SLA?','SLI: Service Level Indicator — a measurement (e.g., "% of requests under 200ms"). SLO: Service Level Objective — an internal target (e.g., "99.9% of requests under 200ms over 28 days"). SLA: contractual commitment to customers with penalties if missed. SLOs drive engineering priority — when error budget is consumed, freeze new features and fix reliability.'),
    ('What is alert fatigue and how to avoid?','Too many noisy/false alerts → people ignore real ones. Avoid: (1) alert only on user-visible impact (SLO burn rate), not on every metric. (2) tune thresholds based on real noise. (3) require alerts to be actionable — if it can\'t be fixed, it shouldn\'t page. (4) review alert volume weekly; tune or delete the noisy ones. (5) page only severities that justify waking someone; lower goes to ticket queue.'),
]
LESSONS=_SHELL+_DOCKER+_K8S+_CI_CD+_GIT_ADV+_OBS
