"""Distributed databases — Cassandra, CockroachDB, Spanner, DynamoDB, Redis Cluster, modern serverless DBs."""
_BASICS=[
    ('What is a distributed database?','Database spread across multiple machines, presenting a unified interface. Goals: horizontal scale (data + traffic beyond one machine), fault tolerance (survive node failures), geo-distribution (low latency near users). Trade-offs vs single-node: consistency choices (CAP), operational complexity, sometimes slower simple queries due to coordination.'),
    ('What is the difference between OLTP and OLAP?','OLTP (Online Transaction Processing): many small reads/writes, low latency, normalized schema, row-oriented storage. Examples: Postgres, MySQL, Spanner. OLAP (Online Analytical Processing): few large aggregations, columnar storage, denormalized, eventual consistency OK. Examples: Snowflake, BigQuery, Redshift, ClickHouse. Many systems specialize for one; lakehouse aims for both.'),
    ('What is a partition key in distributed DBs?','Column(s) used to decide which shard/node holds a row. Hash of key picks the partition. Choose by: query pattern (queries should hit one partition if possible), cardinality (avoid hot partitions), uniformity (avoid skew). Bad choice = hot spots + cross-partition queries. Spanner / DynamoDB call this partition or hash key.'),
    ('What is a clustering key (sort key)?','Within a partition, the order rows are stored. Enables fast range queries within that partition. Cassandra: PRIMARY KEY ((partition_key), clustering_key). DynamoDB: sort key. Pick to support your query: ORDER BY + range queries within partition use this.'),
    ('What is wide-column vs key-value vs document?','Key-value (Redis, DynamoDB simple): blob keyed by id. Wide-column (Cassandra, HBase): keyed rows with sparse columns, each row can have different cols. Document (MongoDB, Firestore): nested JSON-like. Different access patterns. Modern DBs often hybrid (DynamoDB supports document attrs; Postgres has JSONB).'),
]
_CASSANDRA=[
    ('What is Apache Cassandra and when use?','Wide-column distributed DB. Linearly scalable writes (no single primary). Eventual consistency tunable per query (ONE/QUORUM/ALL). Best for: massive write throughput, time-series, IoT sensor data, write-heavy workloads with predictable access patterns. Not for: ad-hoc queries (no JOIN), complex transactions, low data volumes (overhead).'),
    ('What is the Cassandra data model approach?','Design schema AROUND queries, not entities. Denormalize aggressively — same data copied into multiple tables, each optimized for a query. No JOINs. Read-write balance: many tables for many query patterns. Schema rigid (must declare columns), but rows can omit any.'),
    ('What is eventual consistency in Cassandra?','Writes propagate to replicas asynchronously by default. Reads may return stale data briefly. Tunable per query: write/read consistency levels (ONE = one replica, QUORUM = majority, ALL = all). Strong consistency by setting both to QUORUM, but slower. Most apps tune for "eventually consistent within X ms" rather than strong.'),
]
_NEWSQL=[
    ('What is Google Spanner?','Globally-distributed strongly-consistent SQL database. Uses TrueTime (atomic clocks + GPS) for externally consistent transactions across regions. SQL interface, ACID transactions, horizontal scale. Powers Gmail, AdWords. Open implementations: CockroachDB, YugabyteDB. Trade-off: writes have geo latency (consensus across regions).'),
    ('What is CockroachDB?','Distributed SQL DB inspired by Spanner. Strong consistency via Raft per range. Horizontal scale. PostgreSQL wire-compatible (most drivers work). Best for: apps that need Postgres semantics + scale + multi-region. Slower than vanilla Postgres for single-machine workloads. Open source + cloud-hosted versions.'),
    ('What is YugabyteDB?','Distributed SQL with two APIs: YSQL (Postgres-compatible) + YCQL (Cassandra-compatible). Strong consistency via Raft. Similar competitive niche to CockroachDB. Open source. Use when: need Postgres or Cassandra compat AND horizontal scale.'),
    ('What is the difference between Spanner-style DBs and Cassandra-style?','Spanner-style (CockroachDB, Yugabyte): strong consistency via consensus protocol (Raft/Paxos), SQL transactions, slower writes due to consensus. Cassandra-style: eventual consistency, leaderless, faster writes, no JOIN/transactions across nodes. Pick by: need for SQL/transactions vs raw write throughput.'),
]
_DYNAMO=[
    ('What is DynamoDB?','AWS managed key-value + document DB. Single-digit ms latency at any scale. No servers to manage. Pricing: on-demand or provisioned capacity. Best for: serverless apps, high-throughput key-value/document workloads, mobile/web backends. Designed around partition key — get the model right.'),
    ('How do I design a DynamoDB table?','Single-table design: model multiple entity types in ONE table using overloaded keys (PK + SK). Saves cost + improves perf vs many tables. Predefine access patterns FIRST, design key structure to satisfy them. Use GSIs (Global Secondary Index) for additional patterns. Watch hot partitions (uneven traffic distribution).'),
    ('What is the difference between DynamoDB and Cassandra?','Both wide-column, partition-key sharded. DynamoDB: AWS-managed, simpler to operate, more expensive per op, strong consistency available, transactional API. Cassandra: self-hosted (or via DataStax), open-source, complex ops, designed for super-high write throughput, eventual consistency primary. Use DynamoDB if AWS shop + don\'t want ops. Cassandra if needing extreme scale + control.'),
]
_REDIS=[
    ('What is Redis?','In-memory data structure store. Key-value but with rich types: strings, hashes, lists, sets, sorted sets, streams, geo, hyperloglog, bitmaps. Sub-ms latency. Persistence options (RDB snapshots, AOF log). Use for: cache, session store, leaderboards, rate limiting, pub-sub, queues (Streams), real-time analytics. Single-threaded (mostly) — simple model.'),
    ('What is Redis Cluster?','Sharded Redis. 16384 hash slots distributed across nodes. Client routes by hash(key) % 16384. Supports replication + failover. Trade-off: multi-key commands must touch keys in same hash slot (use {tag} in key to control). Modern alternatives: KeyDB (multi-threaded fork), Dragonfly (rewrite, much faster), Valkey (post-license-change Redis fork).'),
    ('What is the difference between Redis and Memcached?','Both in-memory caches. Memcached: simpler, just KV strings, multi-threaded, no persistence. Redis: rich data structures, single-threaded mostly, persistence, replication, pub-sub. Memcached for pure cache + multi-threaded perf. Redis for everything else. Most teams default to Redis now.'),
]
_MODERN_SERVERLESS=[
    ('What is FaunaDB / Convex / PlanetScale style serverless DBs?','New generation: pay-per-query/storage, scale to zero, edge-native. FaunaDB: ACID transactions globally, multi-model. Convex: TypeScript-first, real-time subscriptions, reactive queries. PlanetScale: MySQL-compatible with branching (git-like), separation of storage/compute. Use for: serverless apps, real-time UIs, modern startup stacks.'),
    ('What is Turso / D1 / SQLite-at-scale?','Distributed SQLite over libSQL fork. Per-region replicas, edge-deployed. Reads from local replica (low latency); writes go to primary. Trade-offs: write latency from edge, sync delay for reads after write. Best for: read-heavy apps, edge-first stacks, content sites.'),
    ('When should I NOT use a distributed DB?','When your data + traffic fit comfortably on ONE big Postgres machine — most apps do for far longer than people think. Modern Postgres handles TBs + tens of thousands of QPS easily. Distributed adds: ops complexity, harder transactions, slower simple queries, costs. Default to single Postgres + read replicas; distribute when you actually hit the wall.'),
]
LESSONS=_BASICS+_CASSANDRA+_NEWSQL+_DYNAMO+_REDIS+_MODERN_SERVERLESS
