"""Distributed systems deep dive — consensus, replication, sharding, observability."""
_CONSENSUS=[
    ('What is the consensus problem?','Multiple nodes agree on a single value despite failures (crashes, network partitions). Foundational for: leader election, replicated state machines, distributed locks. Impossible to solve perfectly under FLP impossibility theorem (asynchronous network + at least one failure). Practical solutions trade off availability or termination guarantees. Raft + Paxos are the workhorses.'),
    ('What is Raft consensus?','Designed for understandability. One LEADER per term handles all writes; FOLLOWERS replicate. Leader election via majority vote (random election timeouts prevent split votes). Log replication: leader appends, replicates to majority, then commits. Safe under partitions: minority side can\'t elect new leader (no majority). Implementations: etcd, Consul, TiKV, CockroachDB.'),
    ('What is the difference between Paxos and Raft?','Same fundamental guarantees (consensus on a value). Paxos: older, mathematically elegant, very hard to implement correctly — many implementations are subtly broken. Raft: designed for understandability, easier to implement correctly, slightly more restrictive (single leader). Modern systems use Raft. Multi-Paxos variants still used in old systems.'),
    ('What is the two-phase commit?','Coordinator asks all participants "ready to commit?" (phase 1, prepare). If ALL say yes, coordinator tells them "commit" (phase 2). If any say no, "abort." Problem: if coordinator crashes between phases, participants are stuck holding locks indefinitely. Worse than no transaction in some failure modes. Use only when participants are reliable + coordinator is highly available.'),
    ('What is the CAP theorem in 2025?','Distributed systems can\'t simultaneously guarantee Consistency + Availability + Partition tolerance. Networks DO partition in practice, so real systems choose: CP (consistent under partition, may refuse requests) or AP (always available, may serve stale data). Spectrum, not binary — many systems are "mostly CP with AP fallback." Modern: PACELC adds latency vs consistency tradeoff during normal operation.'),
]
_REPLICATION=[
    ('What is master-replica replication?','One node (master/primary) accepts writes, replicates to read-only replicas. Reads can hit any. Writes lag replicas slightly (replication lag). Pros: simple, scales reads. Cons: writes don\'t scale, master is SPOF (mitigate with auto-failover), reading right after writing may hit stale replica. Most relational DBs default mode.'),
    ('What is multi-master replication and its dangers?','Multiple nodes accept writes, replicate to each other. Pros: write scalability, no single SPOF. Cons: CONFLICTS when same row updated in two places — must resolve (last-write-wins loses data, app-level merge is complex). Common in: geo-distributed deployments, P2P systems. Modern alternative: single-writer + multi-region read replicas via spanner-like or leader rotation.'),
    ('What is sync vs async replication?','Sync: write blocks until replica acks. Guarantees no data loss on master failure. Slower (network round-trip per write). Async: write returns immediately, replica catches up later. Faster but data loss window if master crashes before replication. Mostly-async: write returns after WAL flushed locally, replication background. Tunable: Postgres synchronous_commit, MongoDB write concern.'),
    ('What is sharding (horizontal partitioning)?','Split data across N nodes, each holding a subset. Routing by hash(key)%N (simple but resharding moves all keys) or range partitioning (sortable but hot spots). Consistent hashing: minimizes data movement on add/remove of nodes. Cross-shard queries are slow/complex; design schema so most queries hit one shard. Pain points: distributed transactions, rebalancing.'),
    ('What is read repair vs anti-entropy?','Mechanisms to converge replicas. Read repair: on read, if replicas disagree, write back the latest value to stale ones. Cheap, happens on every read. Anti-entropy: background process compares replicas (Merkle trees) + syncs differences. Catches data that\'s rarely read. Used by Cassandra, DynamoDB. Together they keep eventually-consistent systems converging.'),
    ('What is a vector clock?','Tracks causal order of events in a distributed system. Each node has a counter; vector = map of node → counter. On send: increment own counter, send vector. On receive: max each entry component-wise, increment own. Use to detect: causally-related (A < B), concurrent (neither dominates). Used in: causal consistency, conflict detection in multi-master, distributed debugging.'),
]
_DISTRIBUTED_DATA=[
    ('What is the difference between strong and eventual consistency?','Strong: every read returns the most recent write (looks like single node). Slow + less available under partition. Eventual: reads may return stale data; all replicas converge eventually. Fast + highly available. Strong examples: single-leader RDBMS, etcd. Eventual: DNS, S3 (pre-2020), CRDTs. App must be designed for the chosen model.'),
    ('What is causal consistency?','Reads reflect causal order: if A causally precedes B (A happened-before B), any node that sees B also saw A. Weaker than strong, stronger than eventual. Achieved via vector clocks tracking dependencies. Used in: collaborative editing, social feeds where reply must appear after parent post.'),
    ('What is a CRDT?','Conflict-free Replicated Data Type. Designed so concurrent updates can be merged deterministically without coordination. Types: G-counter (grow-only), PN-counter (inc/dec), OR-Set (add/remove), LWW-Element-Set, CRDT-based JSON. Powers: multiplayer cursors (Figma), collaborative docs (Yjs, Automerge), distributed databases (Riak, Redis CRDB). Trades expressiveness for automatic merge.'),
    ('What is exactly-once delivery and is it possible?','True exactly-once delivery is impossible in a distributed system (Two Generals problem). Achievable: exactly-once SEMANTICS via idempotency. Producer assigns unique message ID; consumer dedupes. Kafka + transactional producers approximate it within Kafka. For external sinks: at-least-once + idempotent application logic. Design your operations to be idempotent.'),
    ('What is a leader election?','Distributed nodes agree on one node as "leader" responsible for coordination tasks. Methods: (1) ZooKeeper/etcd ephemeral nodes (lowest creates wins). (2) Raft consensus (leader emerges from majority vote). (3) Bully algorithm (highest ID wins). (4) Lease-based (renew or lose). Critical: handle leader failure detection (heartbeats with timeout) + split-brain prevention (majority required).'),
]
_OBSERVABILITY_DEEP=[
    ('What is a correlation ID (request ID)?','Unique identifier attached to a request as it flows through services. Lets you trace ALL logs/metrics/spans related to ONE user action across the stack. Generate at edge (UUID per request), propagate via header (X-Request-Id), include in every log line. Without it, distributed debugging is a nightmare.'),
    ('What is a span in distributed tracing?','One operation within a trace — function call, DB query, HTTP request. Has: start time, duration, parent span, attributes (key-value tags), events. Spans form a tree per trace. Tools: OpenTelemetry (instrumentation), Jaeger/Tempo/Datadog (storage + UI). Critical for: finding latency outliers, understanding service dependencies, debugging distributed errors.'),
    ('What is the difference between black-box and white-box monitoring?','Black-box: monitor from outside (synthetic checks, ping, end-to-end probes). Detects "is the service usable from the user perspective." White-box: instrument inside the service (metrics, logs, traces). Detects WHY it might fail. Use both. Black-box catches outages; white-box explains them. SRE classic: black-box for alerting, white-box for debugging.'),
    ('What is the difference between throughput and latency?','Throughput: requests/sec. Latency: time to handle one request. They\'re related but distinct. Optimizing one often hurts the other (batching → higher throughput, higher latency). Always measure latency at PERCENTILES — p50, p95, p99, p99.9 — averages hide tail behavior that affects users. p99 is where complaints come from.'),
    ('What is Little\'s Law and how is it useful?','L = λW. In steady state, items-in-system = arrival-rate × time-in-system. Example: if 100 req/s arrive and avg latency is 50ms, expected in-flight requests = 100 × 0.05 = 5. Useful for: capacity planning, identifying bottlenecks (concurrency limit / mean latency = max throughput), thread-pool sizing.'),
]
LESSONS=_CONSENSUS+_REPLICATION+_DISTRIBUTED_DATA+_OBSERVABILITY_DEEP
