"""Domain-specific corpus — finance, blockchain, healthcare, gaming, scientific computing."""
_FINANCE=[
    ('What is a stock exchange in plain terms?','Marketplace where shares of companies are bought and sold. Matches buyers and sellers via order book (bids + asks). Major: NYSE, NASDAQ, LSE. Electronic — most trading via APIs / algorithms now. Listings have rules (financials, governance). Price = current market consensus, updates millisecond by millisecond.'),
    ('What is the difference between a stock and a bond?','Stock (equity): ownership share in a company. Returns from dividends + appreciation. Higher risk + return. Bond (debt): loan to company/government. Pays fixed interest + principal at maturity. Lower risk + return. Portfolios mix both for risk balance.'),
    ('What is a derivative in finance?','Contract whose value derives from underlying asset (stock, commodity, currency, rate). Types: options (right to buy/sell), futures (obligation to transact at future date/price), swaps (exchange cash flows). Used for: hedging (reduce risk), speculation, arbitrage. Notoriously complex; misused → 2008 crisis.'),
    ('What is volatility in finance?','Measure of price variability over time. Higher vol = wilder swings + more risk + higher option premiums. Computed: standard deviation of returns. Annualized via sqrt(252) for daily returns. VIX = forward-looking implied vol of S&P 500 options — "fear gauge."'),
    ('What is high-frequency trading (HFT)?','Trading firms using ultra-low-latency systems (microseconds) to exploit tiny price differences across exchanges. Strategies: market making, arbitrage, statistical arb. Infrastructure: co-located servers, FPGA, custom hardware, microwave links. Controversial: liquidity provider OR market parasite depending on perspective.'),
    ('What is Black-Scholes?','Famous option pricing formula (1973). Given: stock price, strike, expiry, risk-free rate, volatility — outputs theoretical option price. Assumes log-normal returns, no dividends, constant vol, European exercise. Modern reality: many violations (volatility smile, jumps); used as baseline + adjusted. Won Nobel; underlies trillion-dollar industry.'),
]
_BLOCKCHAIN=[
    ('What is a blockchain in one paragraph?','Distributed append-only ledger replicated across many nodes. Each block contains transactions + hash of previous block (the chain). Modifying a past block changes all subsequent hashes — detected. Consensus protocol (Proof of Work, Proof of Stake) determines which new block extends the chain. Foundation of cryptocurrencies + smart contracts.'),
    ('What is Bitcoin in plain terms?','First cryptocurrency (2009). Decentralized digital cash. Transactions broadcast to network, miners include in blocks via Proof of Work. Limited supply (21M total). No central authority. Use cases: store of value (digital gold narrative), payments (slower than credit cards, ~10 min confirms). Underlying tech (blockchain) more impactful than Bitcoin itself.'),
    ('What is Ethereum?','Blockchain with built-in scripting language (Solidity). Smart contracts = code stored on-chain, executed by all nodes. Powers DeFi, NFTs, DAOs. Moved from PoW to PoS in 2022 (The Merge) — 99% less energy. Transaction fees ("gas") spike under load.'),
    ('What is a smart contract?','Code stored on a blockchain, automatically executed by all nodes. Deterministic, transparent, immutable. Use for: financial agreements, automated escrow, governance, token issuance. Languages: Solidity (Ethereum), Rust (Solana), Move (Sui/Aptos). Pitfalls: bugs are forever (unless contract self-upgrades); high-profile hacks (Parity, DAO).'),
    ('What is Proof of Work vs Proof of Stake?','PoW: miners solve computationally expensive puzzle; first finder gets to add block + earn reward. Bitcoin\'s mechanism. Energy-intensive but Sybil-resistant via cost. PoS: validators stake (lock) coins; pseudorandomly selected to propose blocks proportional to stake. Cheating slashed (lose stake). Massively less energy. Ethereum, Cardano, Solana, etc.'),
    ('What is a DeFi protocol?','Decentralized Finance. Smart-contract based financial services without traditional banks. Lending (Aave, Compound), trading (Uniswap), derivatives (dYdX), stablecoins (DAI). Open + composable ("money legos"). Risks: smart contract bugs, oracle manipulation, regulatory uncertainty.'),
    ('What is a NFT?','Non-Fungible Token. Unique digital token on a blockchain, often pointing to artwork/media. Each is distinct (vs fungible tokens like BTC where every coin = same). Mostly built on Ethereum (ERC-721). Speculative bubble peaked 2021. Real long-term use cases (provenance, identity, in-game items) still being figured out.'),
]
_HEALTHCARE_TECH=[
    ('What is HIPAA in software terms?','US healthcare privacy law. PHI (Protected Health Information) — patient-identifiable health data — must be encrypted at rest + in transit, access logged, BAA (Business Associate Agreement) required with any vendor handling it, breach notification mandated. Building healthcare apps: pick HIPAA-compliant infrastructure (AWS, GCP, Azure all offer); architect for least privilege.'),
    ('What is HL7/FHIR?','Standards for healthcare data exchange. HL7 v2: legacy pipe-delimited messages (still dominant). FHIR: modern REST + JSON resources for clinical data (Patient, Observation, Medication, etc.). Use FHIR for new integrations. SMART on FHIR: launch web apps within EHRs with OAuth.'),
    ('What is an EHR/EMR?','Electronic Health Record (EHR) / Electronic Medical Record (EMR). Database holding patient records, integrated with order entry, billing, scheduling. Major vendors: Epic, Cerner (Oracle), athenahealth, Allscripts. Most healthcare-adjacent software integrates with EHRs (read patient data, write back results).'),
    ('What is interoperability in healthcare and why hard?','Different hospitals/systems sharing patient data seamlessly. Hard because: vendor lock-in (Epic and Cerner historically restrictive), legacy data formats, varying terminologies (SNOMED, LOINC, ICD-10), strong privacy laws, governance/consent complexity. Improving via FHIR + regulatory pressure (Cures Act in US).'),
]
_GAMING_DEEP=[
    ('What is the Entity Component System (ECS) pattern in detail?','Separate WHAT (data, components) from HOW (behavior, systems) from WHO (entity, ID). Entity = just an ID. Component = pure data struct (Position, Velocity, Sprite). System = logic that operates on entities matching certain components. Cache-friendly (components packed in arrays). Parallelizable. Modern: Bevy (Rust), Unity DOTS, Unreal Mass Entity.'),
    ('What is a game engine?','Software framework providing common game functionality so you don\'t reimplement. Rendering, physics, audio, input, scripting, asset pipeline. Major: Unity (C#), Unreal (C++/Blueprint), Godot (GDScript/C#), Bevy (Rust). Pick based on team skills, target platforms, performance needs, business model.'),
    ('What is client-side prediction in multiplayer games?','Local player\'s actions applied immediately client-side, server confirms later. Reduces perceived input lag. If server disagrees (due to physics or other players\' actions), reconcile: rewind to server state + replay subsequent local inputs. Critical for fast-paced games (FPS, fighting). Without it: 100ms lag = unplayable.'),
    ('What is lag compensation in multiplayer games?','Server rewinds world to where shooter saw it when they fired (client\'s observed time). Determines hit based on that. Compensates for latency so shots feel "fair" to the shooter. Trade-off: from victim\'s perspective, "they shot me after I went around the corner." Both sides have valid grievances; choose tradeoff.'),
    ('What is procedural generation?','Generate game content (levels, items, terrain, missions) algorithmically rather than hand-authored. Saves dev time + creates near-infinite content. Techniques: noise functions (Perlin, Simplex) for terrain, L-systems for plants, wave function collapse for tilemaps, simulation for civilizations (Dwarf Fortress). Used in: roguelikes, Minecraft, No Man\'s Sky.'),
]
LESSONS=_FINANCE+_BLOCKCHAIN+_HEALTHCARE_TECH+_GAMING_DEEP
