"""Embedded + low-level systems — C/C++, MCU, RTOS, memory management."""
_C_LANG=[
    ('What is the difference between malloc and calloc?','malloc(n): allocates n bytes uninitialized (contains whatever was there). calloc(n, size): allocates n*size bytes, ZEROED. malloc is slightly faster (no zeroing). Use calloc when you need zero init (most struct/array allocations); use malloc when you\'ll immediately overwrite (memcpy from elsewhere).'),
    ('What is the difference between a pointer and a reference?','C has only pointers (T*). C++ adds references (T&). Pointer: can be null, can be reassigned, explicit dereference (*p, ->). Reference: can\'t be null (must bind to existing), can\'t rebind, transparent (use like the object). Use references for: function parameters that won\'t be null. Pointers for: optional values, dynamic allocation, pointer arithmetic.'),
    ('What is the stack vs the heap?','Stack: function-local variables, LIFO order, allocated on function entry, freed on return. Fast (just adjust SP). Limited size (~1-8MB typically). Heap: malloc/new — allocated explicitly, lives until free/delete. Slower, can be much larger. Bug to avoid: returning pointer to stack variable (it\'s gone after function returns). Stack overflow = recursing too deep or huge local arrays.'),
    ('What is a buffer overflow and why dangerous?','Writing past the end of a buffer overwrites adjacent memory — including return addresses on the stack. Attacker crafts input that overwrites return address with their code\'s address. C/C++ default. Mitigations: stack canaries, ASLR, DEP, modern compilers warn. Use safer functions: strncpy not strcpy, snprintf not sprintf, std::string not char*. Better: switch to Rust for new code.'),
    ('What is the difference between heap and stack overflow?','Heap overflow: writing past heap allocation, corrupts other allocations (often crashes later with mysterious error). Stack overflow: recursion too deep or huge local array — usually instant crash with stack overflow error. Both indicate bugs; both are exploitable in C/C++.'),
    ('What is a memory-mapped I/O?','Hardware registers exposed as memory addresses. Read/write to those addresses → talks to hardware. Common in MCUs, GPU, network cards. `volatile` keyword critical: tells compiler not to optimize away/reorder reads — values can change underneath. `*(volatile uint32_t*)0x40020000 = 0x1;` writes to register at that address.'),
    ('What is endianness?','Byte order for multi-byte values. Big-endian: most-significant byte first (network byte order, PowerPC). Little-endian: least-significant first (x86, ARM). Matters when: reading binary files across systems, network protocols. htons/htonl/ntohl convert. Always use these for portable network code, never raw casts.'),
    ('What is the difference between volatile and atomic?','volatile (C/C++): prevents compiler from optimizing away reads/writes — for hardware regs, signal handlers. Does NOT provide thread synchronization. atomic (C11/C++11): guarantees indivisible access + provides memory ordering for thread-safe access. For multithreaded code, use atomic, not volatile.'),
]
_MCU_RTOS=[
    ('What is a microcontroller (MCU) vs a microprocessor (MPU)?','MCU: CPU + RAM + flash + peripherals on one chip. Small (KB of RAM), low-power, runs bare-metal or RTOS. Examples: STM32, ESP32, ATmega. MPU: CPU only, needs external RAM + storage, runs full OS (Linux). Examples: Raspberry Pi SoC, server CPUs. MCUs for: sensors, IoT nodes, embedded control. MPUs for: anything needing a real OS.'),
    ('What is an RTOS?','Real-Time Operating System. Provides: preemptive scheduling with guaranteed worst-case latencies, primitives for tasks/semaphores/queues. Used in: medical devices, automotive, aerospace, IoT. Examples: FreeRTOS (most popular, open-source), Zephyr, RTEMS, ThreadX, VxWorks. NOT Linux (general-purpose, no hard timing guarantees) — Linux PREEMPT_RT comes close.'),
    ('What is the difference between hard and soft real-time?','Hard real-time: missing a deadline is a FAILURE (catastrophic — airbag, pacemaker, brake system). Soft real-time: deadlines are goals, occasional miss degrades quality but acceptable (video stream, game frame). Hard RT requires: hardware support, certified RTOS, deterministic memory allocation, no dynamic allocation in hot path. Mostly different field from typical app dev.'),
    ('What is interrupt-driven programming?','Hardware signals CPU asynchronously — CPU pauses current code, runs ISR (Interrupt Service Routine), resumes. Use for: hardware events (button press, timer expire, byte received). Rules: ISR must be SHORT (no printf, no malloc, no blocking), set flag/queue work for main loop to handle. ISRs disable lower-priority interrupts briefly — keep them tight or you miss events.'),
    ('What is DMA (Direct Memory Access)?','Hardware copies data without CPU. Example: peripheral receives a chunk via DMA into RAM, CPU only sees one interrupt when whole transfer done. Frees CPU for other work. Used in: high-throughput peripherals (audio, USB, ethernet, SPI/I2C in modern MCUs). Common in modern systems; transparent to higher levels.'),
    ('What is a watchdog timer?','Hardware counter that resets the MCU if not "kicked" (reset) within timeout. Last-resort recovery from firmware hang. Use: enable watchdog at boot, kick from main loop, if main loop wedged → watchdog resets system. Don\'t kick from ISR — ISR running while main loop hung shouldn\'t mask the bug. Critical for unattended embedded systems.'),
]
_LOW_LEVEL=[
    ('What is cache coherence?','In multi-core systems with per-core caches, ensures all cores see a consistent view of memory. Protocols (MESI, MOESI) track cache line states across cores. Cost: writing a shared line from one core invalidates that line on others — false sharing (unrelated variables in same cache line) hurts perf badly. Padding/alignment fixes it.'),
    ('What is a memory barrier?','CPU instruction preventing memory reorder across the barrier. Modern CPUs reorder loads/stores for performance — fine in single-threaded code, breaks lock-free algorithms. Memory ordering types: relaxed, acquire (loads before this stay before), release (stores after this stay after), seq_cst (full ordering). Higher-level: atomic ops + locks insert barriers automatically.'),
    ('What is a syscall?','Request to OS kernel from userspace. Mode switch from user → kernel ring, kernel handles, returns. Cost: context switch overhead (~50-1000ns). Common: open/read/write/close, mmap, fork, sockets. Heavy: many syscalls per request hurts throughput (use batching, larger buffers, io_uring on Linux for batched async I/O).'),
    ('What is virtual memory?','Each process sees its own contiguous address space; OS+MMU map it to physical RAM (or disk). Benefits: process isolation, memory protection, overcommit, swapping, copy-on-write for fork. Cost: page table walks (TLB caches recent translations). Page fault: accessed memory not in RAM, kernel loads from disk or terminates process.'),
    ('What is mmap and when use it?','Maps a file or device into the process address space — read/write the file like memory. Pros: zero-copy reads (OS pages in on access), shared between processes (shared map), simpler code than read/write loops. Cons: not great for streaming or remote files, harder to handle errors mid-access. Great for: random access to large files, IPC.'),
]
LESSONS=_C_LANG+_MCU_RTOS+_LOW_LEVEL
