"""World knowledge facts — geography, history, science basics, units, common questions. Covers high-frequency factual lookups so Adam answers instantly without Gemma generation."""
_GEOGRAPHY=[
    ('What is the largest country by area?','Russia, about 17.1 million km². Spans 11 time zones. Canada is second at 9.98M km², China and USA tied roughly third around 9.6M km².'),
    ('What is the most populous country?','India, ~1.43 billion people (overtook China in 2023). China ~1.41B, USA ~340M, Indonesia ~280M, Pakistan ~240M round out top 5.'),
    ('What are the seven continents?','Africa, Antarctica, Asia, Australia (Oceania), Europe, North America, South America. Some models use 5 (combining Americas, combining Eurasia) or 6 (combining Eurasia OR combining Americas). The 7-continent model is most common in English-speaking countries.'),
    ('What is the longest river in the world?','Nile, about 6,650 km (4,130 mi). Some recent surveys argue the Amazon is longer (~6,400-7,000 km depending on which tributary counted). Both flow north-to-south to a sea (Mediterranean, Atlantic) and drain ancient drainage basins.'),
    ('What is the tallest mountain?','Mount Everest, 8,848.86 m (29,031.7 ft) above sea level. From base to summit, Mauna Kea in Hawaii is taller (~10,200 m) but most of it is underwater. K2 is the second highest peak above sea level at 8,611 m.'),
    ('What is the largest desert?','By the formal definition (low precipitation, not necessarily hot), Antarctica is the largest desert at ~14M km². The largest hot desert is the Sahara at ~9M km². Other major hot deserts: Arabian, Gobi, Kalahari, Patagonian.'),
    ('How many countries are there?','193 UN member states + 2 observer states (Vatican, Palestine) = 195 widely recognized. Taiwan, Kosovo, and a few others are partially recognized. The number is approximate because political boundaries change.'),
    ('What is the capital of Australia?','Canberra. Common wrong answer is Sydney (largest city) or Melbourne (cultural capital). Canberra was a planned compromise city built in the 1910s to resolve the rivalry between Sydney and Melbourne.'),
    ('What is the capital of Brazil?','Brasília. Built from scratch in the 1950s as a planned capital to encourage development of the interior, replacing Rio de Janeiro as capital in 1960.'),
    ('What is the capital of Canada?','Ottawa, in Ontario province. Not Toronto (largest city) or Montreal. Ottawa was chosen by Queen Victoria in 1857 as a compromise between English- and French-speaking factions.'),
]
_HISTORY=[
    ('When did World War 2 end?','In Europe: 8 May 1945 (V-E Day, Germany\'s unconditional surrender). In the Pacific: 2 September 1945 (Japan\'s formal surrender aboard USS Missouri, following the atomic bombings of Hiroshima 6 Aug and Nagasaki 9 Aug 1945).'),
    ('When did humans first land on the Moon?','20 July 1969. Apollo 11 mission. Neil Armstrong stepped out first, Buzz Aldrin followed; Michael Collins remained in lunar orbit. Five more Apollo missions landed humans on the Moon, the last being Apollo 17 in December 1972.'),
    ('Who was the first president of the United States?','George Washington, 1789-1797. Set many lasting precedents: cabinet system, two-term limit (informally — later formalized via 22nd Amendment), inaugural address, farewell address tradition.'),
    ('When did the Roman Empire fall?','Conventional date: 476 CE for the Western Roman Empire (Romulus Augustulus deposed by Odoacer). The Eastern Roman Empire (Byzantine) continued until 1453 CE when Constantinople fell to the Ottoman Turks. Many historians argue the "fall" was actually a gradual transformation over centuries.'),
    ('When was the printing press invented?','Gutenberg developed movable-type printing in Europe ~1440-1455, with his famous Bible printed around 1455. Movable type had been invented earlier in China (Bi Sheng, ~1040 CE) and Korea (metal type, ~1234), but Gutenberg\'s system was the one that triggered the European print revolution.'),
    ('When did the French Revolution start?','14 July 1789 — storming of the Bastille is the symbolic start (now Bastille Day). The Estates-General had convened in May, the Tennis Court Oath was 20 June. The Revolution went through phases (constitutional monarchy, Republic, Terror, Directory) until Napoleon\'s coup in November 1799.'),
    ('Who wrote the US Declaration of Independence?','Thomas Jefferson was the primary author, with edits by John Adams, Benjamin Franklin, and the Continental Congress. Adopted 4 July 1776. Famous opening: "We hold these truths to be self-evident, that all men are created equal..."'),
]
_SCIENCE_FACTS=[
    ('How fast is the speed of light?','Exactly 299,792,458 meters per second in vacuum (the meter is now DEFINED by light\'s speed). Roughly 186,282 mi/s. Light from the Sun takes about 8 min 20 sec to reach Earth. From Alpha Centauri (nearest star system) ~4.37 years.'),
    ('What is absolute zero?','-273.15°C = -459.67°F = 0 Kelvin. Theoretical lowest temperature where atomic motion would cease (in classical thinking; quantum mechanics adds zero-point motion). Has never been reached, only approached. Practical experiments get within billionths of a degree.'),
    ('What is the speed of sound?','In air at sea level, 20°C: about 343 m/s (~767 mph, ~1235 km/h). Mach 1 = local speed of sound. Slower in cold air, faster in warm. In water: ~1480 m/s (~4x faster). In steel: ~5100 m/s. Sound needs a medium; doesn\'t travel in vacuum.'),
    ('How many bones in the human body?','206 in an adult. Babies are born with about 270 — many fuse during childhood (especially in skull and pelvis). The smallest bones are in the middle ear (malleus, incus, stapes). The longest is the femur (thigh bone).'),
    ('What is the chemical formula for water?','H₂O — two hydrogen atoms covalently bonded to one oxygen atom. The bonds are angled at about 104.5°, making water a polar molecule (oxygen pulls electrons strongly). This polarity gives water nearly all its life-essential properties: solvent power, surface tension, high boiling point relative to mass.'),
    ('How many planets in our solar system?','8: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. Pluto was reclassified as a "dwarf planet" in 2006 by the IAU because it hasn\'t cleared its orbital neighborhood. Other dwarf planets include Eris, Haumea, Makemake, Ceres.'),
    ('What is DNA?','Deoxyribonucleic acid — long double-helix molecule that stores genetic information using four bases (adenine, thymine, guanine, cytosine; A-T and G-C pair). Found in nearly every cell. Human DNA is about 3 billion base pairs split into 23 pairs of chromosomes. Discovered as carrier of inheritance by Avery in 1944; double-helix structure by Watson, Crick (with Franklin\'s data) in 1953.'),
    ('How old is the Earth?','About 4.54 billion years, give or take 50 million. Dated primarily by radiometric dating of meteorites (assumed to form around the same time as Earth) and zircon crystals on Earth. The universe is ~13.8 billion years old, so the Earth has been around for about 1/3 of cosmic history.'),
    ('What is gravity?','The attraction between any two objects with mass, proportional to the product of masses and inversely proportional to distance squared (Newton). Einstein reframed it as the curvature of spacetime caused by mass-energy (general relativity, 1915). At everyday scales Newton\'s formula is plenty accurate; at high speeds, strong fields, or GPS-level precision, you need relativity.'),
    ('What is gravity\'s acceleration on Earth\'s surface?','9.81 m/s² (often approximated as 9.8 or just "g"). Varies slightly: ~9.78 at equator (centrifugal effect from Earth\'s rotation reduces apparent gravity), ~9.83 at poles. On the Moon: ~1.62 m/s². On Mars: ~3.71 m/s². On Jupiter (surface defined where pressure equals Earth atmospheric): ~24.79.'),
]
_UNITS=[
    ('How many kilometers in a mile?','1 mile = 1.60934 km. Rough conversion: multiply by 1.6 (or 8/5). Conversely 1 km ≈ 0.621 miles. Marathon = 26.2 miles ≈ 42.2 km.'),
    ('How many feet in a meter?','1 meter ≈ 3.28084 feet. Rough: meter is a bit more than 3 feet. Conversely 1 foot = 0.3048 m exactly (by definition since 1959). Height 6\' = ~1.83 m.'),
    ('How many liters in a gallon?','US gallon = 3.785 liters. UK (imperial) gallon = 4.546 liters (~20% bigger). Roughly: 1 US gallon ≈ 4 liters for back-of-envelope. Car fuel economy: 30 mpg (US) ≈ 7.8 L/100km.'),
    ('How many pounds in a kilogram?','1 kg ≈ 2.20462 pounds. Rough: multiply kg by 2.2. Conversely 1 lb ≈ 0.454 kg. Body weight 180 lb ≈ 82 kg.'),
    ('What is the difference between Celsius and Fahrenheit?','Celsius: water freezes at 0°C, boils at 100°C (at sea level). Fahrenheit: freezes 32°F, boils 212°F. Conversion: °F = °C × 9/5 + 32. °C = (°F - 32) × 5/9. Both meet at -40 (-40°C = -40°F). Body temperature ~37°C ≈ 98.6°F. Comfortable room 20-22°C ≈ 68-72°F.'),
    ('What is the difference between kilobyte, megabyte, gigabyte?','Decimal: 1 KB = 1000 bytes, 1 MB = 1,000,000 bytes, 1 GB = 10^9 bytes. Binary: 1 KiB = 1024 bytes, 1 MiB = 2^20 bytes, 1 GiB = 2^30 bytes. Storage manufacturers use decimal; OSes often use binary, causing the confusing "1 TB drive shows as 931 GB" effect. Network and SI: decimal. RAM and OS file sizes: usually binary.'),
]
_COMMON_QS=[
    ('What is the meaning of life?','One of the oldest open questions in philosophy. Three broad answers: (1) Religious — purpose given by a creator. (2) Naturalist — life has no built-in purpose; meaning is what we create through love, work, growth, relationships. (3) Absurdist (Camus) — life has no inherent meaning, and we should embrace this freedom while still acting as if meaning matters. There is no single correct answer; the question itself is part of being human.'),
    ('Why do we dream?','Several theories, no single consensus: (1) memory consolidation — REM sleep helps integrate the day\'s experiences into long-term memory. (2) emotional processing — working through unresolved feelings. (3) threat simulation — practicing responses to dangers. (4) random neural firing the brain interprets as a story. Likely a combination. Lucid dreaming (awareness during dream) suggests the boundary is softer than it seems.'),
    ('How do magnets work?','Magnetism is caused by aligned electron spins in materials like iron. Each electron is a tiny magnet (spin angular momentum produces magnetic moment). In most materials, electron spins point randomly and cancel. In ferromagnets, neighboring spins align spontaneously below the Curie temperature, creating domains; an external field aligns the domains, producing a strong macroscopic magnet. Field is mediated by virtual photons (electromagnetic force).'),
    ('Why is the ocean salty?','Rainwater is slightly acidic (dissolved CO₂); it weathers rocks on land, dissolving minerals like sodium and chloride. Rivers carry these dissolved ions to the ocean. Water evaporates from the ocean (pure), but the salts stay. Over billions of years salinity built up to ~3.5%. Underwater hydrothermal vents add more minerals directly. The ocean is in a rough steady state — salt deposited at sea floor balances input.'),
    ('Why do we have day and night?','Earth rotates on its axis once every ~24 hours. The half facing the Sun has day; the half facing away has night. The axis is tilted ~23.5° relative to its orbital plane, causing seasons (different hemispheres get more direct sunlight at different times of year). A day is exactly 24 hours by definition; the actual rotation is 23 hours 56 minutes — the extra 4 minutes account for Earth\'s orbital motion around the Sun.'),
    ('Why is the sky blue and sunsets red?','Sunlight contains all visible colors. Earth\'s atmosphere scatters short wavelengths (blue, violet) much more strongly than long ones (red) — Rayleigh scattering, scattering ∝ 1/λ⁴. So we see a blue sky in directions away from the Sun. At sunset, light from the Sun passes through much more atmosphere (low angle through the air); short wavelengths are scattered out completely, leaving red and orange to reach our eyes.'),
    ('How does an airplane fly?','Two principles together: (1) wing shape (airfoil) makes air travel faster over the top than bottom, producing lower pressure above and lift below (Bernoulli\'s principle). (2) the wing deflects air downward; by Newton\'s third law, the wing is pushed upward. Both contribute; emphasis varies by speed and angle of attack. Thrust from engines overcomes drag, lift counters gravity. The four forces: lift, weight, thrust, drag.'),
    ('What is the most spoken language?','By NATIVE speakers: Mandarin Chinese (~940 million). Spanish second (~485M), then English (~380M), Hindi (~345M), Arabic (~275M). By TOTAL speakers including second-language: English wins (~1.5 billion). English is also the dominant lingua franca in business, science, aviation, and the Internet.'),
    ('How many cells are in the human body?','About 30-40 trillion human cells. Plus an estimated 38 trillion bacterial cells (mostly in the gut microbiome) — so you\'re slightly more bacteria than human by cell count, though human cells are larger by mass. The number was long quoted as 100 trillion based on older estimates; a 2013 study revised down.'),
    ('What is the most common element in the universe?','Hydrogen, ~75% of normal matter by mass (and ~92% by number of atoms). Helium next at ~24% by mass. Together they make up ~99% of the universe\'s baryonic matter. Heavier elements (carbon, oxygen, iron, etc.) make up the remaining 1% but include everything that makes Earth interesting. Most of the universe is actually NOT normal matter — dark matter ~5x more, dark energy dominates.'),
]
LESSONS=_GEOGRAPHY+_HISTORY+_SCIENCE_FACTS+_UNITS+_COMMON_QS
