"""Extended world knowledge — biology, chemistry, physics, technology, languages."""
_BIO=[
    ('What is the central dogma of molecular biology?','DNA → RNA → Protein. DNA contains the genetic instructions; transcription copies a gene into messenger RNA; translation uses mRNA + ribosomes to assemble proteins from amino acids. Exceptions: some viruses use RNA → DNA (reverse transcription via reverse transcriptase). Prions are protein-only, no nucleic acid template.'),
    ('What are the four nucleotides in DNA?','Adenine (A), Thymine (T), Guanine (G), Cytosine (C). Pair as A-T (two H bonds) and G-C (three H bonds — stronger). In RNA, thymine is replaced by uracil (U). The base sequence encodes genetic information; three bases (codon) specify one amino acid.'),
    ('What is mitosis vs meiosis?','Mitosis: one diploid cell → two identical diploid cells. For growth + repair. Meiosis: one diploid cell → four haploid cells (eggs, sperm). For sexual reproduction. Meiosis has two divisions + recombination (crossing over) for genetic diversity. Errors in meiosis → chromosomal abnormalities (Down syndrome from trisomy 21).'),
    ('What is the human genome size?','About 3 billion base pairs, ~20,000 protein-coding genes. Only ~1-2% codes for protein; rest includes regulatory regions, repetitive DNA, transposons, non-coding RNAs. Each cell has ~2m of DNA packed into a ~10μm nucleus. Sequenced first in 2003 (Human Genome Project), now done routinely for under $1000.'),
    ('What is CRISPR?','Bacterial immune system co-opted as gene-editing tool. Cas9 protein guided by a designed RNA cuts DNA at matching sequence; cell repairs the break, often introducing a desired edit. Revolutionized molecular biology since 2012. Won Nobel Prize 2020 (Doudna + Charpentier). Used for: research, gene therapy (sickle cell approved 2023), agriculture, hypothetically humans.'),
    ('What is the difference between bacteria and viruses?','Bacteria: living single-cell organisms with metabolism, can reproduce alone. Killed by antibiotics. Viruses: NOT alive in usual sense — protein shell + nucleic acid, can\'t reproduce without host cell. Antibiotics don\'t work; antivirals + vaccines do. Most "stomach bug" / "cold" infections are viral (antibiotics useless and contribute to resistance).'),
]
_CHEM=[
    ('What is the periodic table?','Arrangement of all known elements by atomic number (proton count). Same column = similar chemical behavior (valence electrons). 118 elements known (94 natural, rest synthetic). Groups: alkali metals (1), noble gases (18), halogens (17), transition metals (3-12). Periods (rows) reflect electron shell filling.'),
    ('What is pH and how does it work?','Scale of acidity/alkalinity, 0-14. Defined as -log10[H+]. pH 7 neutral, <7 acidic, >7 basic. Each unit = 10x concentration change. Stomach: pH 2 (very acidic). Blood: 7.35-7.45 (tightly regulated). Pool water: 7.2-7.8. Battery acid: ~0. Drain cleaner: ~14.'),
    ('What is the difference between an ionic and covalent bond?','Ionic: electrons transferred from one atom to another (typically metal + nonmetal: NaCl). Charged ions held together by electrostatic attraction. Often soluble in water (dissociate into ions). Covalent: electrons SHARED between atoms (typically two nonmetals: H₂O). Discrete molecules. Most organic compounds are covalent.'),
    ('What is a mole and Avogadro\'s number?','Mole = 6.022 × 10²³ particles (Avogadro\'s number). Lets chemists count atoms by weighing. 1 mole of carbon-12 = exactly 12 grams. Atomic mass on periodic table = grams per mole. Used to convert between number of particles, mass, and moles in reactions.'),
    ('What is a catalyst?','Substance that speeds up a reaction without being consumed. Provides alternative reaction path with lower activation energy. Doesn\'t change equilibrium (just gets there faster). Enzymes are biological catalysts (proteins). Industrial: platinum in catalytic converters, vanadium pentoxide in sulfuric acid production. Trillion-dollar industry.'),
]
_PHYS_DEEP=[
    ('What are the four fundamental forces?','Strong nuclear (holds nuclei together; quarks via gluons). Electromagnetic (light, electricity; via photons). Weak nuclear (radioactive decay; via W/Z bosons). Gravity (everywhere; mediator hypothetical graviton, not detected). Strong + EM + weak unified at high energy in Standard Model. Gravity not yet unified — Theory of Everything remains open.'),
    ('What is quantum entanglement?','Two particles can be linked such that measuring one instantly determines the state of the other, regardless of distance. Einstein called it "spooky action at a distance." Doesn\'t allow faster-than-light communication (random outcomes). Foundation of: quantum cryptography, quantum computing, quantum teleportation. Demonstrated experimentally over hundreds of km (Bell tests, satellite QKD).'),
    ('What is general relativity in one paragraph?','Einstein 1915. Gravity isn\'t a force — it\'s the geometry of spacetime curved by mass-energy. Massive objects warp spacetime; other objects move along curved paths (geodesics). Predicts: gravitational time dilation (clocks tick slower in gravity wells — GPS depends on this), light bending, gravitational waves (detected 2015), black holes. Reduces to Newtonian gravity in weak fields.'),
    ('What is the Higgs boson?','Quantum excitation of the Higgs field that pervades all space. Particles get mass by interacting with this field (more interaction = more mass). Photons don\'t interact → massless. Confirmed 2012 at the LHC. Last piece of the Standard Model. Doesn\'t explain dark matter, dark energy, or why gravity is so weak — many open questions remain.'),
    ('What is dark matter?','Invisible matter inferred from gravitational effects on galaxies and cosmic structure. ~27% of the universe vs ~5% normal matter. Doesn\'t interact with light (hence "dark"). Composition: unknown — WIMPs, axions, primordial black holes, MOND theories all candidates. Active research area. Don\'t confuse with dark energy (~68%, accelerates universe expansion, even more mysterious).'),
]
_TECH=[
    ('What is the difference between RAM and storage?','RAM (DRAM): fast, volatile (loses contents on power-off), used for active computation. ~10s of GB on modern PCs. ~10ns access. Storage (SSD/HDD): slow, persistent, holds files. ~TB scale. SSD ~100µs, HDD ~10ms. Hierarchy: registers > L1 > L2 > L3 cache > RAM > SSD > HDD > tape. Speed-cost-capacity trade across levels.'),
    ('What is the difference between a CPU and a GPU?','CPU: few cores (4-64), each fast and general-purpose, deep cache, big control logic. Best for: sequential code, branching, OS, business logic. GPU: thousands of small cores, optimized for parallel arithmetic, smaller cache, less control logic per core. Best for: same operation on lots of data (graphics, ML training, video encoding, crypto mining).'),
    ('What is Moore\'s Law?','Empirical observation (Gordon Moore, 1965): number of transistors on a chip doubles ~every 2 years. Held for ~50 years. Slowing now (atoms have a size; quantum tunneling; heat). Drove the digital revolution. Successors: chiplets, 3D stacking, specialized accelerators (AI chips, FPGAs). Software is still catching up — many programs don\'t use the cores they\'re given.'),
    ('What is the difference between WiFi and Bluetooth?','WiFi: high bandwidth (~100 Mbps - several Gbps), longer range (~30m indoor), more power, primarily TCP/IP based. Best for: internet access, file transfer, video stream. Bluetooth: low bandwidth (~1-2 Mbps classic, less for BLE), short range (~10m), low power, peer-to-peer focused. Best for: peripherals (keyboards, headphones), IoT (BLE).'),
    ('What is HTTPS in plain terms?','HTTP wrapped in TLS encryption. Three things: (1) confidentiality — eavesdropper sees encrypted bytes only. (2) integrity — tampering detected. (3) server identity — verified via signed certificate. Doesn\'t protect: client-side compromise, server-side breach, metadata (which sites you visit at DNS/SNI level). Everywhere on modern web; HTTP without S is rare and increasingly browser-blocked.'),
]
_LANG=[
    ('What language is most spoken natively?','Mandarin Chinese, ~940 million native speakers (mostly Mainland China + Taiwan + Singapore). Spanish second (~485M), English third (~380M native). For total speakers including L2: English wins (~1.5 billion) as global lingua franca for business, science, aviation.'),
    ('Why do we have languages with different alphabets?','Cultural and historical evolution. Most modern alphabets descend from Phoenician (~1200 BCE), which spread via trade. Branches: Greek → Latin (Western Europe), Greek → Cyrillic (Slavic). Arabic from Aramaic. Devanagari (Sanskrit, Hindi). Chinese characters: logographic — represent meaning + sound, very different system. Korean Hangul invented in 1443 — explicitly designed, not evolved.'),
    ('What is the most widely spoken second language?','English by a wide margin — taught in nearly every country\'s school system, dominant in international business, science, aviation (mandated by ICAO), academia. After English: French in many African countries, Spanish in the Americas, Mandarin growing, Russian in former Soviet states. Bilingualism rates: highest in countries with non-dominant native language (Netherlands ~90% English fluency).'),
    ('How many languages exist in the world?','About 7,000 actively spoken. Highly uneven: top 20 cover ~50% of world population; majority of languages have <100k speakers. Dying fast: linguists estimate ~half will disappear this century. Most diverse regions: Papua New Guinea (~840 languages), Indonesia, Nigeria, India.'),
]
LESSONS=_BIO+_CHEM+_PHYS_DEEP+_TECH+_LANG
