"""Frontend frameworks beyond React — Vue, Svelte, plus testing and bundlers."""
_VUE=[
    ('What is Vue 3 Composition API vs Options API?','Options API: organize by option type (data, methods, computed, watch) — easier for beginners. Composition API (setup function or <script setup>): organize by FEATURE — related state+behavior together — better for complex components and reuse via composables. Vue 3 supports both. New projects: Composition API + <script setup>.'),
    ('What is ref vs reactive in Vue?','ref(value): wraps any value, access via .value in JS. reactive(obj): wraps object, fields tracked directly. ref works for primitives, reactive for objects only. Both make Vue track reads/writes for re-rendering. Use ref by default (works everywhere); reactive when you want object-without-.value. <script setup> auto-unwraps refs in template (no .value).'),
    ('What is a Vue composable?','Reusable function using composition API that bundles related reactive state + logic. By convention starts with "use": `useMouse()`, `useFetch()`. Returns refs/computed. Replaces mixins (Vue 2) — composables are cleaner, no naming collisions, full type inference. Pattern: extract any logic shared between components into a composable.'),
    ('What is the Vue watch vs computed?','computed: derived value, lazy, cached, returns new value. `const fullName = computed(() => first.value + last.value)`. watch: side effect on change, no return value. `watch(source, (newVal, oldVal) => { ... })`. Rule: use computed for "what should this be"; use watch for "do something when this changes."'),
    ('What is v-model in Vue?','Two-way binding on form inputs: `<input v-model="name">`. Syntactic sugar for :value + @input event. For custom components: emit "update:modelValue" event, receive via v-model on parent. Multiple v-models: `<MyComp v-model:title="title" v-model:body="body">`. Avoids manual prop+event boilerplate.'),
    ('What is the difference between Vue and React in practice?','Vue: template-first (HTML-like syntax), built-in reactivity, more "batteries included" (router, state lib by core team), gentler learning curve. React: JSX (JS-first), explicit hooks, larger ecosystem, more "compose your own stack." Both fine for new projects; Vue often quicker to ship small/medium apps, React deeper for very large ones + better job market.'),
]
_SVELTE=[
    ('What is Svelte?','Compiler-first framework. Your .svelte files compile at BUILD time to vanilla JS that updates the DOM directly — no runtime virtual DOM. Result: smaller bundles, faster first paint, less framework runtime to ship. Reactivity is just JS variable assignments tracked by the compiler. Trade-off: smaller ecosystem than React/Vue, less mature tooling for huge apps.'),
    ('What is reactivity in Svelte?','Just assignment. `count = count + 1` triggers a re-render. Compiler analyzes which DOM elements depend on which variables and updates only those. `$:` prefix declares reactive statements: `$: doubled = count * 2`. Cleaner than hooks/refs in React. Caveat: array.push won\'t trigger — reassign: `arr = [...arr, x]`.'),
    ('What are Svelte stores?','Reactive state outside component instances, shared across components. writable(initial) returns store; subscribe via $store in templates. Set with store.set(v) or store.update(fn). readable + derived for read-only and computed. Stores fill the same role as Redux/Vuex but with much less ceremony.'),
    ('What is SvelteKit?','Full-stack framework on top of Svelte (like Next.js for React). File-based routing, SSR + SSG + hydration, API routes, form actions, layouts. Cleaner than Next.js in many ways. Use for: new full-stack apps, JAMstack sites, hybrid render apps. Adapter system targets Vercel, Cloudflare, Netlify, Node, static.'),
]
_TESTING=[
    ('What is the difference between unit, integration, and end-to-end tests?','Unit: tests one function/class in isolation, fast, lots of them. Integration: tests how units work together (often with real dependencies — DB, API). End-to-end: tests the whole system through the UI as a user would (Cypress, Playwright). Pyramid: lots of unit (cheap, fast), fewer integration, fewest e2e (slow, flaky, expensive). Trophy model (modern): heavy on integration, light on units.'),
    ('What is Jest vs Vitest?','Jest: established JS test runner, works with most frameworks, slower (rebuilds with each run). Vitest: modern alternative using Vite — much faster (esbuild), native ESM, near-Jest API compatibility. For new projects using Vite: Vitest. For React Native or specific tooling: Jest still common. Both: describe/it/expect API.'),
    ('What is Cypress vs Playwright?','Cypress: e2e in browser via JS, runs in same browser context, great DX with time-travel debugging. Limited to Chromium-based + recent Firefox/WebKit; one tab at a time. Playwright (Microsoft): runs all major engines (Chromium, Firefox, WebKit), multi-tab, multi-context, faster, more capable. New projects: Playwright. Existing Cypress: fine, don\'t rush to migrate.'),
    ('How do I test code that has time-dependent behavior?','Mock the clock. JS: jest.useFakeTimers() + jest.advanceTimersByTime(1000). Python: freezegun or unittest.mock.patch("time.time"). Always inject "now" as a dependency rather than calling time.now() directly — makes testing trivial. For animations/intervals: fake timers + advance manually.'),
    ('What is property-based testing?','Generate many random inputs satisfying a property, assert invariant holds. JS: fast-check. Python: Hypothesis. Rust: proptest. Catches edge cases unit tests miss because the test author doesn\'t think of them. Example: `forall x, y: sort([x, y]) is sorted`. When property fails, library shrinks the input to minimal failing example.'),
]
_BUNDLERS=[
    ('What is Vite and why use it?','Modern build tool by Vue\'s creator. Dev: serves source files directly via native ES modules — near-instant startup, fast HMR (only reloads changed module). Build: uses Rollup for production bundle — tree-shaking, code-splitting, minification. Much faster than webpack for dev. Framework-agnostic plugins (Vue, React, Svelte, SolidJS). New projects: default to Vite.'),
    ('What is webpack vs Vite vs esbuild?','webpack: original bundler, mature, slow but most configurable, biggest ecosystem. esbuild: written in Go, 10-100x faster, less feature-rich. Vite: uses esbuild for dev, Rollup for prod — best of both. For new projects: Vite. For Next.js / React Server Components: use what the framework provides (Turbopack, SWC). webpack still everywhere in older codebases.'),
    ('What is tree-shaking?','Bundler eliminates unused exports from the final bundle. Requires ESM (static imports — `import {foo} from "lib"`, not require/dynamic). Reduces bundle size significantly when using only parts of a library. Trap: side-effectful modules (importing for side effect) won\'t shake — mark "sideEffects": false in package.json to opt in.'),
    ('What is HMR (hot module replacement)?','Dev-time feature: when a module changes, only that module reloads in the browser, preserving app state. Implemented per framework (React Fast Refresh, Vue HMR). Faster feedback than full reload. Some changes still need full reload (entry-point changes, certain module-level state).'),
]
LESSONS=_VUE+_SVELTE+_TESTING+_BUNDLERS
