"""Functional programming corpus — Haskell/Scala/Elixir/F#, lambda calc, FP patterns in any language."""
_FP_BASICS=[
    ('What is a pure function?','Function whose output depends ONLY on inputs + has NO side effects (no I/O, no mutation, no global state read/write). Always returns same output for same inputs. Trivially testable + parallelizable + memoizable. Math functions are pure. Most code in mainstream languages is NOT pure — but isolating pure cores from impure shells is a powerful design.'),
    ('What is referential transparency?','Property of an expression: can be replaced by its value without changing program behavior. `2 + 3` is referentially transparent (always 5). `random()` is not (returns different values). Pure functions enable referential transparency. Lets compilers + humans reason about code locally — substitution works.'),
    ('What is immutability and why does it matter?','Data never changes after creation. New data structures returned instead. Pros: thread-safe (no races), easier to reason (state at any time = constructor args + transformations), enables structural sharing + persistent data structures, undo/redo trivial. Cons: more allocation. Modern languages provide efficient persistent structures (Clojure, Scala) so the cost is small.'),
    ('What is a higher-order function?','Function that takes a function as argument OR returns a function. Examples: map, filter, reduce, function composition, decorators, callbacks. Enables abstraction over BEHAVIOR, not just data. Foundation of functional style. Python: first-class functions support this naturally.'),
    ('What is currying?','Transform a function taking multiple args into a chain of single-arg functions. `f(a, b, c)` becomes `f(a)(b)(c)`. Each call returns a function awaiting the next arg. Useful for: partial application, building specialized functions from general ones. Haskell auto-curries everything; in Python/JS you do it manually (`functools.partial`, arrow functions returning arrows).'),
    ('What is partial application?','Fix some arguments of a function, get a new function awaiting the rest. `add5 = partial(add, 5)`; then `add5(3) == 8`. Different from currying (one arg at a time always) — partial fixes any subset at once. Built into Python via functools.partial. Useful for: specializing callbacks, dependency injection, building DSLs.'),
    ('What is function composition?','Combine functions: (f . g)(x) = f(g(x)). Read right to left. Pipeline style: input flows through transformations. Most languages: write helper or use library (toolz, fp-ts, Ramda). F#/Elixir: built-in `|>` operator: `x |> g |> f`. Builds complex transformations from small reusable pieces.'),
    ('What is a closure in functional terms?','Function bundled with its enclosing scope\'s variables — even after that scope returns. `function makeAdder(x) { return y => x + y }` — returned function "closes over" x. Powers: factory functions, private state, callbacks needing context, partial application. Different from class methods but solves similar problems.'),
    ('What is the difference between map, filter, and fold (reduce)?','map: 1:1 transformation, preserves length. `map(f, [1,2,3])` → `[f(1), f(2), f(3)]`. filter: keep elements matching predicate, length ≤ original. `filter(p, [1,2,3])` → subset. fold/reduce: combine all elements into single value via binary fn. `reduce(+, [1,2,3], 0)` → 6. Compose: filter, map, reduce as pipeline.'),
    ('What is recursion in functional programming?','Function calls itself to solve subproblems. FP\'s answer to loops (which inherently rely on mutation). Tail recursion: recursive call is the last action — compiler can reuse stack frame (no growth). Languages like Scala, Erlang, Scheme guarantee tail call optimization (TCO). Python does NOT — converts to iteration for deep recursion.'),
]
_TYPES=[
    ('What is a monad?','Type with two operations: `unit`/`return` (wrap a value) + `bind`/`flatMap` (sequence operations on the wrapped value, where each can fail/produce side effect). Enables composing effectful computations as if they were pure. Famous examples: Maybe/Option (nullability), Either/Result (error handling), Future/Promise (async), List (nondeterminism), IO (side effects).'),
    ('What is the Maybe/Option monad?','Wraps optional values: Just(x) or Nothing (Some/None). Forces handling absence at type level. flatMap chains: `getUser().flatMap(getProfile).flatMap(getEmail)` — short-circuits at first Nothing. Replaces null checks scattered everywhere. Modern languages bake this in: Rust Option, Swift Optional, Haskell Maybe, Kotlin ?.'),
    ('What is the Either monad?','Holds one of two values: Left e (failure with reason) or Right a (success). Like Maybe but Left carries info about the failure. Chains via flatMap: short-circuits at first Left, carrying the error through. Foundation of Rust\'s Result + Swift\'s Result + many error-handling libraries.'),
    ('What is algebraic data type (ADT)?','Types built by combining other types: SUM types (one of these) + PRODUCT types (this AND that). Sum: Rust enum, Haskell `data`, TypeScript discriminated union. Product: struct, tuple. Together they let you precisely model domain states. Pattern matching destructures both. Captures invariants in types so impossible states are unrepresentable.'),
    ('What is pattern matching?','Destructure data + branch on its shape. Compiler checks exhaustiveness: warns if you missed a case. Powerful with ADTs: `match shape { Circle(r) => pi*r*r, Square(s) => s*s, Triangle(b, h) => b*h/2 }`. Most modern languages have it (Rust, Swift, Scala, Kotlin, Python 3.10+).'),
    ('What is a type class (Haskell) or trait (Rust)?','Ad-hoc polymorphism. Define operations a type must support: `class Eq a where (==) :: a -> a -> Bool`. Implement for each type that needs them. Like interfaces but more flexible: implementations defined separately from types. Foundation of Haskell\'s flexibility. Rust traits + Swift protocols similar.'),
]
_LANGUAGES=[
    ('What is Haskell good for?','Lazy + pure + strongly typed. Best for: type-level guarantees (compiler proves invariants), DSLs, compilers, financial systems, anywhere correctness matters more than tooling. Steep learning. Production: limited but committed companies (Standard Chartered, GitHub Semantic). Real impact: ideas exported to Rust, Scala, TypeScript, Swift.'),
    ('What is Elixir?','Dynamic functional language on Erlang BEAM VM. Ruby-like syntax. Pros: fault-tolerant via Erlang/OTP (lightweight processes, supervisor trees), excellent for distributed + concurrent + real-time (chat, queues, telecoms). Phoenix web framework + LiveView impressive. Smaller ecosystem than mainstream langs but rapidly growing.'),
    ('What is Scala?','JVM functional + OO hybrid. Powerful type system (type inference, generics, implicits/given). Spark + Kafka heavy users. Pros: leverages JVM ecosystem, scales from script to big systems. Cons: complex (multiple syntax styles, slow compile times). Scala 3 simplifies. Job market: niche but well-paid.'),
    ('What is Clojure?','Lisp dialect on JVM. Code is data (homoiconic), immutable persistent data structures by default, transactional STM, transducers. Concise + powerful for: data processing, DSLs, web (Ring/Pedestal), tools. Small but devoted community. ClojureScript compiles to JS. Mental model shift required if coming from imperative.'),
    ('What is F#?','Functional-first language on .NET. ML family (similar to OCaml). Pros: strong types + type inference, great C# interop, pattern matching, computation expressions for monads. Used in: finance, scientific computing, web (Giraffe). Less hyped than Rust/Go but very productive. Microsoft-backed.'),
]
LESSONS=_FP_BASICS+_TYPES+_LANGUAGES
