"""Game development corpus — engines, game loops, physics, rendering, optimization."""
_BASICS=[
    ('What is a game loop?','Heart of every game. Loop forever: (1) process input. (2) update game state (positions, physics, AI). (3) render frame. (4) sleep until next frame. Target frame rate: 60 FPS (16.7ms/frame) standard, 120/144 FPS for competitive games. Fixed timestep for physics (deterministic), variable timestep for rendering (smooth). Decouple update rate from render rate.'),
    ('What is delta time and why use it?','Time elapsed since last frame, in seconds. Multiply all movement by dt so behavior is frame-rate independent: `pos += velocity * dt`. Otherwise: game runs faster on faster computers. Cap dt to avoid huge values on lag spikes (otherwise object teleports through wall). Fixed timestep for physics: accumulate dt, step physics in fixed amounts.'),
    ('What is the difference between Unity and Unreal?','Unity: C#, easier learning curve, faster iteration, dominant for mobile + indie. Less raw performance for AAA. Unreal: C++ + Blueprints, AAA engine, photorealistic rendering, more complex. Bigger learning curve. Free with royalties on revenue. Pick Unity for: mobile, 2D, rapid prototyping. Pick Unreal for: AAA visuals, simulation, archviz, automotive.'),
    ('What is the difference between Godot and Unity/Unreal?','Godot: free, open source, MIT license (no royalties). GDScript (Python-like), C#, or C++. Lighter weight, faster project loading. Smaller ecosystem than Unity/Unreal. Excellent for: 2D games, indie projects, anyone who hates engine lock-in. 4.x added Vulkan + significant 3D improvements. Worth serious consideration in 2024+.'),
    ('What are common game design patterns?','Component-based (Entity-Component-System — entities are bags of components, systems process components of one type). Observer (event bus for decoupled game events). State machine (player states: idle/run/jump/attack). Object pool (reuse bullets, particles — avoid alloc per frame). Command (input → command objects for replay, undo, networking).'),
    ('What is an Entity-Component-System (ECS)?','Architecture splitting game objects into: Entity (just an ID), Component (pure data, e.g., Position, Velocity, Sprite), System (logic that processes entities with certain components). Cache-friendly (components packed in arrays). Highly parallel. Used by: Unity DOTS, Unreal Mass Entity, Bevy (Rust). Steeper than OOP but scales to massive entity counts (RTS, simulations).'),
]
_PHYSICS=[
    ('What is collision detection vs collision response?','Detection: does object A overlap object B? Response: what to do about it (bounce, slide, stop, destroy). Detection is the hard part — broadphase (rough culling via spatial partitioning: grid, BVH, quadtree) then narrowphase (exact check for nearby pairs). Common libraries: Box2D (2D), PhysX, Bullet, Jolt (3D).'),
    ('What is a rigid body simulation?','Treats objects as rigid (non-deforming) with mass, velocity, angular velocity. Forces (gravity, applied) → accelerations → integrate to velocity → integrate to position. Constraints (joints, collisions) solved iteratively. Common integrator: semi-implicit Euler (simple, stable enough for games). Verlet for cloth/chain. Box2D and PhysX handle this for you.'),
    ('What is the difference between kinematic and dynamic in physics?','Kinematic body: moves under script control (you set velocity/position), affects others but not affected by physics forces. Use for: player characters (you control), platforms. Dynamic: moves under forces, fully simulated. Use for: debris, ragdolls, projectiles. Static: never moves (walls, ground). Mixing properly is key to performant + sensible game physics.'),
    ('What is interpolation in multiplayer games?','Smoothing between known network states. Server sends position snapshots every N ms; client renders BETWEEN known snapshots (interpolation), not at the latest (delayed slightly). Result: smooth motion despite network jitter. Trade: input feels slightly delayed (~100ms). Extrapolation (predict beyond last known) feels responsive but mispredicts on direction changes. Most games use interpolation for remote players, prediction for local player.'),
]
_RENDERING=[
    ('What is the graphics pipeline?','Vertices → Vertex Shader (per-vertex transforms) → Primitive Assembly (build triangles) → Rasterization (triangles to pixels) → Fragment/Pixel Shader (per-pixel color) → Output Merger (blend with framebuffer). Modern: programmable stages let you customize. APIs: OpenGL, Vulkan, DirectX, Metal, WebGPU.'),
    ('What is a shader?','Small program running on GPU. Vertex shader: transforms vertex positions. Fragment/pixel shader: computes color per pixel. Compute shader: general-purpose GPU work. Languages: GLSL (OpenGL), HLSL (DirectX), MSL (Metal), WGSL (WebGPU). Highly parallel (thousands of pixels at once). Performance: avoid branches, sample textures judiciously, keep simple.'),
    ('What is a UV map?','2D coordinates per vertex telling the renderer where in the texture to sample. UVs in [0,1] range typically. Letters U,V used to avoid conflict with X,Y,Z. UV unwrapping = artist process of laying out 3D model surfaces flat in 2D so texture artists can paint on them. Bad UVs cause stretched textures.'),
    ('What is the depth buffer (z-buffer)?','Per-pixel buffer storing distance from camera. When drawing a pixel: only write if new depth < current. Hides surfaces behind others automatically — no need to sort triangles. Cost: extra memory + bandwidth. Precision issues at large depth ranges (z-fighting) — fix with logarithmic depth or careful near/far planes.'),
    ('What is the difference between forward and deferred rendering?','Forward: shade each fragment as drawn — fast for few lights, naturally handles transparency. Cost grows with lights × pixels. Deferred: write material properties to a G-buffer first, then lighting pass reads back per pixel. Many lights cheap. Transparency requires separate forward pass. Modern engines often use a hybrid (Forward+, clustered forward).'),
]
_OPTIMIZATION_GAME=[
    ('What is the most common cause of slow games?','Too many draw calls — each call has CPU overhead (state changes, validation). Modern GPUs can render millions of triangles per call, but only thousands of calls per frame. Fix: batching (combine many objects into one mesh), instancing (one mesh, many transforms), texture atlasing. Profile with RenderDoc / NSight to see actual culprit.'),
    ('What is level-of-detail (LOD)?','Use simpler meshes for distant objects, full detail up close. Reduces vertex/fragment work. Manual LOD chains (artist-authored) or automated (mesh simplification). Modern: virtualized geometry (Nanite in Unreal 5) handles LOD automatically per-pixel. For large open worlds, LOD is non-negotiable.'),
    ('What is occlusion culling?','Don\'t draw things hidden behind other things. Techniques: frustum culling (skip outside view), backface culling (skip triangles facing away), occlusion queries (GPU asks "is this visible?"). Modern: hierarchical Z-buffer culling, GPU-driven culling. Saves both draw calls + GPU work.'),
    ('What is a frame budget?','Total time per frame at target FPS. 60 FPS = 16.67ms. Subtract: VSync waits, swap, OS overhead → ~12-14ms for your game. Split between CPU (game logic, scripts) and GPU (rendering). Profile each system\'s ms cost. Over budget? Cut graphics quality, reduce particle counts, simplify shaders, batch more aggressively.'),
]
LESSONS=_BASICS+_PHYSICS+_RENDERING+_OPTIMIZATION_GAME
