"""Go corpus — goroutines, channels, interfaces, errors, common idioms."""
_BASICS=[
    ('What is a goroutine?','Lightweight thread managed by Go runtime. Start with `go funcName()`. Costs ~2KB stack initially (grows as needed). Thousands cheap. Scheduler multiplexes goroutines onto OS threads (M:N model). Use for: any concurrent work. Don\'t leak: every goroutine must terminate or be cancellable (context, channel signal).'),
    ('What is a Go channel?','Typed conduit between goroutines. `ch := make(chan int)` unbuffered (sync rendezvous). `make(chan int, 10)` buffered. `ch <- value` sends, `v := <-ch` receives, both block as needed. Close with `close(ch)`. Range over channel: `for v := range ch { ... }` exits when closed. Don\'t send on closed channel (panic); receive from closed returns zero value.'),
    ('What is the Go memory model rule for channels?','"A send on a channel happens before the corresponding receive." Provides synchronization without locks. Buffered channels: send happens before the receive that obtains the value. Closing channel happens before receive returning zero. This means channels carry data AND establish happens-before order — no extra synchronization needed for data passed through.'),
    ('What is a select statement in Go?','Like a switch but for channel ops. Blocks until one case can proceed; picks one randomly if multiple ready. `select { case v := <-ch1: ...; case ch2 <- x: ...; default: ... }`. default makes it non-blocking. Use for: timeout (`case <-time.After(5*time.Second)`), cancellation (`case <-ctx.Done()`), multiplexing channels.'),
    ('What is a Go interface?','Set of method signatures. Types implicitly satisfy interfaces if they have the methods — no `implements` keyword. `type Reader interface { Read([]byte) (int, error) }`. Anything with that method IS a Reader. Powerful: small interfaces compose, mocks easy. The empty interface `interface{}` (or `any` in 1.18+) matches everything — use sparingly.'),
    ('What is the Go error handling pattern?','Return error as last value: `result, err := doSomething()`. Always check: `if err != nil { return ..., err }`. Don\'t use exceptions (panic is for unrecoverable). Wrap to add context: `fmt.Errorf("loading config: %w", err)`. Unwrap with errors.Is(err, sentinel) / errors.As(err, &target). Verbose but explicit — error paths are visible in the code.'),
    ('What is context.Context in Go?','Cancellation + deadline + values passed across API boundaries. Pass as FIRST param: `func DoThing(ctx context.Context, ...)`. ctx.Done() is a channel that closes when cancelled. Functions should select on it for prompt cancellation. context.WithTimeout(parent, 5*time.Second) creates derived ctx. Always cancel() to release resources (defer cancel()).'),
    ('What is the difference between a slice and an array in Go?','Array: fixed-size, value type, `[3]int`. Rare in app code. Slice: dynamic, reference to underlying array, `[]int`. Most common. `make([]int, 5, 10)` = len 5 cap 10. append() may reallocate. Gotcha: slicing keeps reference to underlying array — can prevent GC of big array if you keep tiny slice.'),
    ('How do I handle errors in Go without overwhelming the caller?','(1) Wrap with context: `fmt.Errorf("query users: %w", err)`. (2) Use sentinel errors (var ErrNotFound = errors.New("not found")) + errors.Is for matching. (3) Type assert with errors.As for structured errors. (4) Don\'t log AND return — pick one. Caller decides. (5) For HTTP handlers, convert internal errors to status codes at the boundary; don\'t leak details.'),
    ('What is a defer in Go?','Schedules a call to run when the function returns. `defer file.Close()`. Multiple defers run in LIFO order. Common: close resources, unlock mutex, restore state. Args are evaluated at defer time (gotcha if args mutate). Cost is small but not zero — avoid deferring in tight loops.'),
    ('What is the Go module system?','`go mod init mymodule` creates go.mod. Imports resolve via go.mod + go.sum (hash lockfile). `go get pkg@version` adds dep. `go mod tidy` removes unused, adds missing. Semver versioning. Major version >1 must be in path: `mymodule/v2`. Workspaces (go.work) for multi-module repos.'),
    ('What is a Go struct tag?','Metadata string on struct fields, used by reflection (encoding/json, db drivers, validators). `Name string \\`json:"name" db:"user_name" validate:"required"\\``. Tags parsed by libraries that need extra info. Multiple key:"value" pairs space-separated. Lowercase first letter = unexported (won\'t be serialized by json default).'),
]
_IDIOMS=[
    ('How do I sort a slice in Go?','`sort.Slice(s, func(i, j int) bool { return s[i] < s[j] })` for custom. `sort.Ints`, `sort.Strings`, `sort.Float64s` for primitives. Stable: sort.SliceStable. Custom type implementing sort.Interface (Len, Less, Swap) for repeated use. Sort modifies in place; copy first if you need original.'),
    ('How do I read a file line by line in Go?','`f, _ := os.Open(path); defer f.Close(); scanner := bufio.NewScanner(f); for scanner.Scan() { line := scanner.Text() }`. Default buffer 64KB; for long lines use scanner.Buffer(buf, max). Check scanner.Err() after loop. Or read whole file: `data, _ := os.ReadFile(path)` (Go 1.16+).'),
    ('How do I make an HTTP request in Go?','`resp, err := http.Get(url); defer resp.Body.Close(); body, _ := io.ReadAll(resp.Body)`. For POST: `http.Post(url, contentType, body)`. For custom: create http.Request, use http.Client (with Timeout!). Default client has NO TIMEOUT — always set one. Reuse clients (they pool connections).'),
    ('What is the difference between value and pointer receivers in Go?','`func (u User) Foo()` (value) — operates on copy, can\'t mutate. `func (u *User) Foo()` (pointer) — operates on original, can mutate. Use pointer when: method mutates, struct is large (avoid copy cost), or for consistency. Avoid mixing on the same type — confusing. Interface satisfaction: pointer-receiver methods only satisfy interface for *T, not T.'),
    ('What is iota in Go?','Counter inside const blocks. Resets per const block, increments per line. Used for enum-like constants: `const (Red = iota; Green; Blue)` → 0, 1, 2. With shifts: `const (KB = 1 << (10*(iota+1)); MB; GB)` → 1024, 1048576, 1073741824. Common pattern for bit flags + scaled units.'),
    ('How do I implement a worker pool in Go?','Buffered jobs channel + N goroutines reading from it. `jobs := make(chan Job, 100); for i := 0; i < N; i++ { go worker(jobs, results) }`. Producer sends jobs, close(jobs) when done. Workers exit when range ends. Results channel + sync.WaitGroup for coordinating completion. Avoid one-goroutine-per-task for high-throughput — pool bounds resource use.'),
]
LESSONS=_BASICS+_IDIOMS
