"""JavaScript / TypeScript / React / frontend corpus."""
_JS=[
    ('What is the difference between let, const, and var in JavaScript?','let and const are block-scoped (visible only inside {}), var is function-scoped (visible throughout the function). const cannot be reassigned (but objects bound to const ARE mutable — const x = {} then x.k = 1 is fine). var is hoisted to function top with undefined initial value; let/const are hoisted but in "temporal dead zone" until declaration. Always prefer const, then let, almost never var.'),
    ('How does JavaScript handle === vs ==?','== does type coercion before comparing: "1" == 1 is true, 0 == "" is true, null == undefined is true. === checks type AND value: "1" === 1 is false. ALWAYS use === unless you have a specific reason. Common gotcha: NaN === NaN is false (use Number.isNaN(x)). Object equality is reference-based for both: {} === {} is false.'),
    ('What is a Promise in JavaScript?','Async value placeholder. Three states: pending → fulfilled (with value) or rejected (with error). Consumed via .then(onResolve, onReject) or async/await syntax. Chain with .then(...).then(...) — each returns a new Promise. Errors propagate down chain until .catch() or unhandled rejection. Promise.all waits for all, Promise.race for first, Promise.allSettled gets all results regardless.'),
    ('What is async/await in JavaScript?','Syntactic sugar over Promises. `async function f() { const x = await otherPromise; return x; }` — await pauses until promise settles, returning value or throwing on rejection. async functions ALWAYS return Promises. Inside try/catch works naturally. Common bug: forgetting await — `const x = asyncFn()` gives you a Promise object, not the value. Use `Promise.all` to await multiple in parallel: `const [a,b] = await Promise.all([fA(), fB()])`.'),
    ('What is the event loop in JavaScript?','JS is single-threaded. Event loop runs: pop one callback from microtask queue → run to completion → pop from macrotask queue → repeat. Microtasks (Promise.then) run before next macrotask (setTimeout, I/O). This is why a setTimeout(fn, 0) runs AFTER a Promise.resolve().then(fn) even though timer is 0. Heavy synchronous work blocks the loop — UI freezes, requests pile up.'),
    ('What is hoisting in JavaScript?','Variable and function declarations are conceptually moved to the top of their scope BEFORE code runs. function declarations are fully hoisted (callable before declaration line). var is hoisted but initialized to undefined. let/const are hoisted into "temporal dead zone" — accessing before the declaration line throws ReferenceError. Practical advice: declare before use, don\'t rely on hoisting except for top-level function declarations.'),
    ('How do I deep-copy an object in JavaScript?','Three options: (1) structuredClone(obj) — modern, handles Date, Map, Set, circular refs, but not functions/symbols. (2) JSON.parse(JSON.stringify(obj)) — quick but drops functions, undefined, BigInt, Date becomes string. (3) library like lodash.cloneDeep. Spread `{...obj}` is SHALLOW — nested objects are still shared references.'),
    ('What is a closure in JavaScript?','A function that "remembers" the variables from the scope where it was created, even after that outer scope has returned. Example: `function makeCounter() { let n = 0; return () => ++n; }` — the returned arrow keeps access to `n`. Closures power: factory functions, private state (alternative to classes), event handlers that need outer context, memoization. Memory note: closures hold onto referenced vars; can cause leaks if you forget.'),
    ('What is destructuring in JavaScript?','Concise syntax to extract values: `const {name, age} = user` pulls properties; `const [a, b] = arr` pulls array items. Defaults: `const {name = "anon"} = user`. Rename: `const {name: userName} = user`. Rest: `const {a, ...rest} = obj`. Powerful in function parameters: `function f({x, y = 0}) {...}`. Combine with default function params to build flexible APIs.'),
    ('What is the spread operator vs rest in JavaScript?','Same syntax (`...`), different roles. SPREAD expands an iterable: `Math.max(...arr)`, `{...obj1, ...obj2}`, `[...a, ...b]`. REST collects into an array/object: `function f(...args) {}`, `const [first, ...rest] = arr`. Context determines which: spread in call/literal, rest in parameter/destructuring.'),
    ('How do I handle errors in async code?','Three patterns: (1) try/catch around await — natural, works for any sync-style code. (2) .catch on Promise chains. (3) global handler for unhandled rejections (window.addEventListener("unhandledrejection") in browser, process.on("unhandledRejection") in Node). Avoid swallowing errors silently — log them. AbortController for cancellation: `const ctrl = new AbortController(); fetch(url, {signal: ctrl.signal})` then `ctrl.abort()`.'),
    ('What is the difference between map, filter, and reduce?','All array methods. map(fn) transforms each item, returns new array same length: `[1,2,3].map(x => x*2)` → `[2,4,6]`. filter(fn) keeps items where fn returns truthy, returns smaller array: `[1,2,3,4].filter(x => x > 2)` → `[3,4]`. reduce(fn, init) folds array to single value: `[1,2,3].reduce((acc, x) => acc + x, 0)` → 6. Compose for pipelines: `arr.filter(...).map(...).reduce(...)`.'),
    ('What is event delegation in JavaScript?','Attach ONE listener to a parent element instead of N listeners to N children. Inside, check event.target to find which child triggered. Benefits: works for dynamically added children (no need to re-attach), uses less memory, simpler code. Pattern: `parent.addEventListener("click", e => { if (e.target.matches(".item")) handle(e.target) })`. Especially useful for long lists or container-based UIs.'),
    ('What is the difference between null and undefined?','undefined: variable declared but not assigned, function with no return, missing object property. null: deliberately empty, "no value" intentionally. Best practice: let absent values be undefined naturally; use null only when you specifically want to signal "set to nothing." typeof undefined === "undefined", typeof null === "object" (historical bug). Both falsy. Both == null but only `=== null` matches null specifically.'),
    ('How does this work in JavaScript?','Depends on how function is called, not where defined. (1) Method call obj.f() → this = obj. (2) Plain call f() → this = undefined (strict mode) or window (sloppy). (3) new F() → this = newly constructed object. (4) Arrow function inherits this from enclosing scope — does NOT have its own. (5) f.call(ctx), f.apply(ctx, args), f.bind(ctx) explicitly set this. Class methods unbound from instance lose this; bind in constructor or use arrow class fields.'),
]
_TS=[
    ('What is TypeScript and why use it?','TypeScript = JavaScript + static types. Catches errors at compile time instead of runtime: typos in property names, wrong argument types, missing returns. Modern IDE features (autocomplete, refactor, jump-to-def) are massively better with TS. Cost: build step (tsc or bundler), occasional fights with the type system, learning curve. Worth it for any project >1000 lines.'),
    ('What is the difference between interface and type in TypeScript?','Mostly interchangeable for object shapes. Differences: (1) interface can be DECLARATION-MERGED (multiple `interface Foo {}` in same scope combine); type cannot. (2) type can be ANY type expression (union, intersection, primitive alias), interface only objects/functions. (3) interface error messages tend to be slightly cleaner. Rule of thumb: type for unions/aliases, interface for object shapes that might be extended.'),
    ('What is a generic in TypeScript?','Type parameter that\'s filled in by use site. `function identity<T>(x: T): T { return x }` works for any T, preserves the type. `Array<T>` is parameterized: Array<string> vs Array<number>. Constraints: `function f<T extends Comparable>(x: T)` restricts T. Use generics to avoid losing type info through transformations. Don\'t overuse — sometimes `unknown` + narrowing is simpler.'),
    ('What does the any type mean in TypeScript and why avoid it?','any = "turn off type checking for this." Property access, method calls, assignments — all silently succeed. Defeats the purpose of TypeScript. Use unknown when you genuinely don\'t know the type (forces you to narrow before use). Use object/Record<string, unknown> for arbitrary objects. Enable noImplicitAny in tsconfig to catch accidental any leaks.'),
    ('What is type narrowing in TypeScript?','Process of refining a wide type to a specific one based on runtime checks. typeof guard: `if (typeof x === "string") { /* x: string here */ }`. instanceof guard: `if (x instanceof Error)`. in guard: `if ("prop" in obj)`. Discriminated union: `if (shape.kind === "circle")`. Custom predicate: `function isUser(x): x is User { return ... }`. The compiler tracks the narrowed type through control flow automatically.'),
    ('What is satisfies in TypeScript?','`expr satisfies Type` checks that expr matches Type without WIDENING expr to Type. Difference from `expr as Type` (assertion, dangerous, no check) and `const x: Type = expr` (annotation, widens). Use case: `const config = {...} satisfies Config` — you get autocomplete on config\'s actual shape, but compile-time guarantee it matches Config. Added in TS 4.9, very useful.'),
    ('What is the difference between strict and loose mode in TypeScript?','"strict": true in tsconfig turns on a bundle of flags: noImplicitAny, strictNullChecks (null/undefined are not assignable to other types unless explicit), strictFunctionTypes, strictBindCallApply, alwaysStrict. New projects: always strict. Existing JS migration: turn on incrementally, fix errors per flag. Without strict, TS is barely better than JSDoc.'),
]
_REACT=[
    ('What are React hooks?','Functions starting with `use` that let function components have state and side effects. useState (state), useEffect (after-render side effects), useRef (mutable container, not state), useMemo (cached computation), useCallback (cached function), useContext (consume Context). Replaces class components for most use cases. Rules: only call at top level (not in loops/conditions), only from React components or other hooks.'),
    ('What is useState and common mistakes?','`const [count, setCount] = useState(0)` — count is the value, setCount updates and triggers re-render. Mistakes: (1) reading immediately after set — state doesn\'t update mid-function, only on re-render. (2) directly mutating state (setItems.push doesn\'t trigger re-render; use setItems([...items, new])). (3) setting based on stale state — use functional form `setCount(c => c+1)` for updates dependent on previous value.'),
    ('What is useEffect and when does it run?','Side effects after render: data fetching, subscriptions, DOM manipulation. `useEffect(fn, deps)` — fn runs after every render where any dep changed (deep equality NOT used, reference). Empty array `[]` = run only after first render (mount). No array = run after every render (usually wrong). Cleanup: return a function; it runs before next effect or on unmount. Pitfall: missing deps cause stale closures; React linter warns.'),
    ('What is the difference between useMemo and useCallback?','Both memoize across renders based on deps array. useMemo caches a VALUE (result of a function call). useCallback caches a FUNCTION (the reference). useCallback(fn, deps) is equivalent to useMemo(() => fn, deps). Use useCallback when passing a function to a memoized child component, to prevent unnecessary re-renders. Don\'t memoize everything — the memoization itself costs memory and comparison time.'),
    ('What is React state lifting?','When two sibling components need to share state, move the state UP to their nearest common parent. Parent owns state + handlers, passes data down via props and updaters down via callback props. The pattern enforces a single source of truth. Alternative for deep trees: Context API (avoid prop drilling) or external state library (Redux, Zustand) when state is truly global.'),
    ('What is a key prop in React lists and why does it matter?','When rendering an array of components, React needs to know which DOM nodes correspond to which array items across re-renders, so it can update the right ones. Without keys, it falls back to index-based matching → wrong items animate, lose focus, etc. Use a STABLE id from the data, not array index. Anti-pattern: `key={index}` for lists that reorder/insert/delete.'),
    ('When should I use Context vs Redux vs Zustand?','Context: tiny shared state (theme, current user, locale). Renders all consumers on any change — DON\'T use for frequently-updating state. Redux: large app with complex state mutations, time-travel debugging, middleware ecosystem. Heavy boilerplate (RTK helps). Zustand: middle ground — simple API, hooks-based, no providers, scales surprisingly well. For new projects: Zustand or Jotai. Reserve Redux for big-team / legacy.'),
    ('What is React.memo and when use it?','Higher-order component that skips re-render if props are shallow-equal to previous. `const Memo = React.memo(MyComp)`. Only helps if (1) parent re-renders often AND (2) MyComp\'s render is expensive. Won\'t help if you pass new objects/functions as props each render — they\'re always !== previous. Pair with useMemo/useCallback for stable references. Don\'t wrap everything — the comparison itself isn\'t free.'),
    ('What is JSX really?','Syntactic sugar that compiles to function calls. `<div className="x">hi</div>` becomes `React.createElement("div", {className: "x"}, "hi")`. Children are positional args after the props object. Modern compiles use the JSX transform: `_jsx("div", {className: "x", children: "hi"})`. This is why you "use Object" naming (className not class, htmlFor not for) — these are JS object keys.'),
    ('What is a controlled vs uncontrolled component in React?','Controlled: React holds the form value in state and sets it via prop (value={state} + onChange={setState}). React is source of truth. Uncontrolled: DOM holds the value, React reads via ref when needed. Controlled enables: validation, conditional submit, conditional fields. Uncontrolled simpler for one-off forms. File inputs MUST be uncontrolled (browser security).'),
]
_NODE=[
    ('What is npm vs yarn vs pnpm?','npm: built-in with Node, slow installs. yarn (v1 classic): faster, deterministic via yarn.lock. yarn berry (v2+): PnP (no node_modules), big paradigm shift. pnpm: hardlinks shared deps to one global store — fast, low disk use, strict (catches phantom-deps). Modern choice: pnpm for most. npm has caught up significantly with v9+ workspaces support.'),
    ('What is package-lock.json and should I commit it?','Records the EXACT version of every dep + transitive dep installed. Commit it: ensures reproducible installs across environments + CI. Without lockfile, `npm install` re-resolves semver ranges and may pull different versions, breaking the "works on my machine" rule. Don\'t edit by hand. Delete + re-install if it gets corrupted.'),
    ('How do I handle environment variables in Node?','Use process.env.MY_VAR. For development, load from .env file via `dotenv` library: `require("dotenv").config()` at app entry. Never commit .env (add to .gitignore); commit .env.example with placeholder values. In production, set env vars via deploy platform (Docker -e, k8s ConfigMap, hosting UI). Validate required vars at startup — fail fast, not deep in a code path.'),
    ('What is the difference between require and import in Node?','require (CommonJS): runtime, dynamic, sync. import (ESM): static, hoisted, supports tree-shaking. Modern Node supports both via "type": "module" in package.json (then files are ESM by default) or .mjs / .cjs extensions. Mixing causes pain: ESM can import CJS, CJS can\'t require ESM directly (use dynamic `await import()`). New projects: ESM. Migrate legacy gradually.'),
    ('What is the EventEmitter pattern in Node?','Object with on(event, listener) to subscribe and emit(event, ...args) to dispatch. Listeners run synchronously in registration order. Used by many built-in Node modules (streams, http, process). Wrap in `once` to auto-remove after first fire. Watch out for: memory leaks if you forget to .off(), errors thrown in listeners crash the process unless caught.'),
]
_BROWSER=[
    ('What is the DOM?','Document Object Model. Tree representation of the HTML page in memory. Each tag becomes a Node; text becomes a Text node. document.querySelector / .getElementById to find nodes; .appendChild / .innerHTML to mutate; .addEventListener for events. Modifying the DOM is expensive — batch updates, prefer documentFragment for many inserts, or use a framework that diffs (React) or compiles away (Svelte).'),
    ('What are CSS selectors and specificity?','Specificity = (inline, id, class, element) tuple compared left-to-right. Inline beats id beats class beats element. `#foo .bar` is (0,1,1,0), `body .bar` is (0,0,1,1) — id version wins. Same specificity → later rule wins. !important overrides specificity (use sparingly). To debug: browser devtools shows computed styles + which rule won. Specificity wars are usually a sign you need to refactor.'),
    ('What is the CSS box model?','Every element is a box with content, padding, border, margin. Width = content width by default (`box-sizing: content-box`); padding+border ADD to total. With `box-sizing: border-box` (modern default in resets), width INCLUDES padding+border — much more intuitive. Margin can collapse vertically between adjacent siblings (the larger wins, not the sum).'),
    ('What is flexbox vs grid?','Flexbox: 1D layout — items in a row OR column. Best for: nav bars, button rows, centering, equal-height cards. Properties on container: flex-direction, justify-content, align-items, gap. Grid: 2D layout — rows AND columns simultaneously. Best for: page templates, dashboards. grid-template-columns/rows define structure. Use both: grid for page-level, flex for component-level. Modern CSS, both widely supported.'),
    ('What is a CSS preprocessor and do I need one?','Compile-time CSS extensions: SCSS/Sass, Less. Add variables, nesting, mixins, imports. Less critical now because modern CSS has native variables (--my-color) and @import. Tailwind/styled-components/CSS-in-JS often replace them entirely. Use SCSS if your codebase already uses it; new projects often skip in favor of vanilla CSS + maybe PostCSS.'),
    ('What is a single-page app vs server-rendered app?','SPA: server sends one HTML shell, JS fetches data and renders all pages client-side (React, Vue, Angular). Pro: smooth navigation. Con: slow first paint, SEO challenges, big JS bundles. SSR: server renders full HTML per request (Next.js, Remix, Rails). Pro: fast first paint, SEO works, less JS. Con: server complexity. Modern hybrid (Next.js, Astro, Nuxt) does SSR for first render + hydration for interactivity.'),
]
LESSONS=_JS+_TS+_REACT+_NODE+_BROWSER
