"""Harder leetcode patterns + advanced graph/DP/string problems with worked solutions."""
_DP_HARD=[
    ('What is the longest palindromic substring approach?','Expand around center. For each i: expand outward checking palindrome (odd length centered at i, even length centered at i,i+1). Track max. O(n²) time O(1) space. Manacher\'s algorithm: O(n) by reusing computed palindrome lengths via mirror property. Most candidates do expand-around-center; Manacher\'s if you really need O(n).'),
    ('What is the regular expression matching DP?','Match string s with pattern p (containing . and *). dp[i][j] = does s[0..i] match p[0..j]. Cases: if p[j-1] == \'.\' or p[j-1] == s[i-1]: dp[i][j] = dp[i-1][j-1]. If p[j-1] == \'*\': two subcases (zero occurrences: dp[i][j-2]; one or more if char before * matches s[i-1]: dp[i-1][j]). O(mn). Hard part is the * handling.'),
    ('What is the word break DP problem?','Given string s and dict, can s be split into dict words? dp[i] = can s[0..i] be split. dp[0] = true. dp[i] = any j<i where dp[j] AND s[j..i] in dict. O(n² * max_word_len) using set for dict. Variant: return all possible splittings (backtracking, exponential in worst case).'),
    ('What is the partition equal subset sum DP?','Can array be split into two subsets with equal sum? Total sum must be even; target = sum/2. Becomes: subset summing to target? dp[i][s] = can we make sum s using first i items. dp[i][s] = dp[i-1][s] OR dp[i-1][s-a[i]]. O(n*target). Space-optimize to 1D, iterate s backward.'),
    ('What is the longest increasing path in matrix?','In grid where you can move to adjacent cells with strictly greater value, find longest path. DFS from each cell with memoization: dp[i][j] = 1 + max(dp of valid neighbors). Each cell computed once. O(m*n). Classic DP on graph problem.'),
]
_GRAPH_HARD=[
    ('What is the network delay time problem?','Single-source shortest path. Times[i] = (u,v,w) means edge u→v of weight w. Find time for signal from node K to reach all nodes (or -1 if impossible). Dijkstra from K, return max distance (or -1 if any node unreachable). O((V+E)logV) with heap. Standard Dijkstra application.'),
    ('What is the cheapest flights with K stops problem?','Find cheapest flight from src to dst with at most K stops. NOT plain Dijkstra (allowing more stops can be cheaper). Use BFS layered by stops, OR modified Dijkstra tracking (node, stops_so_far) state. Bellman-Ford limited to K+1 iterations also works. O(K * E).'),
    ('How do I find articulation points (cut vertices) in a graph?','Vertices whose removal disconnects the graph. DFS computing disc[v] (discovery time) + low[v] (lowest disc reachable). v is articulation if: (1) v is DFS root with 2+ children, OR (2) v has child c with low[c] >= disc[v]. O(V+E). Bridges (cut edges) similar: edge u-v is bridge if low[v] > disc[u].'),
    ('What is Tarjan\'s algorithm for SCC?','Strongly connected components in directed graph. DFS with stack. Each node has disc + low (similar to articulation). When low[v]==disc[v], v is root of an SCC; pop stack down to v. O(V+E). Single pass, no re-DFS (Kosaraju needs two). For practical use, prefer Tarjan or use library.'),
    ('How do I find shortest path in unweighted graph?','BFS from source. Distance = level number when first visiting. Parent tracking gives path. O(V+E). For multi-source: push all sources into queue with dist 0. For bidirectional search: BFS from both ends, meet in middle (sqrt speedup).'),
]
_HEAP_PROBLEMS=[
    ('What is the merge K sorted lists problem?','Min-heap of (value, list_idx, node). Pop min, push next from that list. O(N log K) where N=total nodes. Better than naive merge-pairwise O(NK). Python heapq with tuples sorts lexicographically — break ties on index. Used in: external sort, log aggregation, top-K from streams.'),
    ('What is the running median problem?','Maintain median as numbers stream in. Two heaps: max-heap of lower half, min-heap of upper half. Keep sizes balanced (differ by ≤1). Median = top of larger (odd total) or avg of tops (even). O(log n) per insert. Classic interview problem. Variant: median over sliding window of last K.'),
    ('What is top K frequent elements?','Count frequencies (Counter). Heap of size K maintains top K by freq. For each item, push; if size > K, pop smallest. O(n log K). Or: bucket sort by freq (each freq is a bucket), iterate freq descending, collect K. O(n).'),
    ('What is the find median from data stream problem?','Same as running median. Two heaps. addNum + findMedian both O(log n). Beware: Python heapq is min-heap; for max-heap negate values on push, negate on pop. Or use library sortedcontainers.SortedList for O(log n) all ops + O(1) median.'),
]
_TREE_PROBLEMS=[
    ('How do I serialize and deserialize a binary tree?','BFS with placeholders for null: "1,2,3,null,null,4,5". Or pre-order DFS recording each null as "#". Deserialize: parse + reconstruct via the same traversal. Either works; pick one and be consistent. Variant: serialize BST (no nulls needed if sortable).'),
    ('How do I find the lowest common ancestor (LCA) of two nodes in a binary tree?','Recursive: if root is null or matches p or q, return root. Recurse left, right. If both return non-null, root is LCA. If only one, return it. O(n). For BST: O(log n) using BST property (LCA is first node between p and q in value).'),
    ('What is the maximum path sum in binary tree problem?','Path can start and end anywhere. Recurse: at each node, max contribution from one side = max(0, max(left_contrib, right_contrib)) + node.val. Best path going THROUGH node = node.val + left_contrib + right_contrib. Track global max. Return the one-side contribution to parent. O(n).'),
    ('How do I check if a binary tree is balanced?','Bottom-up: compute height + balance check together. Return -1 if unbalanced (early exit). For each node: get heights of children; if either returned -1 or abs diff > 1, return -1; else return max+1. O(n). Beats top-down O(n²) (which recomputes heights).'),
    ('How do I find all paths from root to leaves with target sum?','DFS with current path + remaining target. At leaf: if remaining == 0, record path (copy!). Recurse left + right with target - node.val. Backtrack (pop from path after recursing). O(n) for sum traversal; O(n*depth) if collecting paths.'),
]
_BIT=[
    ('What is the single number problem (XOR trick)?','Array where every element appears twice except one. Find the loner. XOR all elements: pairs cancel (a^a=0), remaining = the loner. O(n) time O(1) space. Beautiful application of XOR properties.'),
    ('How do I count set bits in an integer?','Brian Kernighan\'s: while n: n &= n-1; count++. Each iter clears the lowest set bit. O(set_bits) iterations. Python: bin(n).count("1"). Hardware: POPCNT instruction does it in one op on modern CPUs.'),
    ('What is the missing number from 0..n problem?','Sum 0..n = n*(n+1)/2. Subtract sum of array. Diff = missing. O(n). Or XOR all values 0..n with all array values: pairs cancel, missing remains. Same complexity, no overflow risk.'),
    ('How do I check if a number is a power of two?','n > 0 AND (n & (n-1)) == 0. Powers of 2 have exactly one bit set; n-1 has all lower bits set; AND gives 0. O(1). Generalization: count_set_bits(n) == 1.'),
]
LESSONS=_DP_HARD+_GRAPH_HARD+_HEAP_PROBLEMS+_TREE_PROBLEMS+_BIT
