"""Leetcode-pattern problems with worked solutions — sliding window, two-pointer, monotonic stack, binary search variants, backtracking."""
_SLIDING=[
    ('What is the sliding window pattern?','Two pointers (L, R) bound a window into an array/string. Expand R adding new element; contract L when window violates a constraint. Track max/min/sum/count as window slides. O(n) — each element enters once, leaves once. Use for: longest/shortest contiguous substring/subarray with property, max-sum-of-k-elements, max-of-each-window.'),
    ('Min window substring — sliding window solution?','Find smallest substring of s containing all chars of t. Use char count dict for t. Expand R adding s[R] to window counts. When window contains all needed chars, contract L while still valid, tracking min window. O(|s| + |t|). Classic hard; the contract phase is where most bugs happen — be careful with chars in window but not in t (cap at needed count).'),
    ('Longest substring with at most K distinct characters?','Sliding window. Hash map of char → count in window. Expand R, add s[R]. While map has >K keys, contract L removing s[L], deleting key when count hits 0. Track max(R-L+1). O(n). The "at most K" trick is powerful — also solves "longest with exactly K" via (atMost(K) - atMost(K-1)).'),
    ('Max sum of subarray of size k?','Sliding window of fixed size k. Compute first window sum. Slide: add new right element, subtract old left element. Track max. O(n). Generalizes to "find k-window with max product / mean / median" (last needs sorted multiset).'),
]
_TWO_POINTER=[
    ('What is the two-pointer pattern?','Two indices traverse the array, often from opposite ends or at different speeds. Use for: sorted-array problems, palindrome check, container-with-most-water, removing duplicates in place, partitioning. Each pointer moves O(n) total → O(n) algorithm.'),
    ('Container with most water — two-pointer solution?','Given heights, find pair giving max area = (j-i) * min(h[i], h[j]). Start i=0, j=n-1. Area = width * min height. Move the SHORTER one inward — moving the taller can only reduce width AND not increase min height. Track max. O(n).'),
    ('Three sum (find all triplets summing to zero)?','Sort array O(n log n). For each i: two-pointer (L=i+1, R=n-1) for pair summing to -a[i]. Skip duplicates at i, L, R. O(n²). Sorting is the unlock — converts triple-loop O(n³) brute force.'),
    ('Remove duplicates in place from sorted array?','Slow pointer for write position (starts at 0). Fast pointer for read. If a[fast] != a[slow], slow++, a[slow] = a[fast]. Return slow+1 as new length. O(n) time, O(1) space.'),
]
_MONOTONIC=[
    ('What is a monotonic stack?','Stack maintained in non-decreasing or non-increasing order. As you push, pop everything that breaks the order. Use for: "next greater element," "largest rectangle in histogram," "trapping rain water." Each element pushed + popped once → O(n) overall, even though loop looks nested.'),
    ('Next greater element — monotonic stack solution?','For each element, find next-to-the-right that is greater. Iterate from right to left, monotonic decreasing stack. For each i: pop while top ≤ a[i] (they\'re shorter than current, can\'t be NGE for anything to left). If stack non-empty, NGE[i] = top. Push a[i]. O(n).'),
    ('Largest rectangle in histogram?','For each bar, find the largest rectangle that uses this bar as the SHORTEST. Need leftmost/rightmost index where height < current. Monotonic increasing stack: when popping, top is "shortest" of a rectangle bounded by current and second-from-top. O(n). Classic hard — pairs well with "max rectangle in binary matrix" (apply histogram trick per row).'),
    ('Trapping rain water?','Each position traps min(maxLeft, maxRight) - height[i] water. Precompute maxLeft + maxRight arrays: O(n) time, O(n) space. Better: two-pointer L+R + track leftMax + rightMax → O(1) extra space. Move the pointer with smaller wall — that wall bounds the water at its position.'),
]
_BS_VARIANTS=[
    ('Binary search lower bound vs upper bound?','Lower bound: first index ≥ target (or first index of target if exists). Upper bound: first index > target. Both implementable as binary search with subtle condition tweaks. Python: bisect.bisect_left/bisect_right. C++: lower_bound/upper_bound. Use lower_bound for "insert position" + "first equal." Count of X in sorted = upper - lower.'),
    ('Find peak element in array?','Peak = greater than both neighbors. Binary search: if a[mid] < a[mid+1], peak is to the right (because going up). Else peak is at mid or to left. O(log n). Works even with no ordering — exploits that boundaries are -inf, so a peak must exist.'),
    ('Binary search on answer pattern — when to use?','When you can EFFICIENTLY check "is K a valid answer?" + answer space is monotonic (if K works, K+1 also works — or vice versa). Binary search the answer range. Examples: minimum capacity to ship in D days, min eating speed Koko, split array minimum largest sum. The "predicate" is the check function; you binary-search where it flips.'),
    ('Find minimum in rotated sorted array?','Binary search. If a[mid] > a[right], min is in right half (low = mid+1). Else min is at mid or left (high = mid). Loop ends with low = high = index of min. O(log n). With duplicates allowed: worst-case degrades to O(n) because a[mid]==a[right] gives no info.'),
]
_BACKTRACKING=[
    ('What is backtracking?','Recursive exploration of choices, undoing each choice when a branch fails or ends. Template: `def backtrack(state): if done: record; return; for choice in choices: state.add(choice); backtrack(state); state.undo(choice)`. Use for: combinatorial generation (permutations, subsets, combinations), constraint satisfaction (N-queens, sudoku), pathfinding in a graph.'),
    ('Generate all subsets (power set) of a list?','Backtracking. State = current subset. Choices at index i = include a[i] OR skip. Recurse. Time O(n * 2^n). Iterative alternative: start with [[]]; for each x, double the list by adding x to each existing subset. Bitmask: iterate 0..2^n-1, include element i if bit i set.'),
    ('Generate all valid parentheses combinations?','Backtracking with two counters: open used, close used. At each step, choose ( if open<n, choose ) if close<open. Stop at length 2n. O(catalan number) ≈ 4^n / n^1.5. Pruning via open<n and close<open prevents invalid branches early.'),
    ('Sudoku solver?','Backtracking. Find empty cell → try digits 1-9 → check row/col/box validity → recurse → undo on failure. Optimizations: pick empty cell with fewest valid digits first (MRV heuristic), maintain row/col/box bitmasks for O(1) check. Avg solve <10ms for hard puzzles. The basis of many constraint solvers.'),
]
LESSONS=_SLIDING+_TWO_POINTER+_MONOTONIC+_BS_VARIANTS+_BACKTRACKING
