"""Less-common languages — Ruby, Erlang, Lua, Bash deep, Zig, Crystal."""
_RUBY=[
    ('What is Ruby?','Dynamic OO language, designer-focused on developer joy. Famous for: Rails web framework (revolutionized web dev 2005+), elegant syntax, "everything is an object." Pros: highly readable, productive for web. Cons: slower than compiled langs, GIL like Python. Use for: web (Rails), automation, internal tools. JRuby + TruffleRuby for perf.'),
    ('What is Ruby on Rails?','Full-stack web framework. Convention over configuration — sensible defaults reduce boilerplate. MVC architecture. ActiveRecord ORM. Migrations, sessions, routing, asset pipeline built in. Pioneered many web patterns now standard. Best for: CRUD apps, MVPs, content sites. Less ideal for: real-time, microservices, ultra-high-throughput.'),
    ('What is a block in Ruby?','Anonymous chunk of code passed to a method. `[1,2,3].each { |x| puts x }`. Blocks are not first-class (use Proc or lambda for that). do/end for multi-line. Most idiomatic Ruby is full of blocks (each, map, select, reduce). Yield keyword in method definition invokes the block.'),
    ('What is duck typing in Ruby?','If it walks like a duck and quacks like a duck, treat it as a duck. Ruby checks for the METHOD when called, not the class. `def feed(x); x.eat; end` works with any object responding to .eat. Powerful for polymorphism without interfaces; trade-off: errors only at runtime. Combined with method_missing for very dynamic patterns.'),
    ('What is a Ruby gem?','Packaged Ruby library. Installed via `gem install xxx` or via Bundler (Gemfile + Gemfile.lock for project deps). Equivalent to npm packages, Python packages. RubyGems.org is the registry. Bundler-managed projects pin versions for reproducibility.'),
]
_ERLANG_ELIXIR=[
    ('What is Erlang and the BEAM VM?','Functional language designed for telephony — fault tolerance + concurrency primary goals. BEAM VM: runs lightweight processes (millions per node), message passing only (no shared state), preemptive scheduling, hot code reload. Supervisor trees restart crashed processes. Powers: WhatsApp (handled millions of users with tiny team), Discord backend, telecom systems.'),
    ('What is the OTP framework?','Open Telecom Platform — Erlang stdlib of behaviors and patterns. GenServer (generic server: handle_call/cast/info), Supervisor (restart strategies), Application (lifecycle). Battle-tested over decades. Elixir inherits OTP — Phoenix is built on top.'),
    ('What is "let it crash" philosophy?','Erlang/Elixir approach: don\'t defensively code for every edge case. Let processes crash; supervisor restarts them. Combined with isolation (no shared state), a crash doesn\'t corrupt others. Simpler code, more robust systems. Opposite of typical Java/Python defensive style.'),
    ('What is a Phoenix LiveView?','Elixir framework for real-time UIs without writing JavaScript. Server holds state per session, sends DOM diffs over WebSocket on state changes. Client just renders + sends events. Massive productivity for collaborative/realtime features. Tradeoff: server-side state requires sticky sessions; not ideal for offline-first.'),
]
_LUA=[
    ('What is Lua?','Lightweight embeddable scripting language. Tiny implementation (~200KB), fast, simple syntax. Primary use: game scripting (World of Warcraft, Roblox, Garry\'s Mod, many engines), nginx (OpenResty), Neovim plugins. Dynamic typing. First-class functions, tables (the only data structure — both arrays AND hash maps). Easy to embed in C/C++.'),
    ('What is LuaJIT?','JIT-compiled Lua implementation. 10-100x faster than reference Lua. Used in production: OpenResty (nginx), Tarantool DB, Cloudflare Workers (earlier). FFI for calling C without bindings. Combined with Lua\'s simplicity, surprisingly fast for high-throughput workloads.'),
]
_BASH=[
    ('What is the difference between $@ and $* in bash?','$@ = all args as separate strings (preserves quoting in `"$@"`). $* = all args as one string with separator. Always prefer `"$@"` (quoted) when forwarding args to another command — preserves each arg with spaces intact. Subtle but important for shell scripting.'),
    ('What is set -euo pipefail in bash?','Strict mode flags. -e: exit on any unhandled error. -u: treat unset variables as error. -o pipefail: pipe fails if ANY command in chain fails (default is only last). Together: catch bugs early. Standard preamble for serious shell scripts. Add IFS=$\'\\n\\t\' to safely handle filenames with spaces.'),
    ('What is parameter expansion in bash?','${var:-default} (use default if unset), ${var:+value} (use value if set), ${var:?msg} (error if unset), ${var#pattern} (strip prefix), ${var%pattern} (strip suffix), ${var/pattern/replacement} (substring replace). Lets you avoid spawning sed/awk for many cases. Faster + portable.'),
    ('What is process substitution in bash?','<(cmd) creates a temp file (or fifo) with cmd\'s output, usable as a filename. `diff <(sort a.txt) <(sort b.txt)`. >(cmd) the reverse (write to cmd\'s stdin). Lets you pass program output to programs that only accept file arguments. POSIX shell doesn\'t support; bash + zsh do.'),
    ('What is the difference between [ ] and [[ ]] in bash?','[ ] = POSIX test command (also written as `test`). [[ ]] = bash-only extended test. [[ ]] supports: && / || / ! without quoting issues, =~ regex matching, < / > for string comparison without escape. Always prefer [[ ]] in bash scripts. Use [ ] only for POSIX-portable sh scripts.'),
]
_NEWER=[
    ('What is Zig?','New systems language. Manual memory management, no hidden control flow, no hidden allocations, compile-time code execution, C interop excellent (can use C headers directly). Aims to be a better C. Currently used: tigerbeetle (financial DB), Bun (JS runtime). Pre-1.0; smaller community than Rust but growing.'),
    ('What is Crystal?','Ruby-like syntax, statically typed, compiled to native. Type inference reduces annotations. Fast (close to C performance). Best for: web (Kemal, Lucky), CLI tools, anything wanting Ruby ergonomics without runtime cost. Smaller ecosystem than Ruby. Pre-1.0 for years but mature for many use cases.'),
    ('What is V (vlang)?','New language inspired by Go + Rust simplicity. Fast compilation, no runtime, optional GC. C interop. Pros: simple syntax. Concerns: some marketing claims have been controversial; community smaller. Worth watching but Rust + Go + Zig more established.'),
    ('What is Nim?','Python-like syntax, statically typed, compiled to C. Macros powerful (compile-time code generation). Manual or GC memory mgmt. Pros: very expressive, fast. Cons: smaller community than Rust/Go. Best for: anyone wanting Python ergonomics + native perf.'),
]
LESSONS=_RUBY+_ERLANG_ELIXIR+_LUA+_BASH+_NEWER
