"""Advanced math + algorithm topics — geometry, number theory, calculus, linear algebra."""
_GEOMETRY=[
    ('How do I check if a point is inside a polygon?','Ray casting: shoot a ray from point in any direction; count edges it crosses. Odd → inside, even → outside. Handle edge cases (point on edge, ray hits vertex exactly). O(n) per query for n-vertex polygon. For many queries on same polygon: preprocess (point-in-polygon via spatial structure or polygon decomposition).'),
    ('How do I compute the area of a polygon?','Shoelace formula: 0.5 * |sum of (x_i * y_{i+1} - x_{i+1} * y_i)| over all vertices. Wrap last back to first. O(n). Sign before abs indicates winding (positive = counterclockwise, negative = clockwise). For convex polygons: split into triangles from one vertex, sum triangle areas.'),
    ('What is the convex hull and how to compute?','Smallest convex polygon containing all points. Algorithms: gift wrapping O(nh), Graham scan O(n log n), Andrew\'s monotone chain O(n log n) — simpler to implement than Graham. Use for: closest pair, diameter, minimum bounding rectangle, collision detection. The "rubber band around a set of pins" intuition.'),
    ('How do I check if two line segments intersect?','Use orientation: compute orientation of three points (clockwise, counterclockwise, collinear) via cross product. Segments AB and CD intersect if A and B are on opposite sides of CD AND C and D are on opposite sides of AB. Handle collinear case separately. Avoids dividing (no float drift) — pure cross-product comparison.'),
    ('What is the distance from a point to a line segment?','Project point P onto infinite line through A,B. If projection falls within [A,B], distance = perpendicular distance. If beyond A: distance = |P-A|. Beyond B: distance = |P-B|. Formula: t = ((P-A)·(B-A)) / |B-A|² ; clamp t to [0,1]; closest point = A + t*(B-A); distance = |P - closest|.'),
]
_NUMBER_THEORY=[
    ('How do I compute GCD efficiently?','Euclidean algorithm: gcd(a, b) = gcd(b, a mod b). Base case gcd(a, 0) = a. O(log(min(a,b))). One-liner Python: `def gcd(a,b): return a if b==0 else gcd(b, a%b)`. Or use math.gcd builtin. LCM derived: lcm(a,b) = a*b // gcd(a,b) (careful with overflow).'),
    ('What is modular arithmetic?','Arithmetic where numbers wrap at modulus m. (a+b) mod m, (a*b) mod m. Useful for: avoiding overflow in algorithms (sum mod 1e9+7 in competitive programming), cryptography, hashing. Modular inverse: a*x ≡ 1 (mod m) — exists iff gcd(a, m) = 1, found via Extended Euclidean or Fermat\'s little theorem if m prime.'),
    ('How do I check if a number is prime efficiently?','Trial division up to sqrt(n): O(sqrt(n)) — fine for n < 10^12 ish. For huge n: Miller-Rabin probabilistic test (very fast, deterministic with fixed witnesses for n < 3*10^18). Sieve of Eratosthenes to find ALL primes up to n: O(n log log n). For RSA-scale (2048-bit): Miller-Rabin + AKS for proof.'),
    ('What is the sieve of Eratosthenes?','Find all primes up to N. Start with array [2..N] all true. For each i from 2: if i still true, mark all multiples i*i, i*i+i, ... as false. Remaining trues are primes. O(N log log N) time, O(N) space. Variations: segmented sieve for huge N, Linear sieve for finding smallest prime factor of each number.'),
    ('What is modular exponentiation and why use it?','Compute (base^exp) mod m efficiently. Naive base^exp overflows. Fast exponentiation: square repeatedly, multiply when bit of exp is 1. O(log exp). Python builtin: `pow(base, exp, mod)`. Foundation of RSA, Diffie-Hellman. Without it, modern crypto would be unusable.'),
]
_LINEAR_ALG=[
    ('What is a dot product?','Scalar from two vectors: sum of element-wise products. `a · b = sum(a_i * b_i)`. Geometric: `|a| * |b| * cos(angle)`. Uses: angle between vectors (a·b / (|a||b|) = cos θ), projection (a onto b = (a·b)/|b|² * b), check orthogonality (dot = 0), neural network forward pass (weights · inputs).'),
    ('What is a cross product?','Vector perpendicular to two 3D input vectors. `a × b = (a_y*b_z - a_z*b_y, a_z*b_x - a_x*b_z, a_x*b_y - a_y*b_x)`. Magnitude = area of parallelogram spanned. Direction by right-hand rule. Uses: normal vector for triangle (for lighting, collision), torque, angular momentum. Only defined in 3D (and 7D, but you don\'t care).'),
    ('What is a matrix transpose?','Flip rows ↔ columns: A^T[i][j] = A[j][i]. (A^T)^T = A. (AB)^T = B^T A^T. Important for: solving systems (normal equation A^T A x = A^T b), neural network backprop (gradients), changing between row/column vector conventions. Cache-unfriendly if done naively for big matrices (use blocked algorithm).'),
    ('What is matrix multiplication?','C = A*B where C[i][j] = sum over k of A[i][k] * B[k][j]. Dimensions: A is mxn, B is nxp → C is mxp. NOT commutative (AB ≠ BA generally). Compositional: applying B then A to vector v = (AB)v. Underlies: rotations, projections, neural network layers. Use numpy/BLAS in practice — never roll your own for performance.'),
    ('What is matrix inverse and when use it?','A^-1 satisfies A * A^-1 = I (identity). Exists only for SQUARE non-singular matrices. Use for: solving Ax = b → x = A^-1 b (but better: solve via LU/QR decomposition, more stable). Computing inverse explicitly is rare — usually you want to SOLVE a system, not get the inverse matrix. For least squares: use pseudoinverse or QR.'),
    ('What is an eigenvalue and eigenvector?','For matrix A: v ≠ 0 is an eigenvector with eigenvalue λ if Av = λv. Means: matrix\'s action on v is just scaling. Uses: PCA (eigenvectors of covariance = principal components), PageRank, vibrating mode analysis, quantum mechanics (observable + state). Algorithms: power iteration (largest), QR algorithm (all), Lanczos (sparse).'),
]
_CALCULUS=[
    ('What is a derivative in plain English?','Instantaneous rate of change of a function. df/dx at point x = slope of tangent line at x. Computed via rules (power, chain, product, quotient) or numerically (finite differences). Critical for: optimization (find max/min where derivative = 0), physics (velocity = d-position/dt), ML (gradient descent uses derivatives of loss).'),
    ('What is the chain rule?','Derivative of composite function: (f(g(x)))\' = f\'(g(x)) * g\'(x). Multiplies derivatives along the chain. Foundation of backpropagation in neural networks — gradient through composed layers = product of per-layer Jacobians. Generalizes to multivariate: each variable\'s derivative gets the product of sensitivities along its path.'),
    ('What is integration in plain English?','Area under a curve between two points. Reverse of differentiation: F\'(x) = f(x), so integral of f from a to b = F(b) - F(a). Computed: symbolic (look up rules), numeric (trapezoidal, Simpson, Monte Carlo). Uses: physics (work = integral of force, distance = integral of velocity), probability (cumulative from density), volume/surface computations.'),
    ('What is a gradient?','For scalar function f(x1, x2, ...): vector of partial derivatives [∂f/∂x1, ∂f/∂x2, ...]. Points in direction of steepest increase. Magnitude = rate of increase in that direction. Used in: gradient descent (step opposite to gradient to minimize), physics (force = -gradient of potential), image processing (edges where gradient large).'),
]
LESSONS=_GEOMETRY+_NUMBER_THEORY+_LINEAR_ALG+_CALCULUS
