"""ML frameworks corpus — PyTorch, JAX, HuggingFace transformers, training patterns."""
_PYTORCH=[
    ('What is a PyTorch tensor?','Multi-dimensional array with autograd support + GPU acceleration. `torch.tensor([1,2,3])`, `torch.zeros(5,5)`, `torch.randn(3,4)`. dtype defaults to float32 for floats, int64 for ints. .to(device) moves to GPU/CPU. .requires_grad_(True) enables gradient tracking. Underlies all PyTorch computation.'),
    ('What is autograd in PyTorch?','Automatic differentiation engine. Records ops on tensors with requires_grad=True into a computation graph. Call .backward() on a scalar loss → gradients computed for all leaf tensors with requires_grad. Access via .grad attribute. torch.no_grad() context disables tracking (for inference, saves memory). detach() removes a tensor from the graph.'),
    ('What is nn.Module in PyTorch?','Base class for all NN layers/models. Subclass it, define __init__ (register submodules + params) and forward(x). Calling instance(x) runs forward + tracks for autograd. Parameters auto-registered if assigned as attribute. .to(device) moves all params. .parameters() yields trainable tensors for optimizer. Model = nn.Sequential(...) for simple stacks.'),
    ('What is the training loop in PyTorch?','For each batch: (1) optimizer.zero_grad() — clear old grads. (2) pred = model(x) — forward. (3) loss = loss_fn(pred, y). (4) loss.backward() — compute grads. (5) optimizer.step() — apply update. Common bug: forgetting zero_grad → grads accumulate, leading to exploding updates. Wrap in model.train() and use model.eval() for inference.'),
    ('What is the difference between model.train() and model.eval()?','train(): enables dropout + uses batch statistics in batchnorm. eval(): disables dropout + uses running statistics in batchnorm. Forgetting model.eval() at inference is a classic bug — eval metrics look bad because dropout still randomly zeros activations. Pair with torch.no_grad() context for inference (no gradient tracking saves memory).'),
    ('What is a PyTorch DataLoader?','Iterates batches from a Dataset. Handles: batching, shuffling, parallel loading via num_workers, pinning memory for fast GPU transfer. `DataLoader(dataset, batch_size=64, shuffle=True, num_workers=4, pin_memory=True)`. Dataset is a class with __len__ + __getitem__. For huge data, use IterableDataset for streaming.'),
    ('What is a learning rate scheduler?','Adjusts learning rate during training. Common: StepLR (drop every N epochs), CosineAnnealingLR (smooth decay), OneCycleLR (warm-up + decay, best for fast convergence), ReduceLROnPlateau (drop when loss stalls). Call scheduler.step() after each epoch (or batch, depends on scheduler). Critical for fine-tuning — wrong LR is the #1 cause of bad results.'),
    ('What is mixed precision training (AMP) in PyTorch?','Compute forward + backward in fp16/bf16 (faster, less memory) while keeping master weights in fp32. Use `torch.cuda.amp.autocast()` + GradScaler for fp16 (handles underflow). bf16 (newer GPUs) doesn\'t need GradScaler. Often 2x speedup + half the memory. Standard practice for modern training.'),
    ('What is gradient accumulation?','Simulate larger batch size when GPU memory limits you. Run K mini-batches, accumulate grads (don\'t zero), then optimizer.step + zero. Effective batch size = mini_batch_size * K. Trades wall-clock for memory. Works with any optimizer. Pair with mixed precision for max memory savings.'),
    ('What is the difference between .item() and .detach()?','.item() converts a 0-dim tensor to a Python scalar (for printing/logging). .detach() returns a tensor sharing storage but removed from autograd graph (for using a value without contributing to backprop). Wrong: print(loss) — prints the tensor wrapper. Right: print(loss.item()) — prints just the number.'),
]
_JAX=[
    ('What is JAX?','Google\'s numerical computing library. Combines NumPy-style API + autodiff + JIT compilation + auto-vectorization (vmap) + parallelization (pmap). Built on XLA compiler. Pure-functional: no in-place mutation, side effects are second-class. Great for: research, custom training loops, models that don\'t fit clean PyTorch/TF patterns.'),
    ('What is jax.jit?','JIT-compiles a function via XLA → much faster after first call (traced + optimized). `@jax.jit def f(x): return x*2`. Restriction: inputs\' shape/dtype determine recompilation; control flow must use jax.lax.cond/scan (not Python if/for over tensors). Mental model: write the function as if it has fixed shapes, JIT specializes it.'),
    ('What is jax.vmap?','Auto-vectorization — turn a function that operates on one example into one that operates on a batch. `batched_f = jax.vmap(f)`. No manual broadcasting. Compose with grad/jit. Modern way to write batch-agnostic code.'),
    ('What is jax.grad?','Functional autodiff. `grad_f = jax.grad(f)` returns a function computing the gradient. `value_and_grad` gets both. Differs from PyTorch which puts gradient state on tensors. Pure-functional means easier composition (grad of grad of...).'),
    ('What is the difference between JAX and PyTorch?','PyTorch: imperative, stateful (autograd attached to tensors), wide ecosystem, easier for newcomers. JAX: functional, JIT-compiled, mathy/researchy, better for custom training loops, smaller community but growing. Use PyTorch for most production model work; JAX for research and where compilation matters (transformers from scratch, scientific computing).'),
]
_HF=[
    ('What is HuggingFace transformers?','Library wrapping thousands of pretrained models with consistent API. `from transformers import AutoModel, AutoTokenizer; model = AutoModel.from_pretrained("bert-base-uncased"); tok = AutoTokenizer.from_pretrained("bert-base-uncased")`. Auto* classes pick correct class per model architecture. Pipelines for high-level tasks: `pipeline("sentiment-analysis")(text)`.'),
    ('How do I fine-tune a HuggingFace model?','Use Trainer API: prepare Dataset (HF format), define TrainingArguments (lr, epochs, batch size, eval strategy), call Trainer(model, args, train_dataset, eval_dataset).train(). Handles: loss calc, optimizer, scheduling, mixed-precision, distributed, checkpoints, eval, logging. For more control: write custom training loop using model + Accelerate library.'),
    ('What is HF Accelerate?','Library that lets you write one training script that runs on CPU, single GPU, multi-GPU, TPU without code changes. `accelerator = Accelerator(); model, optim, dataloader = accelerator.prepare(model, optim, dataloader); accelerator.backward(loss)`. Replaces manual DDP/FSDP/DeepSpeed code. Pair with Trainer or custom loops.'),
    ('What is PEFT (parameter-efficient fine-tuning)?','Fine-tune large models by training only a small subset of params + freezing the rest. Adapters, LoRA, prefix tuning, prompt tuning. Result: 1000x less storage per fine-tuned variant (~MBs vs GBs), faster training, less catastrophic forgetting. LoRA dominant: injects low-rank matrices into attention; original weights frozen. HF peft library implements all.'),
    ('What is the difference between AutoModel and AutoModelForSequenceClassification?','AutoModel: base model, returns hidden states. AutoModelForX: adds task-specific head (classification head, language modeling head, QA head, etc.). For training classification: use AutoModelForSequenceClassification which has the final layer ready. For embeddings: AutoModel + pool last_hidden_state. Pick based on whether you need just features or full task output.'),
    ('What is a tokenizer in NLP?','Converts text ↔ token IDs. Modern tokenizers: BPE (GPT family), WordPiece (BERT), SentencePiece (T5, LLaMA). Subword-level: rare words split into known pieces, no OOV. Each model has ITS OWN tokenizer — must match. Returns dict with input_ids, attention_mask. Special tokens: [CLS], [SEP], [PAD], <|endoftext|>. Watch padding side for autoregressive models (padding on left for generation).'),
]
_TRAINING_PATTERNS=[
    ('How do I prevent overfitting in deep learning?','(1) more data — usually the strongest. (2) data augmentation — flips, crops, noise, mixup. (3) dropout — randomly zero activations during training. (4) weight decay (L2 reg) — small but consistent. (5) early stopping — monitor val loss, stop when it stops improving. (6) batch norm — has regularization effect. (7) smaller model. Try in roughly this order based on cost.'),
    ('What is a learning rate finder?','Train for one mini-epoch ramping LR from very small to very large. Plot loss vs LR. Best LR ≈ steepest decline (often 10x lower than where loss explodes). FastAI popularized; implemented in many libraries. Saves wasted runs of guessing.'),
    ('What is a confusion matrix?','For classification: rows = true class, cols = predicted class. Diagonal = correct. Off-diagonal = errors, by category. Reveals: which classes are confused with each other (often informative — visually similar, rare classes get under-predicted). More useful than accuracy alone, especially for imbalanced classes.'),
    ('What is the difference between precision, recall, and F1?','Precision = TP / (TP+FP) — of predicted positives, fraction correct. Recall = TP / (TP+FN) — of actual positives, fraction caught. F1 = harmonic mean of both. Use precision when false positives are expensive (spam filter). Recall when false negatives are expensive (cancer screening). F1 balances. Always cite alongside class distribution.'),
    ('What is cross-validation?','Split data into K folds, train on K-1, test on remaining, rotate. Average metrics. Result: more reliable estimate of generalization vs single train/test split. K=5 or K=10 common. Stratified k-fold preserves class proportions. Don\'t use for time-series (use TimeSeriesSplit). Don\'t use for huge datasets where one train/test split has enough samples.'),
    ('What is a transformer attention mechanism in detail?','For each token, compute Query, Key, Value vectors. Attention weights = softmax(Q @ K.T / sqrt(d_k)) — how much each token attends to every other. Output = weights @ V. Multi-head: do this multiple times in parallel with different projections, concatenate. Self-attention: Q,K,V from same input. Cross-attention: Q from one source, K,V from another (encoder-decoder).'),
]
LESSONS=_PYTORCH+_JAX+_HF+_TRAINING_PATTERNS
