"""Mobile development corpus — iOS, Android, React Native, Flutter basics."""
_IOS=[
    ('What is SwiftUI vs UIKit?','UIKit: imperative, mature (since 2007), all iOS apps were built with it. SwiftUI: declarative, newer (2019), describes UI as a function of state. SwiftUI gains ground each iOS version. New iOS-only apps: SwiftUI primarily, drop to UIKit for advanced cases. Cross-team and complex apps: UIKit still safer. Both interop via UIViewRepresentable.'),
    ('What is Combine vs async/await in Swift?','Combine: reactive streams (publishers + subscribers), like RxJS but Apple\'s. Best for event streams, UI bindings. async/await (Swift 5.5+): structured concurrency, much simpler for "do this then that" sequential async code. New code: async/await + AsyncSequence for streams. Combine still relevant for complex event flows.'),
    ('What is the iOS app lifecycle?','SceneDelegate (iOS 13+) or AppDelegate hooks: didFinishLaunching → sceneWillEnterForeground → sceneDidBecomeActive (you can act now). sceneWillResignActive (incoming call, control center) → sceneDidEnterBackground (you have ~5s for cleanup) → sceneDidDisconnect (system may purge). State preservation: NSUserActivity or scene state restoration.'),
    ('What is Core Data?','Apple\'s object persistence framework (NOT just a DB wrapper — handles change tracking, undo, faulting, validation). Uses SQLite (or in-memory) underneath. Model defined in xcdatamodeld. NSManagedObjectContext mediates writes. Steeper learning curve than SQLite or Realm, but deep iOS integration. Modern alternative: SwiftData (iOS 17+) — Swift-native, simpler API.'),
]
_ANDROID=[
    ('What is Jetpack Compose vs Views?','Views (XML-based): imperative, traditional Android UI since 2008. Compose: declarative, Kotlin-only, describes UI as a function of state. Composables are functions annotated with @Composable. New apps: Compose. Existing apps: incrementally adopt. Compose interops with Views in either direction. Much less boilerplate than XML + findViewById.'),
    ('What is the Android app lifecycle?','Activity lifecycle: onCreate → onStart → onResume (interactive). onPause (briefly losing focus) → onStop (no longer visible) → onDestroy (gone or rotation). Save state in onSaveInstanceState; restore in onCreate or onRestoreInstanceState. Fragments have similar but slightly different. ViewModel survives config changes (rotations) — store UI state there.'),
    ('What is a ViewModel in Android?','Lifecycle-aware object that survives configuration changes (rotation, etc) — UI re-attaches to the SAME ViewModel after recreate. Holds UI state + handles business logic. Use LiveData or StateFlow for observable state UI can subscribe to. Pair with Activity/Fragment\'s scope. Don\'t hold Context references (memory leak).'),
    ('What is Coroutines in Kotlin?','Lightweight concurrency primitive. `suspend fun` declares a function that can pause. launch{} fires-and-forgets, async{} returns Deferred for await. Structured concurrency via CoroutineScope — children cancel with parent. viewModelScope auto-cancels when ViewModel cleared. Replaces RxJava/callbacks for most async work in modern Android.'),
]
_CROSS_PLATFORM=[
    ('What is React Native?','Build native iOS/Android apps using React + JavaScript. Most UI primitives map to native components (View → UIView/View). JS runs in a separate thread, communicates with native via bridge. New Architecture (Fabric + TurboModules) replaces the bridge with JSI for sync calls. Trade-offs: huge code reuse, but native expertise still needed for tricky parts. Expo is the popular "batteries-included" setup.'),
    ('What is Flutter?','Google\'s cross-platform framework using Dart. Custom rendering engine (Skia/Impeller) — every pixel drawn by Flutter, not native components. Result: pixel-perfect across platforms, very fast. Hot reload is excellent. Trade-off: doesn\'t look exactly like native components by default (use Cupertino/Material widgets). Strong for: brand-led apps with custom design language.'),
    ('When choose React Native vs Flutter?','React Native: existing JS team, want shared logic with web app, want native-platform look. Flutter: pixel-perfect custom design, performance-sensitive UI animations, longer-term project willing to invest in Dart. Both production-ready. Native (Swift + Kotlin) still wins for: peak performance, deep platform integration (ARKit, complex audio), apps where native UX expectations are strict.'),
    ('What is Expo?','React Native + curated tooling + cloud services. EAS Build (builds in cloud, no local Xcode/Android SDK needed). EAS Update (over-the-air JS updates). expo-* libraries wrap native modules with consistent API. Modern Expo: works for almost any RN app (no longer "limited"). Recommended for new RN projects.'),
]
_MOBILE_CONCEPTS=[
    ('What are app permissions and why are they tricky?','Mobile OSes gate sensitive APIs (camera, location, contacts, photos) behind user consent. Always request at point of use, not at app start (jarring). Explain WHY in the permission dialog (some platforms require explicit purpose strings). Handle denial gracefully — feature should still partially work or guide user to settings. iOS is stricter than Android historically; both tightening.'),
    ('What is deep linking?','URL that opens a specific screen in your app instead of the home page. Universal Links (iOS) / App Links (Android) use HTTPS URLs — if app installed, opens app; else opens web. Custom schemes (myapp://...) work without verification but less secure. Critical for: marketing campaigns, share-to-app, email notifications. Test on real devices — simulator behavior differs.'),
    ('What is over-the-air (OTA) update?','Push code updates to installed apps without going through the App Store. RN: CodePush / EAS Update. Flutter: Shorebird / app_review hot-fix. Limits: only JS/Dart code (not native binaries) — can\'t add new native modules. iOS allows it for the same binary; Android similar. Use for: emergency bug fixes, A/B tests. Don\'t use to bypass App Review for major features.'),
    ('What is App Store Optimization (ASO)?','SEO for app stores. Title + keywords (App Store) / short description (Play Store) drive search. Icon + screenshots drive conversion from view to install. Ratings + reviews drive both. Update screenshots for major releases. Localize for top languages. Track via Sensor Tower / data.ai. Often half the work of app success is post-launch.'),
]
LESSONS=_IOS+_ANDROID+_CROSS_PLATFORM+_MOBILE_CONCEPTS
