"""Networking deep dive — TCP/IP, DNS, HTTP versions, WebSocket, WebRTC, QUIC."""
_TCPIP=[
    ('What is the TCP three-way handshake?','Client sends SYN. Server replies SYN-ACK. Client sends ACK. Now both sides know the other is reachable + agree on initial sequence numbers. Each step takes one RTT, so connection establishment costs 1.5 RTT before any data. TLS adds 1-2 more RTTs. QUIC + TLS 1.3 combine these into 1 RTT (or 0-RTT for resumption).'),
    ('What is the difference between TCP and UDP?','TCP: connection-oriented, reliable (retransmits lost packets), ordered, congestion-controlled. Best for: web, email, SSH — anything where every byte must arrive. UDP: connectionless, no delivery guarantees, no ordering. Best for: real-time (voice, video, gaming), DNS, where retransmit is worse than loss. QUIC builds reliability+ordering on top of UDP for HTTP/3.'),
    ('What is TCP congestion control?','Algorithm regulates send rate to avoid overwhelming the network. Slow start: exponential ramp until packet loss. Congestion avoidance: linear growth after that. On loss: cut rate (multiplicative decrease). Modern: CUBIC (Linux default), BBR (Google, model-based). Critical for: shared internet stability. Without it, one sender saturates everything.'),
    ('What is TCP flow control vs congestion control?','Both regulate send rate. Flow control: prevents OVERWHELMING THE RECEIVER (receive buffer fills). Receiver advertises window size. Congestion control: prevents OVERWHELMING THE NETWORK (intermediate routers drop). Inferred from loss/RTT. Both run simultaneously; effective rate = min of both windows.'),
    ('What is a port and how many are there?','16-bit number identifying an application endpoint. 0-65535. Well-known ports 0-1023 (need root to bind on Unix): 80 (HTTP), 443 (HTTPS), 22 (SSH), 53 (DNS). Registered 1024-49151. Ephemeral 49152-65535: assigned to client connections. Same IP + different ports = different services. Same IP + port = singleton listener.'),
    ('What is NAT and what does it break?','Network Address Translation — router rewrites source addresses so many internal devices share one public IP. Breaks: end-to-end addressability (you can\'t directly reach a device behind NAT), some protocols that embed IPs in payload (FTP active mode, SIP). Workarounds: STUN (discover external mapping), TURN (relay), UPnP (open ports). WebRTC uses STUN+TURN extensively.'),
    ('What is the OSI 7-layer model in practice?','Layer 1 Physical (cables, radio). Layer 2 Data link (Ethernet, WiFi MAC). Layer 3 Network (IP, routing). Layer 4 Transport (TCP, UDP). Layer 5-6 Session/Presentation (often skipped — TLS bridges). Layer 7 Application (HTTP, DNS). Real protocols don\'t map cleanly — most engineers use a simpler 4-layer mental model (link, internet, transport, app).'),
]
_DNS=[
    ('What is DNS and how does a lookup work?','Domain Name System — translates names to IPs. Lookup: (1) check local cache, /etc/hosts. (2) query recursive resolver (ISP or 8.8.8.8). (3) resolver queries root nameserver → TLD nameserver → authoritative nameserver. (4) returns IP. Caches at every level via TTL. UDP port 53 (TCP for large responses). Modern: DNS-over-HTTPS (DoH), DNS-over-TLS (DoT) for privacy.'),
    ('What are common DNS record types?','A: name → IPv4. AAAA: name → IPv6. CNAME: name → another name (alias). MX: mail server for domain. TXT: arbitrary text (SPF, DKIM, domain verification). NS: nameserver for domain. SOA: zone metadata. PTR: IP → name (reverse). Modern: HTTPS/SVCB records (auto-configure HTTPS, ECH).'),
    ('What is a DNS TTL and why does it matter?','Time-to-live: how long resolvers may cache the record. Short TTL (60s): fast propagation of changes, more queries (load on auth servers). Long TTL (1 hour+): less load, slower changes. Lower TTL before planned changes (DNS migration, IP change), restore after. Some resolvers ignore very low TTLs (clamped to minimum, often 30s).'),
    ('What is a CDN and how does it use DNS?','Content Delivery Network: replicas of your static content at points-of-presence (POPs) near users. DNS routes users to the nearest POP via: GeoIP-aware nameservers OR anycast IPs (same IP routed to closest server via BGP). Effect: lower latency, less load on origin, DDoS absorption. Modern: CDN edges run logic too (Workers, Lambda@Edge).'),
    ('What is DNSSEC?','DNS responses signed with public-key crypto. Resolver verifies signature chain back to root. Prevents: DNS spoofing/cache poisoning attacks. Adoption: most TLDs support, but stubs (browsers) rarely verify — relying on resolver. Doesn\'t encrypt (separate concern — DoH/DoT do that). Operational complexity has slowed adoption.'),
]
_HTTP_DEEP=[
    ('What is the difference between HTTP/1.1, HTTP/2, and HTTP/3?','HTTP/1.1: text-based, one request per connection (or pipelined with head-of-line blocking), TCP. HTTP/2: binary, multiplexed streams over single TCP connection, header compression (HPACK), server push. Still TCP — one packet loss blocks all streams. HTTP/3: built on QUIC (UDP), proper stream isolation (no HOL blocking across streams), faster connection setup. Modern web increasingly HTTP/3.'),
    ('What are common HTTP status codes and meanings?','2xx success: 200 OK, 201 Created, 204 No Content. 3xx redirect: 301 Permanent, 302 Temporary, 304 Not Modified (cached). 4xx client error: 400 Bad Request, 401 Unauthorized (no auth), 403 Forbidden (auth but denied), 404 Not Found, 409 Conflict, 422 Unprocessable Entity, 429 Too Many Requests. 5xx server error: 500 Internal, 502 Bad Gateway, 503 Service Unavailable, 504 Timeout.'),
    ('What is the difference between GET and POST?','GET: idempotent (repeating same request has same effect), safe (no side effects), cacheable, body usually empty (params in URL). POST: not idempotent (creates new each time), not safe, not cacheable by default, body carries data. Other verbs: PUT (idempotent replace), PATCH (partial update), DELETE (idempotent removal). Use the right verb for the operation\'s semantics.'),
    ('What are HTTP headers I should know?','Authorization (auth tokens). Content-Type (body MIME type). Accept (formats client wants). Cache-Control (caching directives). ETag + If-None-Match (conditional GET — server returns 304 if unchanged). Cookie + Set-Cookie. CORS: Access-Control-* family (cross-origin sharing). X-Forwarded-For (real client IP behind proxy). X-Request-Id (tracing). Always lowercase by convention but case-insensitive per spec.'),
    ('What is CORS and when does it bite?','Cross-Origin Resource Sharing. Browsers block JS from reading responses from a different origin unless server opts in via Access-Control-Allow-Origin header. Preflight OPTIONS request for non-simple requests. Bites: fetch fails in browser dev with cryptic message, server logs show no request (preflight failed). Server-to-server requests are unaffected (CORS is browser-only).'),
    ('What is server-sent events (SSE) vs WebSocket?','SSE: server-to-client only, over HTTP, browser-native EventSource API, auto-reconnect, text only. Use for: server-push notifications, live feeds, dashboards. WebSocket: bidirectional, binary or text, separate protocol after upgrade from HTTP, no auto-reconnect (do it yourself), more complex. Use for: chat, multiplayer games, interactive editing. Modern: WebTransport (over QUIC) is the future.'),
]
_REAL_TIME=[
    ('What is WebRTC?','Browser-native peer-to-peer real-time comms: audio, video, data channels. NAT traversal via STUN+TURN+ICE. Encryption mandatory (DTLS-SRTP). Used by: video calls, screen share, P2P file transfer, multiplayer games. Complex: signaling protocol up to you (not in spec). Powers Zoom-like apps in the browser without plugins.'),
    ('What is STUN, TURN, ICE for WebRTC?','STUN: server tells client its public IP/port (discovers NAT mapping). ICE: framework that tries multiple candidates (direct, STUN-discovered, relayed) and picks the best. TURN: relay server when direct P2P impossible (symmetric NAT) — uses bandwidth, costs $. Coturn is common open-source TURN. Most WebRTC apps need ALL three for production reliability.'),
    ('What is QUIC and why does it matter?','UDP-based transport designed by Google, now IETF standard. Combines TLS 1.3 + multiplexing + connection migration into one protocol. 0-RTT or 1-RTT connection setup (vs TCP+TLS 2-3 RTT). Per-stream HOL blocking elimination. Connection survives IP change (mobile network → WiFi). Underpins HTTP/3. Limited by middleboxes that don\'t pass UDP cleanly.'),
    ('What is gRPC?','RPC framework using HTTP/2 + Protocol Buffers. Strongly typed via .proto files; codegen generates client + server stubs. Supports: unary RPC, server streaming, client streaming, bidirectional streaming. Faster + smaller than JSON over HTTP. Best for: service-to-service comms. Browser support requires gRPC-Web (proxy converts). Use for backend; REST/GraphQL for browsers.'),
    ('What is mTLS and when to use?','Mutual TLS: both client AND server present certificates. Client identity proven via cert. Replaces API keys for service-to-service trust. Use for: high-security service mesh (e.g., Istio), regulatory environments, zero-trust networks. Operational cost: cert lifecycle (rotation, revocation). SPIFFE/SPIRE for automated cert distribution at scale.'),
]
LESSONS=_TCPIP+_DNS+_HTTP_DEEP+_REAL_TIME
