"""Performance + profiling corpus — measuring, optimizing, common patterns."""
_MEASURING=[
    ('What is the first rule of performance optimization?','Measure first. Programmer intuition about what is slow is wrong more often than right. Tools: time.perf_counter (single function), profilers (cProfile, py-spy, perf, Instruments), flame graphs. Without numbers you optimize hypothetical bottlenecks while real ones go unfixed. "Premature optimization is the root of all evil" — Knuth\'s real point: optimize the 3% that matters, with data.'),
    ('What is a flame graph and how to read?','Stacked horizontal bars; each level is a stack frame, width is total time spent. Bottom = entry point. Widest plateaus at top = hot functions where time is spent. Read by scanning for unexpected width — that\'s where the cost is. Generate via py-spy (Python), perf + FlameGraph script (Linux), Instruments (macOS), Chrome DevTools (JS).'),
    ('What is the difference between sampling and instrumentation profiling?','Sampling: pauses program periodically, records stack. Low overhead (~1-5%), can run in prod. Misses very short calls. Instrumentation: hook every function call. High overhead (10x slower), but exact. Use sampling for prod / first look. Use instrumentation only when you need exact call counts. py-spy = sampling, cProfile = instrumentation.'),
    ('What are the latency numbers every engineer should know?','L1 cache: ~1ns. L2 cache: ~5ns. RAM: ~100ns. SSD random read: ~150µs. HDD seek: ~10ms. Network round-trip same DC: ~500µs. Cross-region: ~50-150ms. Internet RTT: ~100ms+. Memory access is ~1000x faster than network; network is ~1000x faster than disk seek. Plan memory hierarchy accordingly.'),
    ('What is the difference between wall time and CPU time?','Wall time: actual elapsed clock time (what the user feels). CPU time: time CPU was busy with this process. Wall > CPU means waiting (I/O, locks, sleep). Wall ≈ CPU means CPU-bound. /usr/bin/time on Unix shows both. Important: improving CPU time on I/O-bound code may have ZERO wall-time impact — fix the I/O instead.'),
]
_OPTIMIZATION=[
    ('What are common Python perf wins?','(1) avoid the function call inside the loop — pull constants out. (2) local variable lookup faster than global. (3) join is faster than += for strings. (4) list.append in loop vs comprehension — comp is faster. (5) set membership O(1) vs list O(n). (6) C-extension methods (numpy, Cython) for hot loops. (7) profile before assuming — Python surprises.'),
    ('What is vectorization?','Replace Python loop with numpy/pandas operations that run in optimized C. `[x*2 for x in lst]` (Python loop) → `arr * 2` (numpy, ~50x faster). Each element processed without Python overhead. Even better: SIMD on modern CPUs. Cost: memory (full arrays vs streaming). Worth it when arrays fit comfortably.'),
    ('What is memoization?','Cache function results for previously-seen inputs. Trade memory for time. Python: `@functools.lru_cache` or `@cache` for pure functions. Args must be hashable. Best for: recursive algorithms with overlapping subproblems (DP, Fibonacci, tree traversal). Watch: unbounded cache = memory leak; pick maxsize. Doesn\'t help if inputs rarely repeat.'),
    ('What is lazy evaluation?','Compute values only when needed. Generators in Python (yield), iterators in JS/Java, futures. Use when: full dataset doesn\'t fit in memory, you only need first N matches, computation is expensive and may be skipped. Trade: harder to debug (state hidden), some operations need full data (sum, sort, len).'),
    ('What is batching and when use it?','Group N small operations into one larger op. Amortizes per-op overhead. Examples: batch DB inserts (1 query vs N), batch network requests (1 RPC vs N), batch GPU ops (better throughput). Trade: latency for first item INCREASES (must wait for batch to fill or timeout). Streaming systems use micro-batching for both throughput + bounded latency.'),
    ('What is caching at different layers?','L1 (function memo) → L2 (in-process cache, LRU) → L3 (Redis/memcached, shared across servers) → L4 (CDN / edge cache, near user). Each layer absorbs hits and protects the next. Cost grows downward; hit rate improves. Always: TTL or invalidation strategy. Cache invalidation IS one of the hard things in computer science.'),
    ('What is database query optimization 101?','(1) EXPLAIN the query — see actual plan. (2) Add index for columns in WHERE/JOIN/ORDER BY. (3) Avoid SELECT * — fetch only needed cols. (4) Beware N+1 (loop with query inside). (5) Beware non-sargable predicates (function on column prevents index use). (6) LIMIT early when paginating. (7) Use covering indexes for hot queries. Measure each change.'),
    ('What is connection pooling and why important?','Reuse pre-opened DB/HTTP connections. Opening costs ~100ms (TCP + auth). Pool size = max concurrent in-flight queries (NOT max requests). For DB: use PgBouncer in front of Postgres for thousands of clients. For HTTP: requests.Session(), aiohttp.ClientSession — reuse the same client. Sharing one client across program lifetime is a huge perf win.'),
]
_HARDWARE=[
    ('What is cache locality and why does it matter?','Cache reads bring in a whole CACHE LINE (~64 bytes). Sequential access reuses this line — fast. Random access fetches new lines — slow. Iterating a packed array (numpy) is 10x faster than iterating a linked list of same size. Same for structs: layout related fields together (struct-of-arrays vs array-of-structs trade-offs).'),
    ('What is the difference between latency-bound and throughput-bound?','Latency-bound: serial chain — each step depends on previous (interactive UI, single user request). Optimize: each step\'s wall-clock time. Throughput-bound: parallel work, total work per unit time matters more than each item\'s time (batch processing). Optimize: queue depth, batching, parallelism. The technique is different per case.'),
    ('What is SIMD?','Single Instruction Multiple Data. CPU operates on a vector of values in one instruction. SSE, AVX, AVX-512 instruction sets. Numpy + BLAS use them automatically for many ops. Modern compilers auto-vectorize loops with `-O2 -ftree-vectorize`. Manual: intrinsics (in C/C++) or Rust\'s std::simd. ~4-16x speedup for tight numerical loops.'),
    ('What is a memory leak and how to find one?','Memory allocated but never freed/referenced → process RSS grows unbounded → eventually OOM. Causes: forgotten global state, circular references with __del__ (Python), missing close on resources. Tools: tracemalloc (Python), pprof (Go), heap snapshots (Node devtools), valgrind (C/C++). Bisect: when did it start? What changed? Reduce to minimal repro.'),
    ('What is GC pause and how to mitigate?','Garbage collector stops the world to reclaim memory. Larger heap = longer pauses (up to seconds for old JVMs). Mitigations: (1) generational GC (most collections fast, full GC rare). (2) concurrent/low-pause collectors (G1, ZGC, Shenandoah). (3) reduce allocation rate (object pools, primitive arrays). (4) for latency-critical, languages without GC pauses (Rust, C++) or off-heap (Aeron). For Python: __slots__ + careful sharing.'),
]
LESSONS=_MEASURING+_OPTIMIZATION+_HARDWARE
