"""Python library deep dives — numpy, pandas, requests, FastAPI, Flask, pytest, pydantic."""
_NUMPY=[
    ('What is numpy and why use it?','Library for fast n-dimensional array math in Python. Operations vectorized in C (10-100x faster than Python loops). Foundation of: pandas, scikit-learn, scipy, PyTorch interop. Core: ndarray, dtype, broadcasting, slicing, fancy indexing. Memory layout matters: C-order (row-major) is default; row-iteration is cache-friendly. Avoid Python loops over numpy arrays — use vectorized ops.'),
    ('What is numpy broadcasting?','Operating on arrays of different shapes by virtually expanding the smaller. Rules: align trailing dims, dim of 1 stretches to match, dims that don\'t match (and aren\'t 1) error. Example: shape (3,4) + shape (4,) works — the (4,) broadcasts to (3,4). Avoid the wrong shape combos by inspecting `.shape` before ops.'),
    ('What is the difference between numpy.array and numpy.asarray?','array() ALWAYS makes a copy. asarray() makes a copy only if needed (different dtype, not already array). Use asarray() to avoid pointless copies when input might already be the right type. Both accept lists, tuples, other arrays. For pre-allocating: np.zeros, np.empty, np.full.'),
    ('How do I reshape a numpy array?','arr.reshape(new_shape). Returns a VIEW when possible (no copy) — shares memory with original. -1 in shape means "infer this dim": arr.reshape(-1, 4) makes columns 4, rows whatever fits. Use arr.flatten() for guaranteed copy to 1D. Use arr.ravel() for view-when-possible flattening.'),
    ('What is numpy fancy indexing?','Index with arrays of integers or booleans. `arr[[0,2,4]]` selects those rows. `arr[arr > 5]` selects elements where condition true. Combinations: `arr[mask, col_idx]`. Always returns a COPY (unlike basic slicing which returns view). Powerful for select+update workflows.'),
    ('How do I save and load numpy arrays?','np.save("file.npy", arr) — single array, native format. np.load("file.npy") — loads. np.savez("file.npz", a=a1, b=b1) — multiple arrays in one file. np.savetxt for plain text (slower, less precise). For huge arrays + portability: HDF5 via h5py.'),
]
_PANDAS=[
    ('What is pandas?','Library for tabular data (DataFrames) + time-series (Series). Built on numpy. Read/write CSV/Parquet/SQL/JSON. SQL-like ops (groupby, merge, join, pivot). Workhorse for data exploration. Modern alternatives: Polars (faster, lazy, better API in many ways), DuckDB (SQL on dataframes). Pandas remains the most-known.'),
    ('How do I read a CSV with pandas?','`pd.read_csv("file.csv")`. Common args: usecols=["a","b"] (subset of cols), dtype={"a":int} (specify types), parse_dates=["date"], na_values=["?","N/A"], chunksize=10000 (iterator for huge files). For Parquet (much faster + typed): pd.read_parquet. For Excel: pd.read_excel (needs openpyxl).'),
    ('What is the difference between loc and iloc?','df.loc[row_label, col_label]: label-based indexing (use index names). df.iloc[row_pos, col_pos]: position-based (integer offsets). loc is usually clearer for typed indexes; iloc for "give me row 5 regardless of label." Avoid chained indexing (df[a][b]=...) — set with df.loc[a, b]=... to avoid SettingWithCopyWarning.'),
    ('What is a pandas groupby?','Split data by a column, apply a function, combine results. `df.groupby("dept")["salary"].mean()`. Multiple aggs: `.agg({"salary":"mean", "age":"max"})`. Transform: keep same row count (returns aligned to original). Apply: arbitrary function. Use named aggregation for clearer output: `.agg(avg_sal=("salary","mean"))`.'),
    ('What is the difference between merge and join in pandas?','Both combine DataFrames. merge: SQL-style joins, more flexible (any column key). df1.merge(df2, on="id", how="left"). join: index-based, simpler syntax. how can be: left, right, inner (default), outer. Always check result row count vs expected — duplicate keys cause cross-join blow-up.'),
    ('How do I handle missing values in pandas?','df.isna() / .notna() detect. df.dropna() removes rows with any (or all) NaN. df.fillna(value) replaces. Smarter: df["col"].fillna(df["col"].mean()) (impute), or .ffill() (forward fill from previous valid), .bfill() (backward). Be explicit about strategy per column; don\'t default.'),
]
_HTTP_LIB=[
    ('What is requests in Python?','HTTP client library — easier than urllib. `requests.get(url, params={"q":"x"}, headers={"X-Y":"z"}, timeout=10)`. ALWAYS set timeout (default is forever, will hang in prod). Use Session for connection reuse: `with requests.Session() as s: s.get(...)`. Modern alternatives: httpx (sync + async, same API), aiohttp (async-only).'),
    ('What is httpx vs requests vs aiohttp?','requests: sync only, mature, simple. httpx: sync + async with same code, requests-compatible API, supports HTTP/2. aiohttp: async-only, low-level, max performance for very async-heavy code. New projects: httpx (works in sync code, supports async when needed). aiohttp for high-throughput async services. Always specify timeouts.'),
    ('How do I handle errors in HTTP requests?','Always: try/except + check status. `r = requests.get(url, timeout=10); r.raise_for_status()` raises HTTPError on 4xx/5xx. Catch: requests.RequestException (parent of all). Retry with backoff: tenacity library or urllib3 Retry adapter on a Session. Distinguish: connection errors (network), timeout, HTTP errors (server returned error code).'),
    ('What is FastAPI?','Modern Python web framework. Async-first, type-hint-driven (auto-generates OpenAPI docs + validates input via Pydantic). Fast (Starlette underneath). Best for: APIs (REST or GraphQL via Strawberry). Easy to learn if you know Python type hints. Production-ready. Compare to Flask (sync, simpler) or Django (full-stack, batteries-included).'),
    ('What is Flask and when use it?','Microframework — minimal core, add extensions for ORM/migrations/forms. Sync (Flask 2.0+ has async support). Best for: small APIs, internal tools, prototypes, anything where Django is overkill. Easy to learn. Modern: many teams pick FastAPI for new projects because of automatic validation + docs + async.'),
    ('What is the difference between FastAPI and Flask?','FastAPI: async, type hints required for validation, auto OpenAPI docs, faster, modern. Flask: sync (mostly), no type-hint validation, smaller core, larger ecosystem (Flask-SQLAlchemy, Flask-Login). For new APIs: FastAPI usually wins. For tiny tools or legacy: Flask still fine.'),
]
_PYTEST=[
    ('What is pytest and basic patterns?','Python test runner. Tests are functions starting with `test_`. Assertions are plain `assert x == y` (pytest rewrites for rich failure messages). Run: `pytest`. Filter: `pytest -k "expression"`. Verbose: `-v`. Stop on first fail: `-x`. Show print output: `-s`. Coverage: pytest-cov plugin.'),
    ('What is a pytest fixture?','Function decorated with @pytest.fixture providing shared setup. Tests REQUEST a fixture by including its name in the test\'s signature. Scope: function (default, fresh per test), class, module, session. Teardown via yield: code after yield runs after the test. Powerful for: DB connections, temp files, mock services.'),
    ('What is parametrize in pytest?','Run same test with multiple inputs. `@pytest.mark.parametrize("a,expected", [(1,2),(3,4)])`. Each tuple becomes one test instance. Reports each as separate test (clear failures). Combine with ids= for readable names. Better than loops inside test (which stop at first failure).'),
    ('What is conftest.py?','Special pytest file. Fixtures defined here are auto-available to tests in same dir + subdirs WITHOUT import. Put shared fixtures, plugins, hooks here. One per test directory if needed. The root conftest.py applies to entire test suite.'),
    ('How do I mock in pytest?','Use unittest.mock or pytest-mock. `from unittest.mock import patch; @patch("module.func") def test_x(mock_func): mock_func.return_value = ...`. pytest-mock provides mocker fixture for cleaner syntax. Mock at the boundary you control (where it\'s USED, not where it\'s defined). Verify calls with mock.assert_called_with.'),
]
_PYDANTIC=[
    ('What is Pydantic?','Data validation library using Python type hints. Define schema as class with annotations; Pydantic validates input at runtime + provides clear errors. Used heavily by FastAPI for request/response validation. v2 (current) is much faster than v1 (Rust core). Replaces hand-written validation + dataclasses where you need runtime checks.'),
    ('How is Pydantic different from dataclass?','dataclass: pure Python, no runtime validation, just generates __init__ etc. Pydantic: validates types at runtime, coerces (str "5" → int 5 if asked), provides JSON serialization, generates JSON Schema. Use dataclass for: pure data, no validation needed. Pydantic when: parsing untrusted input (config, API requests, JSON files).'),
    ('What is a Pydantic field validator?','Custom validation logic on a specific field. v2: `@field_validator("name") @classmethod def check(cls, v): ...`. Raise ValueError or return processed value. For cross-field rules: `@model_validator(mode="after")`. Run automatically when model instantiated.'),
]
LESSONS=_NUMPY+_PANDAS+_HTTP_LIB+_PYTEST+_PYDANTIC
