"""Python deep dive — asyncio, type hints, pathlib, dataclasses, contextvars, performance idioms."""
_ASYNCIO=[
    ('What is asyncio.gather vs asyncio.wait_for?','asyncio.gather(*coros) runs multiple coroutines concurrently, returns list of results when all done. Cancels remaining on first exception (unless return_exceptions=True). asyncio.wait_for(coro, timeout) wraps a single coro with timeout — raises TimeoutError if exceeded. Combine for "do N things concurrently with timeout": asyncio.wait_for(asyncio.gather(...), timeout=5).'),
    ('What is the difference between asyncio.create_task and asyncio.ensure_future?','create_task is the modern name (Python 3.7+), wraps a coroutine into a Task and schedules it on the current loop. ensure_future is older + more flexible (accepts coroutine OR future OR awaitable). Use create_task for new code. Always await tasks somewhere or save references — orphan tasks can be silently garbage-collected.'),
    ('What is the asyncio event loop?','Single-threaded scheduler for coroutines. Loops: pick next ready coroutine, run until it awaits, suspend it, repeat. asyncio.run(main()) creates a loop, runs main, closes loop. Don\'t mix loops across threads (each thread can have its own via asyncio.new_event_loop). Modern: asyncio.run handles 95% of cases.'),
    ('What is the difference between async def and a generator?','Both produce iterables, both can yield/await. Generators (def with yield) used for sync iteration. async def with await produces a coroutine — runs on event loop, can do non-blocking I/O. Async generators (async def with yield) combine: `async for x in agen():`. async def WITHOUT await is legal but pointless (just a normal function in disguise).'),
    ('How do I run blocking code in async without blocking the loop?','asyncio.to_thread(blocking_fn, *args) (Python 3.9+) — runs in thread pool, awaitable. For older Python: loop.run_in_executor(None, blocking_fn). For CPU-bound, use ProcessPoolExecutor instead. RULE: never call blocking I/O from inside an async function without to_thread — freezes ALL coroutines until blocking call returns.'),
    ('What is the difference between asyncio.Queue and queue.Queue?','asyncio.Queue: for async coroutines, get/put are awaitable, single-threaded. queue.Queue: for threads, get/put block the calling thread. Different worlds. Use asyncio.Queue for producer-consumer between coroutines; queue.Queue for between threads. Don\'t cross-pollinate — wrap with to_thread bridge if you must.'),
    ('How do I cancel an asyncio task?','task.cancel() schedules cancellation; the task raises CancelledError at the next await point. Use try/except CancelledError + cleanup + re-raise (don\'t swallow). asyncio.shield(coro) protects a sub-task from being cancelled by its parent. Common bug: forgetting to await cancelled task can hide errors.'),
    ('What is the GIL and how does asyncio relate?','GIL = Global Interpreter Lock — only ONE Python thread executes bytecode at a time. asyncio is single-threaded by design — no GIL contention because no actual parallelism. async I/O still wins for I/O-bound work because awaits release control during I/O, letting other coroutines run. For CPU-bound: GIL or no GIL, you need multiprocessing.'),
]
_TYPING=[
    ('What is the difference between Optional[X] and X | None?','Identical semantically. `Optional[X]` from typing module. `X | None` is the newer (Python 3.10+) builtin union syntax — preferred in modern code. Both mean "X or None." Different from `X = None` default parameter (which has type X if not None can be passed). Type checkers (mypy, pyright) treat them the same.'),
    ('What does TypedDict do?','Lets you type-annotate dict shapes: `class Movie(TypedDict): title: str; year: int`. Then `m: Movie = {"title": "X", "year": 2024}` is type-checked. Useful when you can\'t convert to a class (JSON data, **kwargs). NotRequired[T] for optional keys. total=False makes all keys optional. Runtime behavior: still just a dict; the class is type-only.'),
    ('What is a Protocol in Python typing?','Structural subtyping — duck typing for type checker. Define methods/attrs a type must have without inheritance: `class Sized(Protocol): def __len__(self) -> int: ...`. Anything with __len__ is automatically Sized — no inheritance needed. Lets you type-annotate "things that quack like X" without forcing existing code to import your base class. Modern alternative to ABCs for most cases.'),
    ('What is dataclasses.dataclass and when use it?','Decorator that auto-generates __init__, __repr__, __eq__, __hash__ based on class annotations. `@dataclass class Point: x: int; y: int`. Less boilerplate than manual class. Frozen: `@dataclass(frozen=True)` → immutable + hashable. Use for: data containers, value objects, configs. Use plain classes when you need methods that do real work. Pydantic is similar with runtime validation.'),
    ('What is the difference between dataclass and NamedTuple?','dataclass: mutable by default, regular class (can subclass, add methods). NamedTuple: immutable, tuple-based (supports indexing, unpacking, isinstance(x, tuple)), slightly faster + smaller memory. NamedTuple lacks default values for typing.NamedTuple (works in newer Python). Use NamedTuple for tiny immutable data; dataclass for everything else.'),
    ('What is functools.lru_cache and when use it?','Decorator that memoizes a function: `@lru_cache(maxsize=128) def fib(n): ...`. Returns cached result for previously-seen arg combinations. Args must be hashable. Useful for pure functions called repeatedly with same args (recursive algos, expensive computations). Watch out: caches grow with unbounded inputs → memory leak. functools.cache (3.9+) = unbounded version.'),
]
_PATHLIB_IO=[
    ('What is pathlib.Path and why use it?','Object-oriented path manipulation. p = Path("data/file.txt"); p.parent (directory), p.suffix (.txt), p.stem (file), p / "subdir" (join), p.exists(), p.read_text(), p.write_text("..."), p.glob("*.py"). Cross-platform (handles / vs \\ automatically). Replaces os.path.* for most use cases. Modern Python: always use pathlib.'),
    ('How do I find all Python files in a directory recursively?','Path.rglob("*.py") returns iterator. Equivalent: Path.glob("**/*.py"). Filter further: [p for p in Path(".").rglob("*.py") if "test" not in p.parts]. Skip hidden dirs: check `any(part.startswith(".") for part in p.parts)`. For huge trees, consider os.walk or scandir for speed.'),
    ('How do I read JSON safely in Python?','`with open(path, encoding="utf-8") as f: data = json.load(f)`. Or pathlib: `data = json.loads(Path(path).read_text(encoding="utf-8"))`. Catch json.JSONDecodeError for malformed input; OSError for missing/permissions. For untrusted JSON: validate schema with pydantic or jsonschema before using.'),
    ('How do I handle UTF-8 BOM?','BOM = byte-order mark at file start (0xEF 0xBB 0xBF for UTF-8). Open with encoding="utf-8-sig" — strips BOM if present, leaves text alone if not. Common with Windows-generated CSV/TXT. utf-8 (without -sig) leaves BOM as visible \\ufeff char which breaks parsers.'),
    ('What is the difference between os.path and pathlib?','os.path: string-based, function-style (os.path.join(a, b), os.path.exists(x)). pathlib: object-oriented, methods on Path objects. pathlib is generally preferred — more readable, less error-prone, supports / operator. os.path still needed for some interop with libraries that take strings only. Convert: str(path) for str, Path(s) for Path.'),
]
_PERF=[
    ('When should I use a tuple vs a list?','Tuple: immutable, hashable, slightly smaller + faster, use for fixed-size heterogeneous records (coords, db rows). List: mutable, growable, use for collections of like items. Tuples can be dict keys / set members; lists cannot. Functions returning multiple values use tuples implicitly.'),
    ('What is the fastest way to count occurrences in a list?','collections.Counter: `Counter(iterable)` returns dict-like {value: count}. .most_common(n) returns top n. Implemented in C, faster than manual dict++. For huge data, consider numpy.bincount (for ints) or pandas value_counts (DataFrame).'),
    ('How do I efficiently process a huge file line by line?','`for line in open(path):` — iterator, doesn\'t load whole file into memory. For binary: open(path, "rb") + iterate. For huge files where you need parallelism: split by byte ranges, process in workers. Avoid f.readlines() — loads all into memory.'),
    ('What is the difference between deepcopy and dict comprehension?','Dict comp `{k: v for k, v in d.items()}` makes a SHALLOW copy — nested dicts/lists still shared. copy.deepcopy(d) recursively copies all nested structures. For mutation-safety, deepcopy. For just "new top-level dict," shallow is faster.'),
    ('How do I time a Python function?','time.perf_counter() before/after: `t = time.perf_counter(); fn(); elapsed = time.perf_counter() - t`. Higher-resolution + monotonic (won\'t go backward on clock adjustment). For benchmarking: timeit module (handles warmup, multiple runs, returns minimum). For profiling: cProfile + snakeviz. For line-level: line_profiler.'),
    ('What is a slot in a Python class and when use it?','`__slots__ = ("x", "y")` in class definition. Restricts attributes to listed names, stores them in fixed-size array instead of __dict__. Result: ~40% less memory per instance, slightly faster attribute access. Use for: classes with many instances and few attrs (data point objects). Trade-off: can\'t add new attrs dynamically; subclass slots interact weirdly. Pair well with dataclass(slots=True) in 3.10+.'),
    ('Why is mutable default argument a bug?','`def f(x=[]):` — the default list is created ONCE at function definition, then SHARED across all calls. Mutations persist: f() then f() sees the previous one. Fix: `def f(x=None): x = x if x is not None else []`. Classic Python footgun; pylint flags it. Immutable defaults (int, str, tuple, None) are safe.'),
]
_MISC=[
    ('What is the walrus operator :=?','Assignment expression — assigns AND returns value. `if (n := len(data)) > 10: print(n)` — bind n once, use twice. Useful in: while loop conditions (read chunks until empty), list comprehensions (compute once, filter and project), regex matches. Don\'t overuse — clarity beats brevity.'),
    ('What is the difference between @staticmethod, @classmethod, and instance method?','Instance method (self): bound to instance, has access to self. Class method (cls): bound to class, can access class-level state. Static method: just a function namespaced inside class, no implicit args. Classmethod for alternative constructors (`User.from_dict(d)`). Staticmethod when the function relates to the class but doesn\'t need self/cls — could be a module function.'),
    ('What is enumerate and why use it?','`for i, x in enumerate(lst):` — gives index AND value. Replaces error-prone `for i in range(len(lst)): x = lst[i]`. enumerate(lst, start=1) starts at 1. Use whenever you need both index and element.'),
    ('What is zip and zip(*) explained?','zip(a, b) pairs up: zip([1,2,3], ["a","b","c"]) → [(1,"a"), (2,"b"), (3,"c")]. Stops at shortest. zip_longest fills shorter. zip(*list_of_pairs) UNZIPS: zip(*[(1,"a"), (2,"b")]) → [(1,2), ("a","b")] — the * unpacks the list as args. Classic pattern for transposing.'),
    ('What is a Python set comprehension?','`{f(x) for x in iterable if cond}` — like list comp but returns a set (no duplicates). `{c.lower() for c in "Hello"}` → {"h", "e", "l", "o"}. Dict comp similar: `{k: v for k, v in pairs}`. Use sets for membership tests (O(1) avg vs O(n) for list).'),
    ('What is the difference between map/filter and list comprehension?','Both transform/filter iterables. Comprehensions: more Pythonic, can combine map+filter+nesting in one line, returns list directly. map/filter: return iterators (lazy), useful for chaining without intermediate lists, slightly faster in tight loops when called with builtin C functions. Modern preference: comprehensions for clarity, generators (x for x in...) for laziness.'),
]
LESSONS=_ASYNCIO+_TYPING+_PATHLIB_IO+_PERF+_MISC
