"""Rust corpus — ownership, borrowing, traits, async, common patterns."""
_OWNERSHIP=[
    ('What is ownership in Rust?','Each value has exactly ONE owner. When the owner goes out of scope, the value is dropped (memory freed). Moves transfer ownership: `let s2 = s1` invalidates s1. Copy types (i32, bool, etc.) duplicate instead. Ownership eliminates the need for garbage collection and prevents double-free / use-after-free at compile time. Cost: learning curve — fighting the borrow checker is the Rust rite of passage.'),
    ('What is borrowing in Rust?','Temporary access to a value without taking ownership. Immutable borrow: `&T` — many allowed simultaneously, read-only. Mutable borrow: `&mut T` — only one allowed at a time, exclusive. Borrow checker enforces at compile time. Rule: you can have either (a) any number of immutable borrows, OR (b) exactly one mutable borrow — never both. Prevents data races by construction.'),
    ('What is the difference between &str and String?','&str: borrowed string slice, immutable, fixed view into UTF-8 bytes. Often static (literals are &\'static str). String: owned, growable, heap-allocated, mutable. Convert: String::from("x") or s.to_string() or s.to_owned(). Take &str for function params unless you need to OWN/mutate. Avoid taking `String` when `&str` suffices — forces caller to allocate.'),
    ('What are lifetimes in Rust?','Annotations that tell the compiler how long references are valid. Usually elided (inferred). Explicit: `fn longest<\'a>(x: &\'a str, y: &\'a str) -> &\'a str`. Most beginners over-annotate; learn elision rules first. Lifetimes prevent dangling references at compile time. \'static = lives entire program (literals, leaked allocations).'),
    ('What is the Result type in Rust?','Enum with two variants: Ok(T) for success, Err(E) for failure. All recoverable errors return Result. Forces caller to handle both cases via match, ? operator, or .unwrap(). The ? operator early-returns Err: `let x = foo()?;` — propagates errors with minimal noise. unwrap() panics on Err; use for prototypes, never production.'),
    ('What is the Option type in Rust?','Enum: Some(T) or None. Replaces null/None checks that JavaScript/Python use. Forces handling absence at the type level. Methods: .unwrap_or(default), .map(fn), .and_then(fn), match for full control. ? works on Option in functions returning Option. Null pointer crashes don\'t exist in safe Rust because Option enforces the check.'),
    ('What is the difference between Box, Rc, and Arc?','Box<T>: heap allocation, single owner, moves like other types. Use for recursive types or large values. Rc<T>: reference-counted, multiple owners, single-threaded only. Use when ownership graph is unclear. Arc<T>: atomic-reference-counted, thread-safe Rc. Use for shared ownership across threads. None of these provide interior mutability — pair with RefCell/Mutex for that.'),
    ('What is RefCell vs Mutex?','Both provide INTERIOR MUTABILITY (mutate through &T). RefCell: single-threaded, runtime borrow checking (panics on violation). Mutex: thread-safe, blocks until lock available. Use RefCell inside Rc for single-threaded shared mutation. Use Mutex inside Arc for multi-threaded. Plus RwLock when many readers / few writers.'),
    ('What does the ? operator do in Rust?','Shorthand for "if Err return Err early, else unwrap to value." Works on Result and Option. `let x = foo()?;` is `let x = match foo() { Ok(v) => v, Err(e) => return Err(e.into()) };`. Massively reduces error-handling boilerplate. The .into() conversion lets ? convert error types if From is implemented.'),
    ('What is a trait in Rust?','Like an interface — a set of method signatures that types can implement. `trait Greet { fn hello(&self); }`. Implement: `impl Greet for User { fn hello(&self) {...} }`. Trait bounds in generics: `fn f<T: Greet>(x: T)`. Standard traits: Display, Debug, Clone, Copy, Eq, Ord, Iterator. Derive often: `#[derive(Debug, Clone)]`.'),
    ('What is a closure in Rust?','Anonymous function that captures variables from enclosing scope. `|x| x + 1`. Three trait flavors: Fn (immutable borrow), FnMut (mutable borrow), FnOnce (consumes). Compiler picks the most permissive that works. `move` keyword forces capture by value: `move || println!("{}", x)`. Common in iterators, async tasks, callbacks.'),
    ('What is async/await in Rust?','Lazy futures + executors. `async fn f() -> T { ... }` returns a Future. Nothing runs until you .await it OR spawn it on an executor (tokio::spawn, async-std). No async runtime built-in — you pick (tokio is dominant). Differs from JS where async functions auto-run. Pin/Send/Sync constraints add learning curve. Tokio = use it for almost everything async in Rust today.'),
]
_PATTERNS=[
    ('How do I iterate over a vector in Rust?','`for x in &vec { ... }` (immutable borrow), `for x in &mut vec { ... }` (mutable), `for x in vec { ... }` (consumes). Iterator methods: vec.iter().map(|x| x*2).filter(|x| *x > 5).collect::<Vec<_>>(). Lazy — nothing happens until terminal op (collect, sum, for_each).'),
    ('What is the difference between iter, iter_mut, and into_iter?','iter() gives &T (immutable borrow of items). iter_mut() gives &mut T (mutable borrow, exclusive). into_iter() gives T (consumes the collection, transferring ownership of items out). Pick based on what you need: read-only → iter, modify-in-place → iter_mut, take ownership → into_iter.'),
    ('How do I handle errors in Rust well?','Define an error type per crate, often with thiserror crate: `#[derive(thiserror::Error, Debug)] enum MyError {...}`. Library returns Result<T, MyError>. Application uses anyhow::Result for ergonomic error handling. Use ? to propagate, .context("operation failed") to add detail. Avoid unwrap/expect in production code paths.'),
    ('How do I pattern-match an enum in Rust?','`match value { Variant1 => ..., Variant1(x) => ..., Variant3{a, b} => ..., _ => default }`. Match is exhaustive — compiler errors if you miss a variant. Use `if let Some(x) = opt { ... }` for one-arm match. while let for loops. Patterns can have guards: `Some(x) if x > 0 => ...`.'),
    ('What is the borrow checker telling me with "cannot borrow as mutable"?','Some immutable borrow is still in scope. Common cause: you took &x then tried &mut x while &x still alive. Fix: end the immutable borrow first (drop, scope, or refactor to not need both simultaneously). Sometimes split into smaller scopes with {}. NLL (Non-Lexical Lifetimes) has made this much rarer — error usually points to the conflicting borrow now.'),
    ('How do I share state between threads in Rust?','Arc<Mutex<T>> for owned shared state with interior mutability. Clone the Arc for each thread (cheap, increments counter). Lock inside thread: `arc.lock().unwrap()`. For read-heavy: Arc<RwLock<T>>. For message passing: std::sync::mpsc or crossbeam channels — often simpler than locks. The "share memory by communicating" advice from Go applies in Rust too.'),
    ('What is cargo and how does it differ from npm/pip?','Rust\'s package manager + build tool. `cargo build`, `cargo test`, `cargo run`, `cargo add` (modern). Cargo.toml = manifest (deps + metadata). Cargo.lock = exact versions (commit it). Crates from crates.io. Strong points: builds, tests, docs, formatter (cargo fmt), linter (cargo clippy) all unified. Workspaces for multi-crate projects. Far cleaner than the JS/Python equivalents.'),
    ('What is unsafe Rust and when use it?','Unlocks operations the borrow checker can\'t verify: dereferencing raw pointers, calling unsafe functions, mutating static muts, FFI to C. `unsafe { ... }` blocks. Use sparingly — wrap unsafe in safe APIs that uphold invariants. Common needs: FFI, hand-tuned performance, building data structures the borrow checker can\'t prove safe (lock-free queues). Most app code never needs unsafe.'),
    ('What is the difference between String concatenation methods?','`s1 + &s2` (s1 must be String, s2 reference). format!("{}{}", a, b) (most flexible, allocates). String::with_capacity(n) + push_str (no reallocs, fastest for known-size builds). [s1, s2, s3].concat(). s.to_owned() + &t. Performance: format! is convenient but slow if hot; with_capacity + push for hot loops.'),
    ('How do I read a file in Rust?','Quick: `std::fs::read_to_string(path)?` returns String. For binary: read(path) returns Vec<u8>. For line-by-line streaming (large files): BufReader::new(File::open(path)?).lines(). Always handle io::Error via Result. tokio::fs::* equivalents for async. Path types: &str or Path or PathBuf.'),
    ('What is a Vec vs array vs slice in Rust?','Array [T; N]: fixed size known at compile time, on stack. Vec<T>: heap-allocated, growable. Slice &[T]: borrowed view, dynamic size known at runtime, no ownership. Vec auto-coerces to &[T] so functions taking &[T] accept Vec. Use &[T] in parameters for max flexibility, return Vec when you need to give ownership.'),
    ('When use Rust vs Go vs C++?','Rust: memory safety + performance, complex correctness needs (compilers, OS kernels, game engines, browsers). Steep learning. Go: simple syntax, fast compile, great concurrency (goroutines + channels), good for networked services. Less control, GC pauses for latency-sensitive work. C++: legacy ecosystem, real-time low-latency, mature libs for some niches. Memory-unsafe by default; harder to learn well. Most new systems work today: Rust if perf+correctness matter, Go if you want simple+fast-to-ship.'),
]
LESSONS=_OWNERSHIP+_PATTERNS
