"""Scientific computing corpus — numpy/scipy idioms, statistics, simulation, signal processing."""
_SCIPY=[
    ('What is scipy?','Python scientific computing library built on numpy. Modules: scipy.optimize (curve fitting, minimization), scipy.stats (distributions, hypothesis tests), scipy.signal (filters, FFT helpers), scipy.linalg (more LA than numpy), scipy.sparse (sparse matrices), scipy.spatial (KD-trees, distance). Use when numpy isn\'t enough.'),
    ('What is curve fitting in scipy?','scipy.optimize.curve_fit. Define model function: `def f(x, a, b): return a*x + b`. Fit: `popt, pcov = curve_fit(f, xdata, ydata)`. Returns optimal params + covariance. Provide initial guess for nonlinear fits. Standard errors = sqrt(diag(pcov)). Always plot fit vs data to sanity check.'),
    ('What is scipy.stats?','Probability distributions (norm, t, chi2, etc.) + hypothesis tests (ttest_ind, mannwhitneyu, chi2_contingency, ks_2samp) + descriptive stats. Each distribution: pdf, cdf, ppf (quantile), rvs (random samples). Tests return statistic + pvalue. Use as the foundation of stats analyses in Python.'),
    ('What is sparse matrix and when use?','Matrix with mostly zeros — store only nonzero entries. Memory + speed savings can be huge. Formats: CSR (compressed sparse row, fast row slicing), CSC (column), COO (constructing), DOK (dict-of-keys). Use for: graphs (adjacency matrix), word counts, TF-IDF, finite element problems. scipy.sparse + scikit-learn handle.'),
    ('What is the FFT and when use?','Fast Fourier Transform: converts time-domain signal to frequency-domain. O(n log n). Use for: filtering noise (zero out frequencies, inverse), spectral analysis, convolution (multiply in freq domain), audio/image processing. numpy.fft + scipy.fft. Pick power of 2 length for max speed (zero-pad if needed).'),
]
_PROB=[
    ('What is the difference between PDF and CDF?','PDF (probability density function): height shows density (NOT probability) at each value. Area under PDF = 1. Continuous distributions only have PDF. CDF (cumulative): P(X ≤ x). Goes from 0 to 1. CDF\'s derivative = PDF. PPF (percent point function) = inverse CDF: given probability, return value (used for confidence intervals).'),
    ('What is the central limit theorem?','Sum/mean of many independent samples from any distribution (with finite variance) is approximately normally distributed, regardless of original distribution shape. With n ≥ ~30 it kicks in usually. Foundation of: confidence intervals, t-tests, much of inferential statistics. Why "normal" appears everywhere in nature/measurements.'),
    ('What is a confidence interval?','Range likely to contain the true population parameter. 95% CI = "if we repeated this experiment many times, 95% of computed CIs would contain the true value." NOT "95% probability the parameter is in this interval" (frequentist vs Bayesian interpretation differ). Width depends on sample size + variability + confidence level.'),
    ('What is statistical power?','Probability of detecting a real effect (rejecting null when alternative is true). 1 - β. Affected by: sample size (more = more power), effect size (bigger = more power), significance threshold (looser = more power but more false positives). Common standard: 0.80. Underpowered studies waste effort + produce unreliable null results.'),
    ('What is the difference between parametric and non-parametric tests?','Parametric: assume specific distribution (usually normal). More power if assumption holds. Examples: t-test, ANOVA. Non-parametric: distribution-free, work via ranks. More robust to outliers, less power. Examples: Mann-Whitney U, Kruskal-Wallis, Spearman correlation. Use when normality fails (small samples, skewed data, ordinal data).'),
    ('What is correlation vs causation in simple terms?','Correlated: vary together. Causation: one CAUSES the other. Correlation possible without causation: (1) reverse direction. (2) confounding variable. (3) coincidence in small data. Establish causation: intervene (RCT) or use natural experiments. Default skepticism: correlation does NOT imply causation.'),
]
_SIM=[
    ('What is Monte Carlo simulation?','Repeated random sampling to compute results. Estimate things hard to solve analytically. Example: estimate π by throwing darts at unit square, count fraction inside unit circle, π ≈ 4 * fraction. Convergence O(1/sqrt(n)) — many samples for high precision. Use for: integration in high dimensions, financial risk, particle physics, AI playouts (MCTS).'),
    ('What is a random walk?','At each step, move in a random direction. Many variants (1D, 2D, biased, on graphs). Expected distance from start after n steps: sqrt(n) (NOT n). Models: diffusion, stock prices (geometric random walk), molecular motion. Foundation of: Brownian motion, MCMC sampling, much physics + finance.'),
    ('What is MCMC (Markov Chain Monte Carlo)?','Sample from complex distributions by constructing a Markov chain whose stationary distribution is the target. Metropolis-Hastings: propose move, accept with probability that converges to target distribution. Hamiltonian Monte Carlo: uses gradient information for faster mixing. Used in: Bayesian inference, statistical physics, when direct sampling intractable.'),
    ('What is the law of large numbers?','As n → ∞, sample mean → true mean. Why averages of many measurements are reliable. Doesn\'t say WHEN — convergence rate is 1/sqrt(n) (slow). Variant: strong (almost-sure convergence) vs weak (in probability). Foundation of: polling, A/B testing, why Monte Carlo works.'),
]
_LINALG_APPLIED=[
    ('What is PCA (principal component analysis)?','Find directions of max variance in data. Project onto top-K components → reduce dimensions while preserving most info. Steps: center data, compute covariance, find eigenvectors (or SVD). Use for: visualization (project to 2D), feature reduction, denoising, exploratory analysis. Limitations: linear, sensitive to scale (always normalize first).'),
    ('What is SVD (singular value decomposition)?','Factorize matrix A = U Σ V^T. U, V orthonormal; Σ diagonal of singular values (sorted descending). Used in: PCA (Σ² gives variance), low-rank approximation (keep top-K singular vals), pseudo-inverse, recommender systems (Netflix prize), latent semantic analysis. Computed by numpy.linalg.svd.'),
    ('What is matrix rank?','Number of linearly independent rows/columns. Tells you the dimensionality of the column space. Full rank: rank = min(m, n). Rank-deficient: redundant rows/cols. Use cases: detecting collinearity in features, low-rank approximations, solving Ax = b (unique solution requires full rank).'),
    ('What is regression in plain terms?','Fit a function that predicts a numeric output from inputs. Linear regression: y = w·x + b, minimize squared error. Logistic regression: same but predict probability via sigmoid. Polynomial / ridge / lasso / kernel regression are variants. Foundation of supervised learning. Always: check residuals, watch for overfitting (regularization), inspect feature importance.'),
]
LESSONS=_SCIPY+_PROB+_SIM+_LINALG_APPLIED
