"""Security deep dive — cryptography basics, auth flows, OWASP, secure coding."""
_CRYPTO=[
    ('What is the difference between symmetric and asymmetric encryption?','Symmetric: same key encrypts + decrypts. Fast. AES-GCM (modern standard). Problem: how to share the key securely. Asymmetric (public-key): public key encrypts, private key decrypts. Slow. RSA, ECC, Ed25519. Used to securely exchange a symmetric key. Real world: TLS uses asymmetric (handshake to agree on key) + symmetric (bulk data). Best of both.'),
    ('What is AES-GCM and why use it?','AES = block cipher (symmetric, 128/192/256-bit key). GCM = Galois/Counter Mode — provides BOTH encryption AND authentication (detects tampering). Use GCM not just CBC (no auth) or ECB (terrible, leaks patterns). Always with a unique nonce per encryption (12 bytes random). Reusing nonce + key = catastrophic — attacker recovers both messages\' XOR.'),
    ('What is a hash function and what makes one cryptographic?','Maps arbitrary input to fixed-size output. Cryptographic hash needs: (1) deterministic, (2) pre-image resistance (can\'t reverse), (3) collision resistance (can\'t find two inputs hashing same), (4) avalanche effect (small input change → very different output). SHA-256 standard. NEVER use MD5 or SHA-1 for security (collisions found). Use BLAKE3 for speed.'),
    ('What is the difference between encoding, encryption, and hashing?','Encoding (base64, hex): reversible without a key, NOT security — just data format conversion. Encryption: reversible WITH a key — confidentiality. Hashing: ONE-WAY function — used for integrity check, passwords, deduplication. Common bug: "we base64 the password" — that\'s encoding, not security. Use bcrypt/argon2 for passwords.'),
    ('What is a digital signature?','Combines hashing + asymmetric crypto. Sign: hash(message) then encrypt hash with private key. Verify: decrypt signature with public key, compare to hash(message). Proves: only holder of private key could have created this, AND message hasn\'t been altered. Used in: code signing, TLS certs, JWTs (RS256/ES256). Faster than encrypting the whole message.'),
    ('What is a nonce and why is it critical?','"Number used once." Random or sequential value combined with key to ensure same plaintext → different ciphertext each time. Without it, identical messages produce identical ciphertext, leaking info + enabling replay attacks. Random nonce must be unpredictable + unique per encryption with same key. Counter-based requires careful state.'),
    ('What is HMAC?','Hash-based Message Authentication Code. Combines a secret key with a hash function: HMAC(key, msg) = hash((key XOR opad) || hash((key XOR ipad) || msg)). Provides integrity + authenticity (proves message came from someone with the key). Use HMAC-SHA256 for general purpose. Verify with constant-time comparison (avoid timing attacks).'),
    ('What is forward secrecy and why does it matter?','Property of a key exchange: even if long-term keys are later compromised, past session keys (and recorded ciphertext) remain secret. Achieved via ephemeral Diffie-Hellman (DHE/ECDHE) — each session uses fresh keys discarded after. Modern TLS (1.3) requires forward secrecy. Without it, a server private key compromise lets attacker decrypt ALL past recorded traffic.'),
]
_AUTH=[
    ('What is OAuth 2.0 in plain English?','Lets users grant third-party apps limited access to their account WITHOUT sharing the password. User logs into resource owner (Google, GitHub) → consents to app\'s requested scopes → owner gives app a TOKEN representing that limited access. App uses token to call APIs. Token expires, can be revoked. OAuth is for AUTHORIZATION, not authentication (though often used for both via OIDC).'),
    ('What is the difference between OAuth and OIDC?','OAuth 2.0: authorization framework — proves "this app is allowed to do X on user\'s behalf." OpenID Connect (OIDC): authentication layer on top of OAuth — adds an ID token (JWT containing user identity claims) so the app KNOWS who the user is. "Sign in with Google" is OIDC. Use OIDC for user login flows.'),
    ('What is a JWT and when use it?','JSON Web Token. Three parts (header, payload, signature) joined by dots, base64url-encoded. Self-contained: server can verify validity (signature) WITHOUT a database lookup. Use for: stateless API auth, short-lived access tokens. DON\'T use for: long-lived sessions (can\'t revoke without revocation list), storing sensitive data (payload is just base64 — readable). Verify signature with proper algorithm — never accept "alg: none."'),
    ('What is the difference between access token and refresh token?','Access token: short-lived (15min-1hr), authorizes API calls, carried in Authorization header. Refresh token: long-lived (days-months), used ONLY to get new access tokens from auth server, stored securely (HttpOnly cookie or secure storage). If access token leaks, damage bounded by short TTL. If refresh token leaks, attacker can stay in indefinitely — rotate refresh tokens on each use.'),
    ('What is multi-factor authentication?','Multiple independent factors: something you know (password), have (phone, hardware key), are (biometric). 2FA (two of these) defeats password-only attacks. TOTP (time-based codes from Google Authenticator) > SMS (vulnerable to SIM swap). FIDO2/WebAuthn (hardware keys, passkeys) > TOTP — phishing-resistant. Backup codes for account recovery essential.'),
    ('What is session hijacking and how to prevent?','Attacker steals session cookie/token and impersonates user. Prevention: (1) HttpOnly cookies (JS can\'t read). (2) Secure flag (HTTPS only). (3) SameSite=Strict/Lax (no cross-site sends). (4) Rotate session ID on login (defeats fixation). (5) Bind session to client (IP, user-agent — sometimes too restrictive). (6) Short timeout + idle expiry. (7) Force HTTPS everywhere.'),
]
_OWASP=[
    ('What are the OWASP Top 10 (2021)?','(1) Broken Access Control. (2) Cryptographic Failures (was Sensitive Data Exposure). (3) Injection. (4) Insecure Design. (5) Security Misconfiguration. (6) Vulnerable + Outdated Components. (7) Identification + Authentication Failures. (8) Software + Data Integrity Failures. (9) Security Logging + Monitoring Failures. (10) Server-Side Request Forgery (SSRF). Memorize broadly; consult details when designing or reviewing.'),
    ('What is SSRF (Server-Side Request Forgery) and how to prevent?','Attack: user-supplied URL causes server to fetch it. Bad URLs: localhost (access internal services), file:// (local files), 169.254.169.254 (AWS metadata, gives credentials). Prevention: (1) allowlist of allowed schemes (https only) + hosts. (2) resolve hostname; block private/loopback IPs. (3) disable redirects or re-validate post-redirect. (4) network egress controls — server can\'t reach internal IPs at all.'),
    ('What is path traversal and how to prevent?','User input like "../../etc/passwd" reads files outside intended dir. Prevention: (1) reject paths containing ".." (and decoded versions like "%2e%2e"). (2) normalize + check that resolved path stays under base dir (os.path.commonpath). (3) better: use a whitelist of allowed file IDs and never accept paths from users at all. (4) drop privileges so even if exploited, damage limited.'),
    ('What is CSRF and how to prevent in 2025?','Cross-Site Request Forgery: attacker site triggers authenticated request to your site via user\'s browser. Prevention: (1) SameSite=Lax cookies by default (most modern browsers). (2) CSRF tokens for state-changing forms. (3) check Origin/Referer header. (4) require re-auth for sensitive actions. SameSite=Lax has reduced CSRF significantly but not eliminated — still defense in depth.'),
    ('What is mass assignment vulnerability?','User submits extra fields you didn\'t expect, framework auto-binds them to model. Example: user submits `is_admin=true` in profile update, hits a User model that has is_admin → escalation. Fix: explicit allow-list of fields per endpoint (Django ModelForm fields=, Rails strong_parameters, Pydantic models with explicit schema). Never blindly `User(**request.data)`.'),
    ('What is rate limiting and how to implement?','Cap requests per second/minute/hour per actor (IP, user, API key). Prevents: brute force, scraping, DoS, runaway bots. Algorithms: token bucket (most common), sliding window, fixed window. Implement at gateway (nginx, Cloudflare, API Gateway) — closer to client, before hitting your servers. Return 429 with Retry-After header so polite clients back off.'),
]
_SECURE_CODE=[
    ('What is constant-time comparison and why?','Naive string equality short-circuits at first mismatch — attacker measures time to learn how many chars matched. Constant-time: always compares all chars (XOR + OR). Use for: secret comparison (HMAC verify, token compare, password hashes). Python: hmac.compare_digest. Java: MessageDigest.isEqual. Go: subtle.ConstantTimeCompare. Don\'t roll your own.'),
    ('What is "defense in depth" with concrete examples?','Multiple independent security controls so failure of any one doesn\'t mean total compromise. Example for a web app: (1) WAF blocks obvious attacks. (2) Input validation. (3) Parameterized queries ([REDACTED]). (4) Output encoding (XSS). (5) Least-privilege DB user. (6) Encryption at rest. (7) Audit log. (8) Anomaly detection. An attacker bypassing (1)-(3) still hits (4)-(8).'),
    ('What is secrets management best practice?','NEVER commit secrets to git (use git-secrets/trufflehog to scan). Store in: secrets manager (Vault, AWS Secrets Manager, GCP Secret Manager). Inject at runtime via env vars. Rotate regularly. Scope to specific services (least privilege). Audit access. For dev: .env files in .gitignore + a .env.example committed. For CI: platform-native secrets (GitHub Secrets, etc.).'),
    ('What is the difference between authentication and authorization?','Authentication = WHO you are (password, biometric, token). Authorization = WHAT you can do (RBAC, ACL, policies). Common bug: checking auth but not authz — user can call API but accidentally accesses other users\' data. Always check BOTH on every protected endpoint. Modern: ABAC (attribute-based) or RBAC + ABAC hybrid for fine-grained policies.'),
    ('What is "Trust on First Use" (TOFU)?','Accept new identity on first connection, remember it, alert if it changes. SSH host keys are TOFU. Trade-off: simpler than full PKI, but vulnerable to MITM on FIRST connection. Use when full PKI infeasible (peer-to-peer, IoT). Mitigate first-connect risk with out-of-band verification (compare key fingerprint via separate channel).'),
]
LESSONS=_CRYPTO+_AUTH+_OWASP+_SECURE_CODE
