"""SQL + database design corpus."""
_BASICS=[
    ('What is the difference between WHERE and HAVING in SQL?','WHERE filters rows BEFORE aggregation; HAVING filters AFTER aggregation. You can\'t use aggregate functions (COUNT, SUM, AVG) in WHERE — use HAVING. Example: `SELECT dept, COUNT(*) FROM emp WHERE active=1 GROUP BY dept HAVING COUNT(*) > 5` — WHERE drops inactive employees first, then groups, then keeps only depts with >5 active.'),
    ('What is the difference between INNER, LEFT, RIGHT, FULL JOIN?','INNER: rows where both tables have a match. LEFT: all rows from left + matches from right (NULL where no match). RIGHT: mirror. FULL: all rows from both, NULL where no match. CROSS: cartesian product (avoid unless intended). Visualize as Venn diagram: INNER is intersection, LEFT is left circle, FULL is union. Default JOIN means INNER JOIN.'),
    ('What is normalization and why use it?','Reducing redundancy by splitting data across tables linked by foreign keys. 1NF: atomic values (no comma-separated lists in cells). 2NF: no partial-key dependencies. 3NF: no transitive dependencies (non-key depends on non-key). Benefits: smaller storage, no update anomalies. Cost: more joins for queries. Modern systems sometimes DE-normalize for read performance — denormalize when reads vastly outnumber writes.'),
    ('What is an index and how do I know if I need one?','Auxiliary B-tree (or hash) that maps column values to row locations. Speeds up WHERE / JOIN / ORDER BY on indexed columns from O(n) to O(log n). Cost: storage + slower writes. Add index when: (1) query is slow AND uses the column in WHERE/JOIN. (2) high cardinality (lots of distinct values). (3) read-heavy workload. EXPLAIN your query to see if it uses the index.'),
    ('What does EXPLAIN do?','Shows the query planner\'s execution plan WITHOUT running the query (in most DBs). Reveals: which indexes are used, join order, estimated rows, scan type (seq scan vs index scan). Reading: bottom-up, left-to-right. Look for: "Seq Scan" on big tables (bad if you have an index), high estimated rows on a join (cardinality misestimate), expensive sorts. Postgres: EXPLAIN ANALYZE runs and shows actual timing.'),
    ('What is a foreign key constraint?','Column(s) that reference primary key of another table. DB enforces: you can\'t insert a value that doesn\'t exist in the referenced table; you can\'t delete the referenced row unless cascading rules say so. Catches data integrity bugs at write time instead of detecting orphans later. ON DELETE CASCADE/SET NULL/RESTRICT controls behavior when parent deleted. Use FKs; trust the DB.'),
    ('What is the difference between UNION and UNION ALL?','Both stack rows from multiple SELECTs. UNION removes duplicates (implicit DISTINCT — costs a sort). UNION ALL keeps duplicates (fast). 99% of the time you want UNION ALL — duplicates are usually impossible by query construction, and the sort wastes time. Use UNION only when duplicate rows are possible AND you want them removed.'),
    ('What is a subquery vs a CTE?','Both let you reuse a query result. Subquery: inline in WHERE/FROM. CTE: WITH name AS (...) at top of query, used by name. CTEs are usually MORE readable for complex queries — name them so the structure documents itself. Recursive CTEs handle hierarchies (org charts, tree traversal). Postgres CTEs are an "optimization barrier" historically — recent versions inline them when safe.'),
    ('What is the difference between DELETE, TRUNCATE, and DROP?','DELETE: removes rows matching WHERE; respects triggers/FKs; logged per row (slow at scale); table structure preserved. TRUNCATE: removes ALL rows fast; resets auto-increment; minimal logging; usually can\'t use in transactions or with FKs. DROP: removes the table entirely (structure + data). Choose by need: targeted removal → DELETE, fast clear → TRUNCATE, remove table → DROP.'),
    ('What is ACID?','Properties guaranteed by relational DB transactions. Atomicity: all-or-nothing — partial commit impossible. Consistency: constraints (FK, UNIQUE, CHECK) always hold; transactions transform DB from valid state to valid state. Isolation: concurrent transactions don\'t see each other\'s in-progress changes (configurable via isolation levels). Durability: committed data survives crash. NoSQL often trades some of these for scale (BASE: Basically Available, Soft state, Eventual consistency).'),
    ('What are SQL isolation levels?','Read Uncommitted: see dirty writes (rarely used). Read Committed: see only committed data, but each read can return different rows ("non-repeatable read"). Repeatable Read: snapshot at transaction start, but new rows may appear ("phantom read"). Serializable: full isolation, as if transactions run one at a time. Higher isolation = more locking/conflict. Postgres default = Read Committed; MySQL InnoDB default = Repeatable Read.'),
    ('What is a deadlock and how to avoid?','Two transactions each hold a lock the other needs → both wait forever. DB detects and kills one (deadlock victim, application sees error). Avoid: (1) acquire locks in the SAME ORDER everywhere (e.g., always sort IDs ascending). (2) shorter transactions = less window. (3) lower isolation if app can tolerate. (4) retry on deadlock error — often the simplest fix. (5) for hot rows, use explicit advisory locks or queue.'),
    ('What is a covering index?','Index that contains ALL columns the query needs (in SELECT, WHERE, ORDER BY) so the DB never reads the table — answers query from the index alone. Postgres: include with INCLUDE clause. MySQL: any non-clustered index can cover. Trade-off: bigger index, slower writes. Worth it for hot read queries. To know if used: EXPLAIN shows "index only scan" or "using index."'),
    ('How do I paginate large result sets?','Two patterns. OFFSET/LIMIT: simple but slow for large offsets (DB still scans skipped rows). Keyset / cursor pagination: `WHERE id > last_seen_id ORDER BY id LIMIT 50` — constant time. Always ORDER BY a unique stable column (or unique tiebreaker after sort column). For UI: keyset for infinite-scroll, OFFSET for numbered pages (and only first few are fast).'),
]
_DESIGN=[
    ('When to use a relational DB vs NoSQL?','Relational (Postgres, MySQL): structured data with relations, transactions, complex queries (JOIN), strong consistency needs. NoSQL document (Mongo, Firestore): nested/varied schemas, fast read of whole document, eventual consistency OK. NoSQL key-value (Redis, DynamoDB): O(1) lookup by key, simple access patterns, scale horizontally. NoSQL columnar (Cassandra, ClickHouse): analytical workloads on huge tables. Most apps: start with Postgres; it scales further than people think.'),
    ('What is a primary key vs unique key?','PK: identifies each row uniquely + NOT NULL + only one per table. Often INT/BIGINT auto-increment or UUID. UNIQUE: enforces uniqueness for a column (or combination) but allows NULLs (varies by DB) + can have many per table. Best practice: surrogate PK (auto-id) for stability + UNIQUE on natural keys (email, sku) for business uniqueness. Avoid using natural keys as PK — they change (people marry, products rename).'),
    ('When should I use UUID vs auto-increment ID?','Auto-increment: smaller (4 or 8 bytes), faster indexes/joins, sequential = better cache locality, predictable. UUID: globally unique (no coordination needed across shards/microservices), unguessable (no enumeration attacks), client-can-generate-before-insert. Modern: UUIDv7 keeps time-ordered prefix, mostly fixes UUID\'s index-locality downside. Pick UUID if distributed; auto-int otherwise; UUIDv7 if you want both.'),
    ('What is a database transaction and when to use it?','Group of statements that succeed atomically. Use whenever a logical operation spans multiple writes that must all succeed or all roll back (transfer money: debit + credit, both or neither). BEGIN / commit / ROLLBACK in raw SQL; framework usually wraps it (Django @transaction.atomic, SQLAlchemy session). Keep transactions SHORT — long ones hold locks, hurt concurrency. Avoid network calls inside transactions.'),
    ('What is N+1 query problem?','Loop that runs 1 query to fetch a list, then N queries to fetch related data for each item — instead of a single JOIN or bulk fetch. Example: posts = Post.all(); for p in posts: print(p.author.name) → 1 + N queries. Fix: prefetch/eager-load (Django select_related/prefetch_related, SQLAlchemy joinedload, GraphQL DataLoader). The classic ORM perf trap. Log all queries in dev to catch.'),
    ('What is database connection pooling?','Reuse a pool of pre-opened DB connections instead of opening one per request. Opening a TCP+auth handshake is slow (10-100ms). Pool size = peak concurrent queries (NOT requests). Postgres can\'t handle many thousands of connections — use PgBouncer in front. Settings to tune: pool min/max, connection timeout, idle timeout, lifetime (rotate to avoid stale connections).'),
    ('What is a materialized view?','Cached result of a query, stored as if it were a table. Refreshed manually or on schedule. Use for: expensive aggregations queried often where slight staleness OK (dashboard metrics, leaderboards). Postgres: CREATE MATERIALIZED VIEW + REFRESH MATERIALIZED VIEW. Trade real-time accuracy for read speed. Modern alternatives: Postgres MV + cron, or streaming systems (Materialize, RisingWave) that auto-update.'),
]
LESSONS=_BASICS+_DESIGN
