"""Real-world production war stories + lessons — what breaks, what saves you."""
_OUTAGES=[
    ('What is a thundering herd problem?','Many clients/processes wake up simultaneously and overwhelm a resource. Example: cache key expires, 1000 servers each try to recompute it, hammer the DB. Mitigations: (1) cache stampede protection (only one rebuilds, others wait). (2) jitter on retry (random backoff prevents synchronized waves). (3) request coalescing (group identical concurrent requests). (4) circuit breakers (fail fast when downstream sick).'),
    ('What is cache stampede and how to prevent?','Specific thundering herd: cache miss → many concurrent requests recompute the same value. Fix patterns: (1) "lock" — only one request recomputes, others wait or return stale. (2) "probabilistic early expiration" — refresh BEFORE expiry randomly. (3) "stale-while-revalidate" — serve stale while async refresh runs. Modern caches (Caffeine, redis-lock libs) implement these.'),
    ('What is a cascading failure?','One service fails → downstream services that depend on it also fail → their dependents fail → entire system dies. Classic: payment service slow → checkout slow → web frontend slow → mobile app times out everywhere. Mitigations: circuit breakers (stop calling sick service), bulkheads (isolate failure domains), timeouts (don\'t wait forever), backpressure (refuse load you can\'t handle).'),
    ('What is the Mariner 1 lesson for software?','1962: Mariner 1 destroyed shortly after launch due to a missing hyphen (or per other sources, missing overbar) in guidance code. Lessons: small notation mistakes can have huge cost; software for critical systems needs formal review + redundancy + simulation; always test in conditions resembling production. Modern equivalent: typo in Cloudflare config caused half the internet outage 2019.'),
    ('What is the Knight Capital incident?','2012: $440M loss in 45 minutes. Old test code reactivated by deploy mishap — a flag that hadn\'t been used in 8 years was still in code. Repurposed for different meaning. Deployed to 7 of 8 servers; 8th had old code with old flag meaning → traded billions of shares against itself. Lessons: dead code is risk; deploys must be all-or-nothing atomic; kill old code paths aggressively; have kill switches you can hit fast.'),
    ('What is the Therac-25 lesson?','Medical radiation device with race condition + missing safety interlock killed/injured patients (1985-87). Lessons: (1) NEVER trust software-only safety (hardware interlocks). (2) edge cases under time pressure manifest in production. (3) shared mutable state + threading is dangerous. (4) error messages must be informative (theirs were cryptic codes). Why critical systems still favor mechanical/electrical safety.'),
]
_BACKUP=[
    ('Why are backups not enough — you need RESTORE?','Untested backup is not a backup. Common failures: corrupted backup files (silent data corruption), backup script broken for months, encryption key lost, format unreadable on new system, restore takes 48 hours when business needs 4. Test restores monthly. Time the restore. Practice in non-prod. Document the procedure. Your first production restore should not be your first ever restore.'),
    ('What is the 3-2-1 backup rule?','3 copies of data: original + 2 backups. 2 different media types (e.g., disk + tape, or disk + cloud). 1 offsite (different location, in case fire/flood/theft). For critical data: also 1 offline (immune to [REDACTED] encrypting all reachable systems). Tape made a comeback for offline air-gap protection.'),
    ('What is RPO vs RTO?','RPO (Recovery Point Objective): how much data CAN you afford to lose? Determines backup frequency. RPO 1 hour = backups every hour. RTO (Recovery Time Objective): how long CAN you be down? Determines restore architecture. RTO 5 minutes = hot standby. RTO 24 hours = cold-recovery from backup. Costs scale exponentially as RPO/RTO approach zero.'),
]
_OPS=[
    ('What is on-call and how to make it sustainable?','Rotation of engineers responding to alerts 24/7. Sustainable means: (1) alert volume is manageable (tune noisy alerts). (2) runbooks for known scenarios. (3) compensation/comp time for paged hours. (4) postmortems lead to fewer pages over time. (5) team size > 4 (rotation isn\'t brutal). Unsustainable on-call = burnout + attrition.'),
    ('What is the "left pad incident" of 2016?','One developer unpublished a tiny npm package (11 lines of code) after a name dispute. Thousands of downstream projects broke instantly because npm allowed full removal. Lessons: (1) supply chain fragility — one tiny dep can stop the world. (2) audit dependencies (do you need 100 transitive deps for 100 lines of code?). (3) immutable package registries (npm now disallows unpublish after 72 hours). (4) lockfiles + vendoring matter.'),
    ('What is the Heartbleed lesson?','2014: OpenSSL bug let attackers read server memory via crafted heartbeat packets. Exposed passwords, keys, etc. Lessons: (1) critical infrastructure with shoestring funding is fragile. (2) memory-unsafe languages bite eventually — modern crypto increasingly in Rust. (3) version + vulnerability tracking matters (most affected didn\'t know). (4) Core Infrastructure Initiative now funds critical OSS — but coverage spotty.'),
    ('What is alert fatigue and how to fix?','Too many noisy alerts → people ignore them → real one missed. Caused by: alerts that aren\'t actionable, alerts that fire repeatedly for same cause, alerts at wrong threshold. Fix: review weekly, tune or delete noisy alerts, require alerts be actionable, only page on user-visible impact, route low-severity to ticket queue. Healthy on-call rotation: <5 actionable pages per week.'),
    ('What is the "you build it, you run it" principle?','Engineers operate the systems they build. Aligns incentives: poorly-designed systems wake up the people who built them. Promotes: better monitoring at build time, smaller blast radius, faster fix cycles. Trade-off: requires culture + tooling (every team needs ops skills). Amazon famously enforces this; not for every org.'),
    ('What is chaos engineering?','Deliberately inject failures in production-like environments to verify the system actually handles them. Netflix\'s Chaos Monkey kills random EC2 instances. Tests: dependencies failing, network partitions, region outages, slow disks. Surfaces hidden assumptions and untested recovery paths. Start small (game days), scale up to continuous chaos. Production-grade systems benefit hugely.'),
]
_DESIGN_FAILURES=[
    ('What is the second-system effect?','Brooks (1975): the second system an architect designs tends to be over-engineered — they pile in every feature they couldn\'t add to the first. Result: bloated, slow, fails. Famous example: IBM OS/360 vs OS/360 successor. Modern: microservices rewrites that don\'t match the monolith\'s usefulness. Cure: discipline, MVP mindset, write down what NOT to include.'),
    ('What is the big rewrite trap?','"Let\'s rewrite the legacy system from scratch." Almost always: takes longer than expected, loses features the old system had quietly, business runs on TWO systems for years. Joel Spolsky\'s "Things You Should Never Do Part 1" makes the case. Better: strangler fig pattern — replace incrementally, never have a flag day.'),
    ('What is Conway\'s Law?','"Any organization that designs a system... will produce a design whose structure is a copy of the organization\'s communication structure." Org charts show up in software architecture. If you want service boundaries different from team boundaries, you need to restructure teams (inverse Conway maneuver) or live with the friction. Goes both ways: how you organize determines what you build.'),
    ('What is feature creep and how to fight it?','Scope expanding mid-project. Each "small addition" individually reasonable but cumulatively kills delivery. Fight: (1) explicit list of NOT in scope. (2) "if we add this, what do we cut?" forced trade. (3) ship something small + iterate. (4) defer ambiguous requests to next release. (5) calculate cost-of-delay for adds. Hardest part: saying no to stakeholders who don\'t see cost.'),
    ('What is YAGNI applied as a habit?','"You Aren\'t Gonna Need It." Don\'t build for speculative needs. Each feature has carrying cost (test it, maintain it, document it, security implications). Premature flexibility creates the wrong abstraction. Add complexity only when you have THREE concrete cases that need it. Hardest discipline in software: shipping the boring minimum.'),
]
LESSONS=_OUTAGES+_BACKUP+_OPS+_DESIGN_FAILURES
